// Mocks generated by Mockito 5.4.6 from annotations
// in client_app/test/features/admin/presentation/providers/admin_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:client_app/core/error/app_error.dart' as _i5;
import 'package:client_app/features/admin/data/admin_repository.dart' as _i2;
import 'package:client_app/features/admin/domain/dtos/user_dtos.dart' as _i8;
import 'package:client_app/features/admin/domain/models/queue_stats.dart'
    as _i9;
import 'package:client_app/features/auth/domain/models/user.dart' as _i6;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AdminRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminRepository extends _i1.Mock implements _i2.AdminRepository {
  MockAdminRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.AppError, List<_i6.User>>> getUsersByOrganization(
    String? orgId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByOrganization, [orgId]),
            returnValue:
                _i3.Future<_i4.Either<_i5.AppError, List<_i6.User>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.AppError, List<_i6.User>>>(
                    this,
                    Invocation.method(#getUsersByOrganization, [orgId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.AppError, List<_i6.User>>>);

  @override
  _i3.Future<_i4.Either<_i5.AppError, void>> updateUserRole(
    String? userId,
    String? newRole,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserRole, [userId, newRole]),
            returnValue: _i3.Future<_i4.Either<_i5.AppError, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.AppError, void>>(
                this,
                Invocation.method(#updateUserRole, [userId, newRole]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppError, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppError, void>> createUser(
    _i8.UserCreateDto? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [data]),
            returnValue: _i3.Future<_i4.Either<_i5.AppError, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.AppError, void>>(
                this,
                Invocation.method(#createUser, [data]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppError, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppError, void>> updateUser({
    required String? userId,
    required _i8.UserUpdateDto? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [], {#userId: userId, #data: data}),
            returnValue: _i3.Future<_i4.Either<_i5.AppError, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.AppError, void>>(
                this,
                Invocation.method(#updateUser, [], {
                  #userId: userId,
                  #data: data,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppError, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppError, void>> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i3.Future<_i4.Either<_i5.AppError, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.AppError, void>>(
                this,
                Invocation.method(#deleteUser, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppError, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppError, _i9.QueueStats>> getQueueStats() =>
      (super.noSuchMethod(
            Invocation.method(#getQueueStats, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.AppError, _i9.QueueStats>>.value(
                  _i7.dummyValue<_i4.Either<_i5.AppError, _i9.QueueStats>>(
                    this,
                    Invocation.method(#getQueueStats, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.AppError, _i9.QueueStats>>);
}
