"""Large Language Model (LLM) Integration Schemas.

This module defines the standardized response structures for interacting with
various LLM providers (Google Gemini, OpenAI, etc.), including support for
advanced reasoning tokens and tool calls.
"""

from __future__ import annotations

import logging
from typing import Annotated, Any, Literal

from fastapi import status
from pydantic import ConfigDict, Field, field_validator

from backend_v2.exceptions import AppException, ErrorCodes
from backend_v2.models.domain.usage import TokenUsage
from backend_v2.models.dtos.base import BaseDTO, BaseResponseDTO

logger = logging.getLogger(__name__)


class LLMResponse(BaseDTO):
    """Unified response wrapper for all LLM providers (Gemini 3, GPT-5.1, etc.).

    Supports advanced features like 'Meaning Tokens' (Thought Signature / Reasoning Blob).

    Attributes:
        content: The primary text content generated by the model.
        parsed_content: Pre-parsed structured data from the provider.
        reasoning_token: Encrypted Blob representing the model's internal reasoning state.
        tool_calls: List of tool use requests invoked by the model.
        token_usage: Token usage statistics (prompt, completion, total, cost).
        provider_metadata: Provider-specific raw metadata (e.g. finish_reason).
        messages: The full list of messages sent to the model for audit purposes.
        override_reason: Reason for override if applicable.
        system_fingerprint: System fingerprint identifying exact model weights used.
    """

    content: Annotated[str, Field(description="The primary text content generated by the model.")]
    parsed_content: Annotated[
        Any | None,
        Field(description="Pre-parsed structured data (Dict or Pydantic Model) from the provider."),
    ] = None
    reasoning_token: Annotated[
        str | None,
        Field(
            description=(
                "Encrypted Blob representing the model's internal reasoning state "
                "(e.g. Gemini 'thought_signature' or OpenAI 'reasoning_blob'). "
                "Must be passed back to continue the thought process."
            ),
        ),
    ] = None
    tool_calls: Annotated[
        list[dict[str, Any]] | None,
        Field(description="List of tool use requests invoked by the model."),
    ] = None
    token_usage: Annotated[
        TokenUsage,
        Field(description="Token usage statistics (prompt, completion, total, cost)."),
    ] = Field(default_factory=lambda: TokenUsage(prompt_tokens=0, completion_tokens=0, total_tokens=0))
    provider_metadata: Annotated[
        dict[str, Any],
        Field(description="Provider-specific raw metadata (e.g. finish_reason)."),
    ] = Field(default_factory=dict)
    messages: Annotated[
        list[dict[str, Any]] | None,
        Field(description="The full list of messages (prompts) sent to the model for audit purposes."),
    ] = None
    override_reason: Annotated[str | None, Field(description="Reason for override if applicable.")] = None
    system_fingerprint: Annotated[
        str | None, Field(description="System fingerprint identifying exact model weights used.")
    ] = None

    model_config = ConfigDict(frozen=True)

    @field_validator("content", mode="after")
    @classmethod
    def validate_non_empty(cls, v: str) -> str:
        """Validates that the generated content is not an empty-equivalent placeholder.

        Args:
            v: The raw generated string content to check.

        Returns:
            The pristine string content validation parsed value.

        Raises:
            AppException: Triggered with HTTP 400 when an invalid empty signature is received.
        """
        clean_v = str(v).strip().lower()
        if clean_v in {"null", "none", "n/a", "ei saatavilla"}:
            msg = f"LLM returned an invalid empty-equivalent string: '{v}'"
            logger.error("[LLMModel] %s: %s", ErrorCodes.VALIDATION_FAILED.name, msg, exc_info=True)
            raise AppException(
                message=msg,
                status_code=status.HTTP_400_BAD_REQUEST,
                details={"error_code": ErrorCodes.VALIDATION_FAILED.value},
            )

        return v


class LLMProviderConfig(BaseDTO):
    """Configuration for an LLM Provider.

    Attributes:
        id: Configuration ID (unique key).
        provider: Provider type (e.g. 'openai', 'vertex_ai').
        model_name: Model identifier (e.g. 'gpt-4', 'gemini-pro').
        api_key: API Key (masked on read).
        base_url: Base URL for API calls.
        temperature: Sampling temperature.
        top_p: Nucleus sampling probability.
        top_k: Top-K sampling limit.
        tpm_limit: Tokens per minute limit. 0=unlimited.
        rpm_limit: Requests per minute limit. 0=unlimited.
        default_max_tokens: Default max output tokens.
        parsing_mode: Instructor parsing mode.
        caching_strategy: Caching strategy.
        vertex_location: Google Cloud Region (Vertex AI only).
        supports_grounding: Whether this model supports Google Search Grounding.
        is_active: Whether this provider is active.
        additional_params: Additional provider-specific parameters.
    """

    id: Annotated[
        str,
        Field(
            ...,
            min_length=1,
            pattern=r"^([a-z]{2,5})_[a-zA-Z0-9]{8,}$",
            description="Configuration ID (unique key).",
            json_schema_extra={"x-ui-hidden": True},
        ),
    ]
    provider: Annotated[
        str,
        Field(
            ...,
            min_length=1,
            pattern=r"\S",
            description="Provider type (e.g. 'openai', 'vertex_ai').",
            json_schema_extra={"x-ui-label": "Provider"},
        ),
    ]
    model_name: Annotated[
        str,
        Field(
            ...,
            min_length=1,
            pattern=r"\S",
            description="Model identifier (e.g. 'gpt-4', 'gemini-pro').",
            json_schema_extra={"x-ui-label": "Model Name"},
        ),
    ]
    api_key: Annotated[
        str | None,
        Field(description="API Key (masked on read).", json_schema_extra={"x-ui-label": "API Key"}),
    ] = None
    base_url: Annotated[
        str | None,
        Field(description="Base URL for API calls.", json_schema_extra={"x-ui-label": "Base URL"}),
    ] = None
    temperature: Annotated[
        float,
        Field(
            description="Sampling temperature.",
            json_schema_extra={"x-ui-label": "Temperature"},
        ),
    ] = 0.7
    top_p: Annotated[
        float | None,
        Field(
            description="Nucleus sampling probability.",
            json_schema_extra={"x-ui-label": "Top-P"},
        ),
    ] = None
    top_k: Annotated[
        int | None,
        Field(
            ge=1,
            description="Top-K sampling limit.",
            json_schema_extra={"x-ui-label": "Top-K"},
        ),
    ] = None
    tpm_limit: Annotated[
        int,
        Field(
            ...,
            ge=0,
            description="Tokens per minute limit. 0=unlimited.",
            json_schema_extra={"x-ui-label": "TPM Limit"},
        ),
    ]
    rpm_limit: Annotated[
        int,
        Field(
            ...,
            ge=0,
            description="Requests per minute limit. 0=unlimited.",
            json_schema_extra={"x-ui-label": "RPM Limit"},
        ),
    ]
    default_max_tokens: Annotated[
        int | None,
        Field(
            ge=1,
            description="Default max output tokens.",
            json_schema_extra={"x-ui-label": "Max Tokens"},
        ),
    ] = None
    parsing_mode: Annotated[
        str | None,
        Field(
            description="Instructor parsing mode (e.g. 'STRUCTURED_JSON', 'JSON').",
            json_schema_extra={"x-ui-label": "Parsing Mode"},
        ),
    ] = None
    caching_strategy: Annotated[
        str | None,
        Field(
            description="Caching strategy (e.g. 'anthropic_ephemeral', 'gemini_native').",
            json_schema_extra={"x-ui-label": "Caching Strategy"},
        ),
    ] = None
    vertex_location: Annotated[
        str | None,
        Field(
            description="Google Cloud Region (Vertex AI only).",
            json_schema_extra={"x-ui-label": "Vertex Location"},
        ),
    ] = None
    supports_grounding: Annotated[
        bool,
        Field(
            description="Whether this model supports Google Search Grounding.",
            json_schema_extra={"x-ui-label": "Supports Grounding"},
        ),
    ] = False
    is_active: Annotated[
        bool,
        Field(
            description="Whether this provider is active.",
            json_schema_extra={"x-ui-label": "Is Active"},
        ),
    ] = True
    additional_params: Annotated[dict[str, Any], Field(description="Additional provider-specific parameters.")] = Field(
        default_factory=dict
    )

    model_config = ConfigDict(frozen=True)

    @field_validator("temperature", mode="after")
    @classmethod
    def validate_temperature(cls, v: float) -> float:
        """Validates that the temperature is within bounds [0.0, 2.0] at runtime.

        Args:
            v: The temperature variable.

        Returns:
            The validated temperature value.

        Raises:
            AppException: Raised when temperature falls outside safety bounds.
        """
        if not (0.0 <= v <= 2.0):
            msg = "Temperature must be between 0.0 and 2.0"
            logger.error("[LLMProviderConfig] %s: %s", ErrorCodes.VALIDATION_FAILED.name, msg, exc_info=True)
            raise AppException(
                message=msg,
                status_code=status.HTTP_400_BAD_REQUEST,
                details={"error_code": ErrorCodes.VALIDATION_FAILED.value},
            )
        return v

    @field_validator("top_p", mode="after")
    @classmethod
    def validate_top_p(cls, v: float | None) -> float | None:
        """Validates that top_p is within bounds [0.0, 1.0] at runtime.

        Args:
            v: The nucleus sampling probability.

        Returns:
            The validated top_p configuration choice.

        Raises:
            AppException: Raised when top_p boundary constraint is breached.
        """
        if v is not None and not (0.0 <= v <= 1.0):
            msg = "top_p must be between 0.0 and 1.0"
            logger.error("[LLMProviderConfig] %s: %s", ErrorCodes.VALIDATION_FAILED.name, msg, exc_info=True)
            raise AppException(
                message=msg,
                status_code=status.HTTP_400_BAD_REQUEST,
                details={"error_code": ErrorCodes.VALIDATION_FAILED.value},
            )
        return v


class AdHocTestRequest(BaseDTO):
    """Request payload for ephemeral LLM testing.

    Attributes:
        provider: Provider identifier.
        api_key: Optional API key for testing.
        system_instruction: System prompt.
        user_prompt: User prompt.
        model_params: Model parameters override.
    """

    provider: Annotated[str, Field(..., min_length=1, pattern=r"\S", description="Provider identifier.")]
    api_key: Annotated[str | None, Field(default=None, description="Optional API key for testing.")]
    system_instruction: Annotated[str, Field(..., min_length=1, pattern=r"\S", description="System prompt.")]
    user_prompt: Annotated[str, Field(..., min_length=1, pattern=r"\S", description="User prompt.")]
    model_params: Annotated[dict[str, Any], Field(default_factory=dict, description="Model parameters override.")]

    model_config = ConfigDict(frozen=True)


class AdHocTestResponse(BaseResponseDTO):
    """Response for ephemeral LLM testing.

    Attributes:
        content: Generated content.
        latency_ms: Execution latency in milliseconds.
        status: Status string (e.g. 'success', 'error').
    """

    content: Annotated[str, Field(..., min_length=1, pattern=r"\S", description="Generated content.")]
    latency_ms: Annotated[float, Field(..., ge=0.0, description="Execution latency in milliseconds.")]
    status: Annotated[Literal["success", "error"], Field(..., description="Status string (e.g. 'success', 'error').")]

    model_config = ConfigDict(frozen=True)
