"""Search hooks for executing external searches (e.g. Google)."""

import logging

from backend_v2.core.hook_registry import HookExecutionContext, hook_registry
from backend_v2.exceptions import AppException, ErrorCodes
from backend_v2.hooks.search_client import VertexAISearchTool

logger = logging.getLogger(__name__)


from typing import Any


@hook_registry.register(name="execute_google_search")
async def execute_google_search_hook(data: dict[str, Any], context: HookExecutionContext) -> dict[str, Any]:
    """Workflow Data wrapper for execute_google_search.

    Executes Google Search via Vertex AI Grounding based on hypotheses generated by the Analyst agent.

    Logic (Fail Fast):
    1. Extracts 'analyst' data. If missing, logs warning and returns (safe default for optional step).
    2. Extracts queries. If none, returns.
    3. Initializes Tool. If config missing, RAISES ConfigurationError (Crashing is better than silent fail).
    4. Executes Search. If fails, RAISES AppException.
    5. Returns dict with 'search_result'.

    Args:
        data (dict): Current data containing analysis hypotheses.

    Returns:
        dict: Updated data with search results.

    Raises:
        AppException: If configuration is missing, data is invalid, or execution fails.
    """
    logger.debug("[SearchHook] execute_google_search_hook CALLED (Vertex AI Grounding)")

    if not data:
        return {}

    # 1. Extract Analyst Output
    # V2 Isolation: If running as a post-hook, 'data' is already the local step dictionary.
    analyst_output = data.get("step_analyst", data)

    # 2. Extract Queries
    queries: list[str] = []

    hypotheses = analyst_output.get("hypotheses", [])

    # V2 Extraction: JSON may be stringified inside dynamic PromptBlock keys
    for key, value in analyst_output.items():
        if isinstance(value, str) and '"hypotheses"' in value:
            import json
            try:
                parsed = json.loads(value)
                if isinstance(parsed, dict) and "hypotheses" in parsed:
                    hypotheses.extend(parsed["hypotheses"])
            except Exception:
                pass

    for hyp in hypotheses:
        if isinstance(hyp, dict):
            sq = hyp.get("search_query")
            if sq and isinstance(sq, str) and len(sq.strip()) > 3:
                queries.append(sq)

    if not queries:
        logger.debug("[SearchHook] No valid queries generated. Skipping search.")
        return {}

    # 4. Initialize Tool via SSOT Factory

    from backend_v2.exceptions import ConfigurationError
    from backend_v2.llm.client import LLMClient

    # Hooks executing within an async workflow loop should safely execute this.
    # Note: If executed synchronously, this would require `asyncio.run()`,
    # but the framework is expected to handle async properly in `execute_google_search`
    # because the hook signature itself is `async def`.
    try:
        repository = context.repository
        search_client = await LLMClient.from_strategy("SearchHook", repository=repository)
        model_id_full = search_client._config.model_name if search_client._config else None  # type: ignore

        # Vertex tools expect the raw model id without provider prefix 'vertex_ai/'
        if model_id_full and model_id_full.startswith("vertex_ai/"):
            model_id = model_id_full.split("/")[-1]
        else:
            model_id = model_id_full

        if not search_client._config or not search_client._config.supports_grounding:  # type: ignore
            # We strictly enforce that the allocated strategy must support grounding.
            raise ConfigurationError("The assigned 'SearchHook' strategy does not have supports_grounding=True.")

        tool = VertexAISearchTool(model_id=model_id)
    except ConfigurationError as e:
        error_code = ErrorCodes.SEARCH_CONFIG_ERROR
        msg = f"Search configuration failed: {e.message}"
        logger.error(f"[SearchHook] {error_code.name}: {msg}")
        raise ConfigurationError(msg, details={"error_code": error_code}) from e

    # 5. Extract Language
    # If inputs is missing due to V2 isolation, default to "en" or attempt a global fetch if repository is injected
    inputs = data.get("inputs", {})
    lang_code = "en"
    if isinstance(inputs, dict):
        lang_code = inputs.get("language", "en")

    # 6. Execute Search (Vertex AI Grounding)
    try:
        logger.debug(f"[SearchHook] Executing {len(queries)} searches (Lang: {lang_code})...")

        # tool.search raises ServiceUnavailableError or AppException on failure.
        client_results = tool.search(queries, limit=3, language=lang_code)

        # STRICT Enforce: Tool must return Objects, not dicts.
        if client_results and isinstance(client_results[0], dict):
            error_code = ErrorCodes.INVALID_OUTPUT_SCHEMA
            msg = "Search Tool returned dicts instead of Pydantic Models. Strict Pydantic Enforcement Violation."
            logger.error(f"[SearchHook] {error_code.name}: {msg}")
            raise AppException(message=msg, status_code=500, details={"error_code": error_code})

        # Convert Client Model -> Domain Model (Strict Mapping)
        domain_items: list[dict[str, Any]] = []
        for c_res in client_results:
            domain_items.append({"title": c_res.title, "link": c_res.link, "snippet": c_res.snippet})

        # 7. Isolated dict return
        logger.info(f"[SearchHook] Search complete. Found {len(domain_items)} results. Isolated to 'search_result'.")
        return {"search_result": {"results": [i for i in domain_items]}}

    except AppException as e:
        # Re-raise known AppExceptions (ConfigurationError, ServiceUnavailableError, etc.)
        # This preserves the original error code and details.
        raise e
    except Exception as e:
        # Catch unexpected unknown errors and wrap them
        error_code = ErrorCodes.SEARCH_EXECUTION_FAILED
        msg = f"Unexpected error in Search Hook: {e}"
        logger.error(f"[SearchHook] {error_code.name}: {msg}", exc_info=True)
        raise AppException(message=msg, status_code=500, details={"error_code": error_code}) from e
