"""Context variables and evaluation execution trace states."""

from typing import Annotated, Any

from pydantic import ConfigDict, Field

from backend_v2.models.domain.analyst import SearchResult
from backend_v2.models.domain.archivist import ArchivistOutputDTO
from backend_v2.models.domain.coach import BibliographyResult, CoachingPlanDTO
from backend_v2.models.domain.linguistics import LinguisticsResultDTO
from backend_v2.models.dtos.base import BaseDTO
from backend_v2.models.dtos.report.matrix import MatrixObservabilityDTO
from backend_v2.models.dtos.report.scoring import PenaltyData, ScoreItem, ScoreSummaryData, ScoringReportData
from backend_v2.models.dtos.report.specialists import (
    AnalystReportData,
    CausalAnalysisData,
    FalsifierData,
    JudgeReportData,
    LogicianData,
    LogicianReportData,
    OverseerData,
    OverseerReportData,
    PanelReportData,
    PerformativityAnalysis,
    PerformativityReportData,
    ProfilerReportData,
    XaiReportData,
)
from backend_v2.models.dtos.report.validation import ValidationReportData, ValidationWarningData
from backend_v2.models.view.sdui import ReferenceItem


class PromptContextDTO(BaseDTO):
    """Execution prompt context containing exact compilation boundaries."""

    model_config = ConfigDict(strict=True, frozen=True, extra="forbid")

    static_messages: Annotated[
        list[dict[str, Any]],
        Field(description="Globally identical content across all chunks (base system prompt + source document)."),
    ] = Field(default_factory=list)
    dynamic_messages: Annotated[
        list[dict[str, Any]],
        Field(description="Per-chunk/per-retry content (rubrics, atoms, execution params, healing errors)."),
    ] = Field(default_factory=list)
    metadata: Annotated[
        dict[str, Any], Field(description="Arbitrary execution metadata (e.g., token proxy scores).")
    ] = Field(default_factory=dict)


class GlobalContextVarsDTO(BaseDTO):
    """Schema for parsing agent outputs dynamically from global_context_vars."""

    model_config = ConfigDict(strict=True, frozen=True, extra="forbid")

    step_xai: XaiReportData | None = None
    step_judge: JudgeReportData | None = None
    step_overseer: OverseerReportData | None = None
    step_logician: LogicianReportData | None = None
    step_detector: PerformativityReportData | None = None
    step_linguistics: LinguisticsResultDTO | None = None
    step_analyst: AnalystReportData | None = None
    step_panel: PanelReportData | None = None
    step_profiler: ProfilerReportData | None = None
    step_scoreengine1: ScoringReportData | None = None
    step_validation: ValidationReportData | None = None
    step_archivist: ArchivistOutputDTO | list[ArchivistOutputDTO] | None = None
    step_coach: CoachingPlanDTO | None = None
    bibliography_result: BibliographyResult | list[BibliographyResult] | None = None
    search_result: SearchResult | list[SearchResult] | None = None


class AuditQuestionItem(BaseDTO):
    """Key diagnostic question generated by structural nodes."""

    model_config = ConfigDict(strict=True, frozen=True, extra="forbid")

    question: str
    status: str


class ReportContextDTO(BaseDTO):
    """Strictly typed schema for the aggregated report context injected into state."""

    model_config = ConfigDict(strict=True, frozen=True, extra="forbid")

    inputs: MatrixObservabilityDTO
    generated_at: str
    timestamp: str
    summary: str
    critical_findings: Annotated[list[str], Field(default_factory=list)]
    pre_mortem_signals: Annotated[list[str], Field(default_factory=list)]
    ethical_issues: Annotated[list[str], Field(default_factory=list)]
    audit_questions: Annotated[list[AuditQuestionItem], Field(default_factory=list)]
    scores: Annotated[dict[str, ScoreItem], Field(default_factory=dict)]
    average_score: float = 0.0
    hitl_required: bool = False
    uncertainty: Annotated[dict[str, str], Field(default_factory=dict)]
    bibliography: Annotated[list[dict[str, Any]], Field(default_factory=list)]
    references: Annotated[list[ReferenceItem], Field(default_factory=list)]
    output_extensions: Annotated[list[Any], Field(default_factory=list)]

    # Specialist Data (passthrough for templates)
    logician_data: LogicianData | None = None
    overseer_data: OverseerData | None = None
    falsifier_data: FalsifierData | None = None
    causal_analysis: CausalAnalysisData | None = None
    performativity_analysis: PerformativityAnalysis | None = None

    # Enrichment
    word_count: int | None = None
    input_control_ratio: float | None = None
    google_search_results: Annotated[list[Any], Field(default_factory=list)]
    knowledge_items: Annotated[list[Any], Field(default_factory=list)]

    archivist_precedents: ArchivistOutputDTO | list[ArchivistOutputDTO] | None = None
    penalties_applied: list[PenaltyData] | None = None
    score_summary: ScoreSummaryData | None = None
    structural_warnings: list[ValidationWarningData] | None = None
    coaching_plan: CoachingPlanDTO | None = None
