import pytest

from backend_v2.exceptions import AppException, ErrorCodes
from backend_v2.llm.ingress_pipeline import UniversalIngress


def test_parse_llm_output_success():
    """Test successful parsing of raw JSON."""
    raw_text = """
    {
      "test_key": "test_value"
    }
    """
    result = UniversalIngress.parse_llm_output(raw_text)
    assert result["test_key"] == "test_value"


def test_parse_llm_output_markdown_stripping():
    """Test parsing strips markdown fences correctly."""
    raw_text = """```json
{
  "test_key": "test_value"
}
```"""
    result = UniversalIngress.parse_llm_output(raw_text)
    assert result["test_key"] == "test_value"


def test_parse_llm_output_self_healing_trailing_comma():
    """Test self-healing fixes a trailing comma."""
    raw_text = """
    {
      "invalid_key": "value",
    }
    """
    result = UniversalIngress.parse_llm_output(raw_text)
    assert result["invalid_key"] == "value"


def test_parse_llm_output_self_healing_unescaped_quotes():
    """Test self-healing fixes unescaped double quotes inside string."""
    raw_text = """
    {
      "reasoning": "The user said "hello" to me."
    }
    """
    result = UniversalIngress.parse_llm_output(raw_text)
    assert result["reasoning"] == 'The user said "hello" to me.'


def test_parse_llm_output_unrepairable():
    """Test parsing still raises AppException if the text is completely non-JSON."""
    raw_text = "This is just raw text without any JSON structure."
    with pytest.raises(AppException) as exc:
        UniversalIngress.parse_llm_output(raw_text)

    assert exc.value.details["error_code"] == ErrorCodes.PARSING_FAILED.value
    assert "Malformed JSON in LLM output. Self-healing failed." in exc.value.message


def test_parse_llm_output_list_wrapper():
    """Test parsing of a top-level list wraps it in a dict."""
    raw_text = """
    [
      {"item": 1},
      {"item": 2}
    ]
    """
    result = UniversalIngress.parse_llm_output(raw_text)
    assert "data" in result
    assert len(result["data"]) == 2
    assert result["data"][0]["item"] == 1


def test_clean_dict_against_model_alias_stripping_bug():
    """Reproduces the bug where clean_dict_against_model strips fields generated by the LLM
    if they match the Pydantic alias (e.g. eval_1) instead of the underlying field name.
    """
    from pydantic import BaseModel, ConfigDict, Field

    class AliasModel(BaseModel):
        model_config = ConfigDict(populate_by_name=True)
        my_field: str = Field(..., alias="eval_1")
        other_field: str

    # The LLM generates the JSON using the 'eval_1' alias, as instructed by the JSON Schema
    raw_llm_payload = {"eval_1": "Target Data", "other_field": "Normal Data"}

    # ACL cleans the dict
    cleaned = UniversalIngress.clean_dict_against_model(raw_llm_payload, AliasModel)

    # We expect 'eval_1' to still be present (or remapped to 'my_field') so it can pass validation
    assert "eval_1" in cleaned or "my_field" in cleaned, "The aliased field was incorrectly stripped!"

    # And validation should succeed
    validated = AliasModel.model_validate(cleaned)
    assert validated.my_field == "Target Data"


def test_clean_dict_against_model_discriminated_unions_and_nested_structures():
    """Verify UniversalIngress handles discriminated unions, heuristics, and nested types."""
    from typing import Annotated, Literal

    from pydantic import BaseModel, ConfigDict, Field

    class CardA(BaseModel):
        model_config = ConfigDict(strict=True, extra="forbid")
        block_type: Literal["card_a"] = "card_a"
        severity: str
        text: str

    class CardB(BaseModel):
        model_config = ConfigDict(strict=True, extra="forbid")
        block_type: Literal["card_b"] = "card_b"
        items: list[str]

    class CardC(BaseModel):
        model_config = ConfigDict(strict=True, extra="forbid")
        block_type: Literal["card_c"] = "card_c"
        quote: str

    class CardD(BaseModel):
        model_config = ConfigDict(strict=True, extra="forbid")
        block_type: Literal["card_d"] = "card_d"
        message: str

    class CardE(BaseModel):
        model_config = ConfigDict(strict=True, extra="forbid")
        block_type: Literal["card_e"] = "card_e"
        text: str

    PolyCard = Annotated[CardA | CardB | CardC | CardD | CardE, Field(discriminator="block_type")]

    class NestedChild(BaseModel):
        model_config = ConfigDict(strict=True, extra="forbid")
        name: str

    class ContainerModel(BaseModel):
        model_config = ConfigDict(strict=True, extra="forbid")
        single_card: PolyCard
        cards: list[PolyCard]
        single_nested: NestedChild
        nested_list: list[NestedChild]
        strict_string: str

    raw_payload = {
        "single_card": {"message": "warning message"},
        "cards": [
            {"severity": "high", "text": "alert text"},
            {"items": ["item 1", "item 2"]},
            {"quote": "some quote"},
            {"text": "paragraph text"},
            {"block_type": "card_a", "severity": "low", "text": "explicit"},
        ],
        "single_nested": {"name": "child", "hallucinated_nested": 123},
        "nested_list": [{"name": "item 1", "extra": True}],
        "strict_string": None,
        "hallucinated_root_key": "drop me",
    }

    cleaned = UniversalIngress.clean_dict_against_model(raw_payload, ContainerModel)
    assert "hallucinated_root_key" not in cleaned
    assert cleaned["strict_string"] == ""
    assert cleaned["single_nested"] == {"name": "child"}
    assert cleaned["nested_list"] == [{"name": "item 1"}]

    validated = ContainerModel.model_validate(cleaned)
    assert isinstance(validated.single_card, CardD)
    assert len(validated.cards) == 5
    assert isinstance(validated.cards[0], CardA)
    assert isinstance(validated.cards[1], CardB)
    assert isinstance(validated.cards[2], CardC)
    assert isinstance(validated.cards[3], CardE)
    assert isinstance(validated.cards[4], CardA)


def test_clean_dict_non_dict_passthrough():
    """Verify non-dict data is returned as-is."""
    from pydantic import BaseModel

    class Dummy(BaseModel):
        val: int

    assert UniversalIngress.clean_dict_against_model("not a dict", Dummy) == "not a dict"
    assert UniversalIngress.clean_dict_against_model(123, Dummy) == 123


def test_clean_dict_against_model_explicit_tag_literal_matching():
    """Verify explicit tag matching with Literal type annotations and unknown tag fallback."""
    from typing import Annotated, Literal

    from pydantic import BaseModel, ConfigDict, Field

    class OptionX(BaseModel):
        model_config = ConfigDict(strict=True, extra="forbid")
        block_type: Literal["opt_x"]
        data: str

    class OptionY(BaseModel):
        model_config = ConfigDict(strict=True, extra="forbid")
        block_type: Literal["opt_y"]
        score: int

    UnionOpt = Annotated[OptionX | OptionY, Field(discriminator="block_type")]

    class WrapModel(BaseModel):
        item: UnionOpt

    # Matching via Literal annotation
    res1 = UniversalIngress.clean_dict_against_model({"item": {"block_type": "opt_x", "data": "val"}}, WrapModel)
    assert res1["item"]["block_type"] == "opt_x"

    # Unknown tag fallback matches first candidate
    res2 = UniversalIngress.clean_dict_against_model({"item": {"block_type": "unknown_opt", "data": "val"}}, WrapModel)
    assert "data" in res2["item"]


def test_clean_dict_against_model_overlap_inference_and_unmatched():
    """Verify key overlap inference when signature heuristics do not match."""
    from typing import Annotated, Literal

    from pydantic import BaseModel, ConfigDict, Field

    class CustomBlock(BaseModel):
        model_config = ConfigDict(strict=True, extra="forbid")
        block_type: Literal["custom_b"] = "custom_b"
        alpha: str
        beta: int

    class AnotherBlock(BaseModel):
        model_config = ConfigDict(strict=True, extra="forbid")
        block_type: Literal["another_b"] = "another_b"
        gamma: float

    CustomUnion = Annotated[CustomBlock | AnotherBlock, Field(discriminator="block_type")]

    class TopModel(BaseModel):
        block: CustomUnion

    # Overlap heuristic matches CustomBlock due to alpha and beta
    res = UniversalIngress.clean_dict_against_model({"block": {"alpha": "a", "beta": 1}}, TopModel)
    assert res["block"]["block_type"] == "custom_b"
    assert res["block"]["alpha"] == "a"

    # None input handling
    assert UniversalIngress._clean_value_against_annotation(None, None) is None
    assert UniversalIngress._clean_value_against_annotation(None, int) is None
    assert UniversalIngress._clean_value_against_annotation(None, str) == ""


def test_parse_llm_output_generic_markdown_code_fence():
    """Test parsing strips generic markdown code fences without json tag."""
    raw_text = """```
{
  "key": "generic_fence"
}
```"""
    result = UniversalIngress.parse_llm_output(raw_text)
    assert result["key"] == "generic_fence"


def test_parse_llm_output_repair_unexpected_type_raises_app_exception(monkeypatch: pytest.MonkeyPatch):
    """Negative test: verify AppException is raised if repair_json returns non-dict/non-list."""
    monkeypatch.setattr("backend_v2.llm.ingress_pipeline.repair_json", lambda *a, **kw: "invalid_string_output")
    with pytest.raises(AppException) as exc:
        UniversalIngress.parse_llm_output("{broken json without end")

    assert exc.value.details["error_code"] == ErrorCodes.PARSING_FAILED.value
    assert "Self-healing failed" in exc.value.message


def test_extract_discriminator_info_edge_cases():
    """Verify various discriminator annotations and edge cases."""
    from typing import Annotated, Union
    from pydantic import BaseModel, Discriminator, Field

    class ModA(BaseModel):
        tag: str

    class ModB(BaseModel):
        tag: str

    # None annotation
    assert UniversalIngress._extract_discriminator_info(None) == (None, [])

    # Direct Discriminator meta
    ann1 = Annotated[Union[ModA, ModB], Discriminator("tag")]
    disc1, models1 = UniversalIngress._extract_discriminator_info(ann1)
    assert disc1 == "tag"
    assert len(models1) == 2

    # Field with Discriminator object
    ann2 = Annotated[Union[ModA, ModB], Field(discriminator=Discriminator("tag"))]
    disc2, models2 = UniversalIngress._extract_discriminator_info(ann2)
    assert disc2 == "tag"
    assert len(models2) == 2

    # Annotated inside union
    ann3 = Annotated[Union[Annotated[ModA, "meta"], ModB], Field(discriminator="tag")]
    disc3, models3 = UniversalIngress._extract_discriminator_info(ann3)
    assert disc3 == "tag"
    assert len(models3) == 2

    # Target union that is single BaseModel (not a Union)
    ann4 = Annotated[ModA, Field(discriminator="tag")]
    disc4, models4 = UniversalIngress._extract_discriminator_info(ann4)
    assert disc4 == "tag"
    assert len(models4) == 1


def test_clean_dict_against_model_advanced_branches():
    """Verify clean_dict branches for single candidate, missing matches, and discriminator preservation."""
    from typing import Annotated
    from pydantic import BaseModel, ConfigDict, Discriminator, Field

    class Inner(BaseModel):
        model_config = ConfigDict(strict=True, extra="forbid")
        val: str

    class Outer(BaseModel):
        model_config = ConfigDict(strict=True, extra="forbid")
        nested: Inner
        items: list[Inner]
        not_a_list_target: int

    # Passing single candidate model inside list and nested dict
    raw = {
        "nested": {"val": "hello", "extra_strip": 123},
        "items": [{"val": "one", "drop_me": 456}],
        "not_a_list_target": 42,
    }
    cleaned = UniversalIngress.clean_dict_against_model(raw, Outer)
    assert cleaned["nested"] == {"val": "hello"}
    assert cleaned["items"] == [{"val": "one"}]

    # Val is list but target is not list
    cleaned_not_list = UniversalIngress._clean_value_against_annotation([1, 2], int)
    assert cleaned_not_list == [1, 2]

    # Nested with Discriminator object passed to _clean_value_against_annotation
    from typing import Literal

    class DiscModelA(BaseModel):
        tag: Literal["a"] = "a"
        x: int

    class DiscModelB(BaseModel):
        tag: Literal["b"] = "b"
        y: int

    class ContainerDisc(BaseModel):
        item: Annotated[DiscModelA | DiscModelB, Field(discriminator="tag")]

    res_disc = UniversalIngress.clean_dict_against_model(
        {"item": {"tag": "a", "x": 10}},
        ContainerDisc,
    )
    assert res_disc["item"]["x"] == 10

    # Discriminator field present in item but no matching models found
    class UnmatchedTagModel(BaseModel):
        tag: str = "fixed"
        val: int

    assert (
        UniversalIngress._infer_and_heal_discriminator(
            {"tag": "completely_unmatched_tag"},
            "tag",
            [UnmatchedTagModel],
        )
        == UnmatchedTagModel
    )

    # Heuristic complete failure returns None
    assert (
        UniversalIngress._infer_and_heal_discriminator(
            {"unrelated_key": 999},
            "tag",
            [],
        )
        is None
    )

