import 'package:client_app/features/studio/data/studio_repository.dart';
import 'package:client_app/features/studio/domain/models/component_def.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'available_matrices_controller.g.dart';

/// **Available Matrices Controller**
///
/// Manages the list of available Evaluation Matrices using the modern
/// "Optimistic Update + Silent Invalidation" pattern (Riverpod 3.0 Best Practice).
@riverpod
class AvailableMatricesController extends _$AvailableMatricesController {
  
  @override
  FutureOr<List<MatrixDef>> build() async {
    return ref.watch(studioRepositoryProvider).getMatrices();
  }

  /// **Create Matrix**
  Future<void> createMatrix(String name, String description) async {
    final previousState = state;
    // 1. Optimistic Update (Append)
    final newMatrix = MatrixDef(
      id: 'new_${DateTime.now().millisecondsSinceEpoch}',
      name: name,
      description: description,
      scale: {'min': 1, 'max': 5},
      criteria: [],
    );
    
    final currentList = state.value ?? [];
    state = AsyncData([...currentList, newMatrix]);

    try {
      // 3. API Call
      await ref.read(studioRepositoryProvider).saveMatrix(newMatrix);

      // 4. Silent Invalidation (Sync with Server)
      // This will fetch the real ID generated by backend/DB
      ref.invalidateSelf();
    } catch (e, st) {
      // 5. Rollback
      state = previousState; // Assign directly, do not wrap in AsyncData
      state = AsyncError(e, st); // Also expose error to UI? Or just rollback + rethrow?
      // Standard: Rollback state to data, then rethrow for Snackbar.
      state = previousState;
      rethrow;
    }
  }

  /// **Delete Matrix**
  Future<void> deleteMatrix(String id) async {
    final previousState = state;
    
    // 1. Optimistic Update
    final currentList = state.value ?? [];
    state = AsyncData(currentList.where((m) => m.id != id).toList());

    try {
      // 2. API Call
      await ref.read(studioRepositoryProvider).deleteMatrix(id);

      // 3. Silent Sync (Confirmation)
      ref.invalidateSelf();
    } catch (e) {
      // 4. Rollback
      state = previousState;
      rethrow;
    }
  }
}
