import 'package:client_app/features/studio/data/studio_repository.dart';
import 'package:client_app/features/studio/domain/models/component_def.dart';
import 'package:client_app/core/error/app_error.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'ontology_controller.g.dart';

@riverpod
class OntologyController extends _$OntologyController {
  @override
  FutureOr<List<OntologyDimension>> build() async {
    return ref.watch(studioRepositoryProvider).fetchOntology();
  }

  Future<void> addDimension(OntologyDimension dimension) async {
    final previousState = state;
    if (previousState.value == null) return;

    // Optimistic Update
    state = AsyncValue.data([...previousState.value!, dimension]);

    try {
      await ref.read(studioRepositoryProvider).saveDimension(dimension);
      // No need to refresh entire list if save is just persistence,
      // but if ID is generated by backend, we might need to.
      // However, typical pattern for optimistic UI is assumption of success.
      // If backend returns new data, we should use that.
      // StudioRepository.saveDimension returns void.
      // We assume ID is pre-generated or client-side managed for now in this context?
      // But standard is: "new_" prefix.
      if (dimension.id.startsWith('new_')) {
        // If it's new, we might want to refresh to get the standard ID if backend changes it.
        // But for now, let's keep it simple.
        ref.invalidateSelf();
      }
    } catch (e, st) {
      state = previousState; // Revert
      state = AsyncValue.error(e, st);
    }
  }

  Future<void> updateDimension(OntologyDimension dimension) async {
    final previousState = state;
    if (previousState.value == null) return;

    // Optimistic Update
    final updatedList =
        previousState.value!.map((e) {
          return e.id == dimension.id ? dimension : e;
        }).toList();
    state = AsyncValue.data(updatedList);

    try {
      await ref
          .read(studioRepositoryProvider)
          .saveDimension(dimension, isUpdate: true);
      // Success, state is already updated optimally.
    } catch (e, st) {
      state = previousState; // Revert
      state = AsyncValue.error(e, st);
    }
  }

  Future<void> removeDimension(String id) async {
    final previousState = state;
    if (previousState.value == null) return;

    // Optimistic Update
    state = AsyncValue.data(
      previousState.value!.where((e) => e.id != id).toList(),
    );

    try {
      await ref.read(studioRepositoryProvider).deleteDimension(id);
    } catch (e) {
      // Revert state
      state = previousState;
      // Rethrow so UI can show SnackBar
      if (e is AppError) {
        rethrow;
      }
      // If unknown, we still want to rethrow or wrap?
      // For now, let's rethrow to let UI handle "Unknown Error".
      // But we must wrap in AppError if not already.
      // Actually, if we just set state=error, ListView turns red.
      // We want List to stay visible (reverted) + SnackBar.
      // So rethrow is key.
      throw e is AppError ? e : AppError.server(e.toString());
    }
  }
}
