"""End-to-End Golden Master Test for Epic 93 SDUI Output Rendering Unification."""

from typing import Any

import pytest

from backend_v2.models.dtos.report.root import ReportDataDto
from backend_v2.models.view.sdui import ReportView

# The following import will fail intentionally in Phase 0 (Red-Green-Refactor)
from backend_v2.services.sdui_mapper_service import SduiMapperService


@pytest.mark.asyncio
async def test_epic_93_e2e_golden_master() -> None:
    """Verifies the E2E data flow:
    seed_data.json -> DAG (Epic 92) -> ResultProjector -> ReportDataDto (Epic 91.5) -> SduiMapper (Epic 93) -> SduiComponent tree.
    """
    # 1. We will use a mock ReportDataDto that mimics the output of Epic 91.5.
    # In a full DAG test, this would be generated by ResultProjector.
    # For now, we simulate a minimal valid ReportDataDto to pass into SduiMapperService.
    # Since we are testing SduiMapperService here, let's create a minimal payload.

    mock_dto_payload: dict[str, Any] = {
        "execution_id": "exe_123",
        "workflow_id": "wor_456",
        "global_metrics": {"total_atoms": 1, "evaluated": 1, "short_circuited_na": 0, "duration_ms": 100},
        "global_synthesis": None,
        "results": [],
        "hydrated_references": {},
    }

    dto = ReportDataDto.model_validate(mock_dto_payload)

    # 2. Map the DTO to SDUI view model using the SduiMapperService
    mapper = SduiMapperService()
    view = mapper.map_report(dto)

    # 3. Assertions
    assert isinstance(view, ReportView)
    assert view.view_id == "exe_123"
