"""Database Protocol Interfaces (ISP Refactoring).

These interfaces split the monolithic AbstractWorkflowRepository into
cohesive, role-based protocols according to the Interface Segregation Principle.
All methods return strictly typed Pydantic Domain models (ConfigDict(frozen=True)).
"""

from __future__ import annotations

from typing import Protocol

from backend_v2.models.auth import (
    Organization,
    OrganizationCreate,
    OrganizationUpdateDTO,
    User,
    UserCreate,
    UserUpdate,
)
from backend_v2.models.domain.base import (
    AuditLogCreateDTO,
    AuditLogEntry,
    DetailedUsageDTO,
    UsageAggregateDTO,
    UsageAggregateUpdateDTO,
    UsageRecord,
)
from backend_v2.models.domain.knowledge import (
    BannedPhrase,
    Claim,
    ClaimCreateDTO,
    Concept,
    ConceptCreateDTO,
    PromptTemplateDTO,
    Reference,
    ReferenceCreateDTO,
)
from backend_v2.models.domain.output_profile import OutputProfile
from backend_v2.models.domain.prompt_blocks import PromptBlock
from backend_v2.models.dtos.studio import (
    StepCreateDTO,
    StepUpdateDTO,
    WorkflowCreateDTO,
    WorkflowUpdateDTO,
)
from backend_v2.models.dtos.system import (
    AnySystemConfig,
    SystemConfigCreateDTO,
    SystemConfigUpdateDTO,
    SystemSettingsDTO,
)
from backend_v2.models.dtos.trace import (
    ExecutionCreateDTO,
    ExecutionUpdateDTO,
)
from backend_v2.models.state import TraceEvent
from backend_v2.models.v2_core import (
    ExecutionRecord,
    Role,
    Step,
    SystemConfigMCPGateways,
    SystemConfigModelRegistry,
    SystemConfigPerformativeLexicons,
    Workflow,
)


class IExecutionRepository(Protocol):
    """Protocol for Execution persistence operations."""

    async def get_execution(self, execution_id: str, hydrate: bool = True) -> ExecutionRecord | None: ...
    async def get_execution_status(self, execution_id: str) -> str | None: ...
    async def create_execution(self, execution_data: ExecutionCreateDTO) -> str: ...
    async def update_execution(self, execution_id: str, updates: ExecutionUpdateDTO) -> bool: ...
    async def append_trace_event(self, execution_id: str, event_data: TraceEvent) -> bool: ...
    async def delete_execution(self, execution_id: str) -> bool: ...
    async def get_all_executions(
        self, organization_id: str | None = None, user_id: str | None = None
    ) -> list[ExecutionRecord]: ...
    async def get_recent_completed_executions(self, limit: int = 5) -> list[ExecutionRecord]: ...
    async def count_executions_by_matrix(self, matrix_id: str) -> int: ...


class IWorkflowRepository(Protocol):
    """Protocol for Workflow and Step persistence operations."""

    async def get_workflow_definition(self, workflow_id: str) -> Workflow | None: ...
    async def get_workflow(self, workflow_id: str) -> Workflow | None: ...
    async def get_all_workflows(
        self, organization_id: str | None = None, role: str | None = None
    ) -> list[Workflow]: ...
    async def get_workflow_by_id(self, workflow_id: str) -> Workflow | None: ...
    async def create_workflow(self, workflow_data: WorkflowCreateDTO) -> str: ...
    async def update_workflow(self, workflow_id: str, updates: WorkflowUpdateDTO) -> str: ...
    async def update_workflow_definition(self, workflow_id: str, definition_data: WorkflowUpdateDTO) -> str: ...
    async def delete_workflow(self, workflow_id: str) -> bool: ...
    async def count_workflows(self) -> int: ...
    async def get_all_steps(self) -> list[Step]: ...
    async def get_step_by_id(self, step_id: str) -> Step | None: ...
    async def get_step(self, step_id: str) -> Step | None: ...
    async def create_step(self, step_data: StepCreateDTO) -> str: ...
    async def update_step(self, step_id: str, updates: StepUpdateDTO) -> str: ...
    async def delete_step(self, step_id: str, force_delete: bool = False) -> bool: ...
    async def save_workflow(self, workflow: Workflow) -> str: ...
    async def save_step(self, step: Step) -> str: ...


class IIdentityRepository(Protocol):
    """Protocol for Organization and User identity operations."""

    async def list_organizations(self) -> list[Organization]: ...
    async def get_organization(self, org_id: str) -> Organization | None: ...
    async def get_organization_model(self, org_id: str) -> Organization | None: ...
    async def create_organization(self, org_data: OrganizationCreate | Organization) -> str: ...
    async def update_organization(self, org_id: str, updates: OrganizationUpdateDTO) -> bool: ...
    async def delete_organization(self, org_id: str) -> bool: ...
    async def list_users(self, org_id: str | None = None) -> list[User]: ...
    async def get_user(self, user_id: str) -> User | None: ...
    async def get_user_by_email(self, email: str) -> User | None: ...
    async def create_user(self, user_data: UserCreate | User) -> str: ...
    async def update_user(self, user_id: str, updates: UserUpdate) -> bool: ...
    async def delete_user(self, user_id: str) -> bool: ...
    async def delete_org_data(self, org_id: str) -> None: ...
    async def get_org_usage_total(self, org_id: str, since: str | None = None) -> float: ...


class IComponentRepository(Protocol):
    """Protocol for generic component persistence operations."""

    async def get_all_components(
        self, type: str | None = None, exclude_types: list[str] | None = None
    ) -> list[PromptBlock]: ...
    async def get_component_by_id(self, component_id: str) -> PromptBlock | None: ...
    async def get_component_by_name(self, name: str) -> PromptBlock | None: ...
    async def update_component_metadata(self, component_id: str, module: str, component_class: str) -> bool: ...
    async def register_component(self, component_data: PromptBlock) -> str: ...
    async def create_component(self, component_data: PromptBlock) -> str: ...
    async def update_component(self, component_id: str, updates: PromptBlock) -> str: ...
    async def delete_component(self, component_id: str) -> bool: ...
    async def get_components_using_dimension(self, dimension_id: str) -> list[str]: ...


class IPromptBlockRepository(Protocol):
    """Protocol for Prompt Block persistence operations."""

    async def get_prompt_block_by_id(self, block_id: str) -> PromptBlock | None: ...
    async def get_prompt_block(self, block_id: str) -> PromptBlock | None: ...
    async def get_all_prompt_blocks(self) -> list[PromptBlock]: ...
    async def get_prompt_blocks_by_ids(
        self,
        block_ids: list[str],
        strict: bool = True,
    ) -> list[PromptBlock]: ...
    async def get_all_prompt_blocks_models(self) -> list[PromptBlock]: ...
    async def create_prompt_block(self, block_data: PromptBlock) -> str: ...
    async def update_prompt_block(self, block_id: str, updates: PromptBlock) -> bool: ...
    async def delete_prompt_block(self, block_id: str, force_delete: bool = False) -> bool: ...


class IAgentRepository(Protocol):
    """Protocol for Agent persistence operations."""

    async def get_agent_by_id(self, agent_id: str) -> PromptBlock | None: ...
    async def get_all_agents(self) -> list[PromptBlock]: ...
    async def create_agent(self, agent_data: PromptBlock) -> str: ...
    async def update_agent(self, agent_id: str, updates: PromptBlock) -> bool: ...
    async def delete_agent(self, agent_id: str) -> bool: ...


class ITaskBlueprintRepository(Protocol):
    """Protocol for Task Blueprint / Step persistence operations."""

    async def get_task_blueprint_by_id(self, blueprint_id: str) -> Step | None: ...
    async def get_all_task_blueprints(self) -> list[Step]: ...
    async def create_task_blueprint(self, blueprint_data: Step) -> str: ...
    async def update_task_blueprint(self, blueprint_id: str, updates: StepUpdateDTO) -> bool: ...
    async def delete_task_blueprint(self, blueprint_id: str) -> bool: ...


class IOutputProfileRepository(Protocol):
    """Protocol for Output Profile persistence operations."""

    async def get_all_output_profiles(self) -> list[OutputProfile]: ...
    async def get_all_output_profiles_models(self) -> list[OutputProfile]: ...
    async def get_output_profile_by_id(self, profile_id: str) -> OutputProfile | None: ...
    async def create_output_profile(self, profile_data: OutputProfile) -> str: ...
    async def update_output_profile(self, profile_id: str, updates: OutputProfile) -> bool: ...
    async def delete_output_profile(self, profile_id: str) -> bool: ...


class IKnowledgeRepository(Protocol):
    """Protocol for Knowledge Base, Banned Phrases, and Prompt Templates."""

    async def get_banned_phrases(self) -> list[BannedPhrase]: ...
    async def add_banned_phrase(self, phrase: str, language: str = "en") -> None: ...
    async def delete_banned_phrase(self, phrase: str) -> bool: ...
    async def get_prompt_template(self, template_id: str) -> PromptTemplateDTO | None: ...
    async def get_concepts(self) -> list[Concept]: ...
    async def get_references(self) -> list[Reference]: ...
    async def get_claims(self) -> list[Claim]: ...
    async def add_concept(self, item: ConceptCreateDTO) -> str: ...
    async def add_reference(self, item: ReferenceCreateDTO) -> str: ...
    async def add_claim(self, item: ClaimCreateDTO) -> str: ...
    async def clear_knowledge_base(self) -> None: ...


class ISystemRepository(Protocol):
    """Protocol for System configuration, MCP gateways, and Model registries."""

    async def get_model_registry(self) -> SystemConfigModelRegistry: ...
    async def update_model_registry(self, registry_data: SystemConfigModelRegistry) -> bool: ...
    async def get_mcp_gateways(self, id: str | None = None) -> SystemConfigMCPGateways: ...
    async def update_mcp_gateways(self, gateways_data: SystemConfigMCPGateways) -> bool: ...
    async def get_system_settings(self) -> SystemSettingsDTO | None: ...
    async def update_system_settings(self, updates: SystemConfigUpdateDTO) -> bool: ...
    async def get_system_config(self, config_id: str) -> AnySystemConfig | None: ...
    async def create_system_config(self, config_data: SystemConfigCreateDTO) -> str: ...
    async def update_performative_lexicons(self, lexicons_data: SystemConfigPerformativeLexicons) -> bool: ...


class IAuditRepository(Protocol):
    """Protocol for Audit Logs and Usage tracking."""

    async def log_audit_event(self, event_data: AuditLogCreateDTO) -> None: ...
    async def get_audit_logs(
        self,
        organization_id: str | None = None,
        actor_id: str | None = None,
        action: str | None = None,
        limit: int = 100,
    ) -> list[AuditLogEntry]: ...
    async def log_usage(self, record: UsageRecord) -> None: ...
    async def get_usage_records(
        self, scope: str, entity_id: str | None = None, since: str | None = None
    ) -> list[UsageRecord]: ...
    async def get_usage_aggregate(self, scope: str, entity_id: str | None, period: str) -> UsageAggregateDTO | None: ...
    async def upsert_usage_aggregate(
        self, scope: str, entity_id: str | None, period: str, update_data: UsageAggregateUpdateDTO
    ) -> None: ...
    async def get_detailed_usage(
        self, scope: str, target_id: str | None = None, since: str | None = None
    ) -> DetailedUsageDTO: ...


class IMatrixRepository(Protocol):
    """Protocol for Evaluation Matrix components."""

    async def get_all_matrices(self) -> list[PromptBlock]: ...
    async def get_matrix_by_id(self, matrix_id: str) -> PromptBlock | None: ...
    async def create_matrix(self, matrix_data: PromptBlock) -> str: ...
    async def update_matrix(self, matrix_id: str, updates: PromptBlock) -> str: ...
    async def delete_matrix(self, matrix_id: str) -> bool: ...
    async def get_matrices_using_dimension(self, dimension_id: str) -> list[str]: ...


class IRoleRepository(Protocol):
    """Protocol for Role components."""

    async def get_all_roles(self) -> list[Role]: ...
    async def get_role_by_id(self, role_id: str) -> Role | None: ...
    async def create_role(self, role_data: Role) -> str: ...
    async def update_role(self, role_id: str, updates: Role) -> str: ...
    async def delete_role(self, role_id: str) -> bool: ...


class IExecutionPersonaRepository(Protocol):
    """Protocol for Execution Persona components."""

    async def get_all_execution_personas(self) -> list[PromptBlock]: ...
    async def get_execution_persona_by_id(self, persona_id: str) -> PromptBlock | None: ...
    async def create_execution_persona(self, persona_data: PromptBlock) -> str: ...
    async def update_execution_persona(self, persona_id: str, updates: PromptBlock) -> str: ...
    async def delete_execution_persona(self, persona_id: str) -> bool: ...


class IExtractionProtocolRepository(Protocol):
    """Protocol for Extraction Protocol components."""

    async def get_all_extraction_protocols(self) -> list[PromptBlock]: ...
    async def get_extraction_protocol_by_id(self, protocol_id: str) -> PromptBlock | None: ...
    async def create_extraction_protocol(self, protocol_data: PromptBlock) -> str: ...
    async def update_extraction_protocol(self, protocol_id: str, updates: PromptBlock) -> str: ...
    async def delete_extraction_protocol(self, protocol_id: str) -> bool: ...


class IUnifiedWorkflowRepository(
    IWorkflowRepository,
    IExecutionRepository,
    IComponentRepository,
    IMatrixRepository,
    IRoleRepository,
    IExecutionPersonaRepository,
    IExtractionProtocolRepository,
    IPromptBlockRepository,
    IAgentRepository,
    ITaskBlueprintRepository,
    IOutputProfileRepository,
    IIdentityRepository,
    IAuditRepository,
    ISystemRepository,
    IKnowledgeRepository,
    Protocol,
):
    """Combined protocol facade for all repository operations."""

    ...
