import 'package:test/test.dart';
import 'package:backend_api/backend_api.dart';

// tests for TokenUsage
void main() {
  final TokenUsage? instance = /* TokenUsage(...) */ null;
  // TODO add properties to the entity

  group(TokenUsage, () {
    // Tokens used in the prompt.
    // int promptTokens (default value: 0)
    test('to test the property `promptTokens`', () async {
      // TODO
    });

    // Tokens generated by the model.
    // int completionTokens (default value: 0)
    test('to test the property `completionTokens`', () async {
      // TODO
    });

    // Total tokens used.
    // int totalTokens (default value: 0)
    test('to test the property `totalTokens`', () async {
      // TODO
    });

    // Estimated cost in USD.
    // num costUsd (default value: 0.0)
    test('to test the property `costUsd`', () async {
      // TODO
    });
  });
}
