"""DAG Data Transfer Objects.

This module defines the strictly typed Pydantic V2 models for the Enriched Atom Graph
architecture, including the causal edges, extracted atoms, linked graphs, and the
execution state.

Models enforce `ConfigDict(extra="forbid", strict=True, frozen=True)` to guarantee
architectural Single Source of Truth and Fail-Fast operations.
"""

from pydantic import BaseModel, ConfigDict, Field

from backend_v2.models.enums import ExecutionStatus


class CausalEdge(BaseModel):
    """Represents a directional causal dependency between two atoms in the DAG.

    Attributes:
        edge_reasoning: Chain-of-thought reasoning explaining the causal relationship.
        tda_id: The identifier of the parent atom.
        source_id: The identifier of the spatial anchor (e.g., chunk ID).
        expected_status: The expected status of the parent for this edge to be satisfied.
    """

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    edge_reasoning: str = Field(
        description="Chain-of-thought: LLM reasoning about why this causal relationship exists (Reason-then-Format)."
    )
    tda_id: str = Field(description="The Opaque Stripe ID of the parent atom.")
    source_id: str = Field(description="The spatial anchor (Chunk ID) where this edge was identified.")
    expected_status: ExecutionStatus = Field(
        default=ExecutionStatus.PASSED,
        description="Allows for negative conditions. The dependency is met only if the parent reaches this status.",
    )


class ExtractedAtom(BaseModel):
    """Represents a single extracted claim with resolved anaphora and exact evidence.

    Attributes:
        reasoning: Chain-of-thought reasoning for anaphora resolution and extraction.
        resolved_claim: The standalone, contextualized claim.
        source_quote: The exact verbatim quote from the source text.
        tda_id: The globally unique Opaque Stripe ID of this atom.
        source_id: The spatial anchor (Chunk ID) indicating where the claim originated.
    """

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    reasoning: str = Field(description="Chain-of-thought: reasoning for anaphora resolution and claim extraction.")
    resolved_claim: str = Field(description="The cleaned, standalone claim with all anaphora resolved.")
    source_quote: str = Field(description="The exact verbatim quote from the original text. Immutable evidence.")
    tda_id: str = Field(
        description="The Opaque Stripe ID of this atom.",
        pattern=r"^tda_[a-fA-F0-9]{16,32}$",
    )
    source_id: str | None = Field(
        default=None,
        description="The spatial anchor (Chunk ID).",
    )


class LinkedAtomGraph(BaseModel):
    """Wraps an ExtractedAtom with its topological dependencies (the DAG).

    Attributes:
        atom: The extracted claim and its metadata.
        depends_on: Implicit AND-list of causal dependencies that must be met before evaluating this atom.
    """

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    atom: ExtractedAtom = Field(description="The extracted claim.")
    depends_on: list[CausalEdge] = Field(
        default_factory=list,
        description="Implicit AND-list. Atom is evaluated only if all parents match their expected_status.",
    )


class AtomExecutionState(BaseModel):
    """Runtime state for a single Atom in the DAG.

    Attributes:
        tda_id: The Opaque Stripe ID of the atom.
        status: The current evaluation status.
        short_circuit_reason_tda_ids: The list of parent IDs that caused a short-circuit (N/A) or block.
        evaluation_reasoning: Detailed reasoning for the assigned status.
    """

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    tda_id: str = Field(description="The Opaque Stripe ID of the atom.")
    status: ExecutionStatus = Field(
        default=ExecutionStatus.PENDING,
        description="The current runtime execution status.",
    )
    short_circuit_reason_tda_ids: list[str] = Field(
        default_factory=list,
        description="List of tda_id values that caused this atom to short-circuit (Blame determinism).",
    )
    evaluation_reasoning: str | None = Field(
        default=None,
        description="Reasoning generated by the evaluation engine or system error traces.",
    )


class OntologyEntity(BaseModel):
    """Represents a global entity or concept extracted from the document."""

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    name: str = Field(description="The name of the entity or concept.")
    description: str = Field(description="A brief description of what this entity represents in context.")


class GlobalOntologyMap(BaseModel):
    """A map of all global entities, concepts, and macro-rules in the document.

    Used to resolve cross-chunk anaphora and conditional logic (GECL).
    """

    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)

    entities: list[OntologyEntity] = Field(
        default_factory=list,
        description="A list of distinct entities, actors, and concepts.",
    )
    macro_rules: list[str] = Field(
        default_factory=list,
        description="A list of global rules or conditions that apply across the document.",
    )
