from typing import Any, Literal

from pydantic import Field, model_validator

from backend_v2.models.core_base import V2CoreBase
from backend_v2.models.enums import LaxXaiExtensionType


class OutputProfileConfig(V2CoreBase):
    """Configuration for Output Profile extensions."""

    visible_extensions: list[LaxXaiExtensionType]


class XAILogDto(V2CoreBase):
    """Structured XAI Log separating UI-facing translations from mathematical traces."""

    pedagogical_key: str
    engine_debug_trace: dict[str, Any] = Field(default_factory=dict)


class LightweightMatrixOutput(V2CoreBase):
    """Strict schema for the Lightweight Matrix Output."""

    raw_score: float | None = None
    normalized_score: float | None = Field(default=None, ge=0.0, le=100.0)
    level_breakdown: dict[str, dict[str, int]] | None = None
    justification: str = ""
    xai_log: XAILogDto | None = None
    evaluated_atoms: dict[str, bool | str] = Field(default_factory=dict)
    extensions: dict[LaxXaiExtensionType, Any] = Field(default_factory=dict)

    @staticmethod
    def map_llm_extensions_to_domain(raw_data: Any) -> Any:
        """Phase 9 Zero-Legacy: Map flat LLM schema keys to the nested domain extensions dictionary.

        This strictly bridges the gap between the flat LLM JSON output (generated by PromptCompiler)
        and the strict LightweightMatrixOutput domain schema.
        """
        if not isinstance(raw_data, dict):
            return raw_data

        mapped_data = raw_data.copy()
        extensions = mapped_data.get("extensions", {})
        if not isinstance(extensions, dict):
            extensions = {}

        mapping = {
            "step_1_evidence_scan": "justification",
            "semantic_reasoning": "justification",
            "step_2_mitigating_context": "missing_context",
            "contextual_override": "contextual_override",
            "exact_quote": "citation",
        }

        # Phase 4 Zero-Variance: Drop structural list fields that do not belong in matrix extensions
        mapped_data.pop("localized_anchors_found", None)

        for flat_key, enum_str in mapping.items():
            if flat_key in mapped_data:
                val = mapped_data.pop(flat_key)
                if val is not None:
                    if enum_str == "justification":
                        mapped_data["justification"] = val
                    extensions[enum_str] = val

        # Phase 4 Option B: Dynamically injected Zero-Compromise XAI extensions
        # Any remaining key that wasn't mapped above is treated as a dynamic extension.
        # This guarantees any new output_extension from seed_data works automatically.
        for remaining_key in list(mapped_data.keys()):
            # Prevent moving known base fields if they are somehow still here
            known_fields = [
                "justification",
                "extensions",
                "raw_score",
                "normalized_score",
                "evaluated_atoms",
                "level_breakdown",
                "xai_log",
            ]
            if remaining_key in known_fields:
                continue

            val = mapped_data.pop(remaining_key)
            if val is not None:
                extensions[remaining_key] = val

        mapped_data["extensions"] = extensions
        return mapped_data


class AtomEvaluationItemDTO(V2CoreBase):
    """Strict schema for individual atom evaluations in the waterfall pipeline."""

    atom_id: str
    mechanical_trace: str = ""
    exact_quote: str | None = None
    pre_quote_anchor: str | None = None
    post_quote_anchor: str | None = None
    status: Literal["PASS", "FAIL", "DLQ"] | None = None
    localized_anchors_found: list[str] = Field(default_factory=list)
    semantic_reasoning: str = ""
    contextual_override: bool = False
    dlq_status: bool | None = None

    @property
    def evidence_found(self) -> bool:
        """Phantom Boolean -esto: Sanitoi LLM:n tuottamat haamu-nullit."""
        if self.exact_quote is None:
            return False

        blacklist = {
            "null",
            "none",
            "n/a",
            "false",
            "",
            "ei löydy",
            "not found",
            "-",
            "ei mainittu",
            "none detected",
            "[]",
            "{}",
            "ei sovelleta",
            "ei lainausta",
            "no quote",
            "ei ole",
        }
        return self.exact_quote.strip().lower() not in blacklist

    def calculate_rule_satisfied(self, inverse_evidence: bool) -> bool | str:
        """Deterministinen tuomiovalta: Laskee rule_satisfied arvon kooditasolla."""
        if self.status:
            if self.status == "DLQ":
                return "DLQ"
            evidence_found = (self.status == "PASS")
            if inverse_evidence:
                return not evidence_found
            return evidence_found

        if inverse_evidence:
            return not self.evidence_found
        return self.evidence_found

    @model_validator(mode="after")
    def validate_anti_laziness(self) -> AtomEvaluationItemDTO:
        # exact_quote can naturally be empty and thus evidence_found will correctly be False.
        # But if the LLM hallucinated something, the @computed_field handles it.
        return self
