import re
import unicodedata
from typing import Any, Literal

from pydantic import ConfigDict, Field, ValidationInfo, field_validator, model_validator
from rapidfuzz import fuzz

from backend_v2.models.core_base import V2CoreBase
from backend_v2.models.enums import LaxXaiExtensionType


class OutputProfileConfig(V2CoreBase):
    """Configuration for Output Profile extensions."""

    visible_extensions: list[LaxXaiExtensionType]


class XAILogDto(V2CoreBase):
    """Structured XAI Log separating UI-facing translations from mathematical traces."""

    pedagogical_key: str
    engine_debug_trace: dict[str, Any] = Field(default_factory=dict)


class LightweightMatrixOutput(V2CoreBase):
    """Strict schema for the Lightweight Matrix Output."""

    raw_score: float | None = None
    normalized_score: float | None = Field(default=None)
    level_breakdown: dict[str, dict[str, int]] | None = None
    justification: str = ""
    xai_log: XAILogDto | None = None
    evaluated_atoms: dict[str, bool | str] = Field(default_factory=dict)
    extensions: dict[LaxXaiExtensionType, Any] = Field(default_factory=dict)

    @field_validator("normalized_score")
    @classmethod
    def validate_normalized_score(cls, v: float | None) -> float | None:
        """Enforces float range bounds off the Field level to prevent Vertex AI validation issues."""
        if v is not None:
            if v < 0.0 or v > 100.0:
                raise ValueError("Input should be less than or equal to 100")
        return v

    @staticmethod
    def map_llm_extensions_to_domain(raw_data: Any) -> Any:
        """Phase 9 Zero-Legacy: Map flat LLM schema keys to the nested domain extensions dictionary.

        This strictly bridges the gap between the flat LLM JSON output (generated by PromptCompiler)
        and the strict LightweightMatrixOutput domain schema.
        """
        if not isinstance(raw_data, dict):
            return raw_data

        mapped_data = raw_data.copy()
        extensions = mapped_data.setdefault("extensions", {})
        if not isinstance(extensions, dict):
            extensions = {}

        mapping = {
            "step_1_evidence_scan": "justification",
            "semantic_reasoning": "justification",
            "step_2_mitigating_context": "missing_context",
            "contextual_override": "contextual_override",
            "exact_quote": "citation",
        }

        # Phase 4 Zero-Variance: Drop structural list fields that do not belong in matrix extensions
        mapped_data.pop("localized_anchors_found", None)

        for flat_key, enum_str in mapping.items():
            if flat_key in mapped_data:
                val = mapped_data.pop(flat_key)
                if val is not None:
                    if enum_str == "justification":
                        mapped_data["justification"] = val
                    extensions[enum_str] = val

        # Phase 4 Option B: Dynamically injected Zero-Compromise XAI extensions
        # Any remaining key that wasn't mapped above is treated as a dynamic extension.
        # This guarantees any new output_extension from seed_data works automatically.
        for remaining_key in list(mapped_data.keys()):
            # Prevent moving known base fields if they are somehow still here
            known_fields = [
                "justification",
                "extensions",
                "raw_score",
                "normalized_score",
                "evaluated_atoms",
                "level_breakdown",
                "xai_log",
            ]
            if remaining_key in known_fields:
                continue

            val = mapped_data.pop(remaining_key)
            if val is not None:
                extensions[remaining_key] = val

        mapped_data["extensions"] = extensions
        return mapped_data


class MergedFactsDTO(V2CoreBase):
    """Holds global aggregation results safely with ConfigDict(extra='allow')."""

    model_config = ConfigDict(extra="allow", frozen=True)


class AtomEvaluationItemDTO(V2CoreBase):
    """Strict schema for individual atom evaluations in the waterfall pipeline."""

    atom_id: str
    extracted_facts: dict[str, str | None] = Field(default_factory=dict)
    exact_quote: str | None = None
    post_quote_anchor: str | None = None
    status: Literal["PASS", "FAIL", "DLQ"] | None = None
    localized_anchors_found: list[str] = Field(default_factory=list)
    semantic_reasoning: str = ""
    contextual_override: bool = False
    dlq_status: bool | None = None

    @property
    def evidence_found(self) -> bool:
        """Phantom Boolean mitigation to sanitize fake null values returned by LLM."""
        blacklist = {
            "null",
            "none",
            "n/a",
            "false",
            "",
            "ei l\u00f6ydy",
            "not found",
            "-",
            "ei mainittu",
            "none detected",
            "[]",
            "{}",
            "ei sovelleta",
            "ei lainausta",
            "no quote",
            "ei ole",
            "[contextual_override_applied]",
        }
        if self.exact_quote is not None and self.exact_quote.strip().lower() not in blacklist:
            return True
        for val in self.extracted_facts.values():
            if val is not None and val.strip().lower() not in blacklist:
                return True
        return False

    def calculate_rule_satisfied(self, inverse_evidence: bool, allow_contextual_override: bool = False) -> bool | str:
        """Deterministinen tuomiovalta: Laskee rule_satisfied arvon kooditasolla."""
        if allow_contextual_override and self.contextual_override:
            return True

        if self.status:
            if self.status == "DLQ":
                return "DLQ"
            evidence_found = self.status == "PASS"
            if inverse_evidence:
                return not evidence_found
            return evidence_found

        if inverse_evidence:
            return not self.evidence_found
        return self.evidence_found

    @model_validator(mode="after")
    def _enforce_zero_variance_protocols(self, info: ValidationInfo) -> Any:
        if self.contextual_override:
            # Rule 6: Blind Extraction Null Hypothesis enforcement
            object.__setattr__(self, "exact_quote", None)

            # Milestone 4: Spatiaalinen ankkurointi & Anti-Laziness enforcement
            reasoning = self.semantic_reasoning or ""
            if len(reasoning) < 50:
                raise ValueError("Contextual override requires semantic_reasoning to be at least 50 characters long.")

            spatial_markers = [
                "page",
                "paragraph",
                "section",
                "kappale",
                "sivu",
                "chapter",
                "luku",
                "otsikko",
                "line",
                "rivi",
            ]
            reasoning_lower = reasoning.lower()
            if not any(marker in reasoning_lower for marker in spatial_markers):
                raise ValueError(
                    "Contextual override reasoning must contain a spatial/structural location reference "
                    "(e.g., page, paragraph, section, sivu, kappale)."
                )
            return self
        else:
            # Milestone 3: Check quote integrity
            if self.exact_quote:
                context = info.context if info else None
                source_text = context.get("source_text") if context else None
                if source_text:
                    # Normalize both source and quote using NFKC and collapsing whitespaces
                    def normalize_text(text: str) -> str:
                        if not text:
                            return ""
                        normalized = unicodedata.normalize("NFKC", text).lower()
                        normalized = re.sub(r"\s+", " ", normalized).strip()
                        return normalized

                    norm_source = normalize_text(source_text)
                    norm_quote = normalize_text(self.exact_quote)

                    if norm_quote not in norm_source:
                        score = fuzz.partial_ratio(norm_quote, norm_source)
                        if score < 95.0:
                            raise ValueError(
                                f"exact_quote not found in source text with high enough similarity "
                                f"(got {score:.1f}%, required >= 95.0%)."
                            )
        return self
