from typing import Any, Literal

from pydantic import ConfigDict, Field, ValidationInfo, field_validator, model_validator
from rapidfuzz import fuzz

from backend_v2.models.core_base import V2CoreBase
from backend_v2.models.enums import LaxXaiExtensionType, SystemConcurrency, get_lexical_fuzz_threshold


class OutputProfileConfig(V2CoreBase):
    """Configuration for Output Profile extensions.

    Attributes:
        visible_block_extensions: List of extensions enabled at the block level.
        visible_workflow_extensions: List of extensions enabled globally across the workflow.
    """

    visible_block_extensions: list[LaxXaiExtensionType]
    visible_workflow_extensions: list[LaxXaiExtensionType]


class XAILogDto(V2CoreBase):
    """Structured XAI Log separating UI-facing translations from mathematical traces.

    Attributes:
        pedagogical_key: The designated mapping key for UI-facing explanations.
        engine_debug_trace: System dictionary containing mathematical/diagnostic reasoning.
    """

    pedagogical_key: str
    engine_debug_trace: dict[str, Any] = Field(default_factory=dict)


class LightweightMatrixOutput(V2CoreBase):
    """Strict schema for the Lightweight Matrix Output.

    Attributes:
        raw_score: Original unnormalized float evaluation score.
        normalized_score: Final scaled score ranging from 0.0 to 100.0.
        level_breakdown: Complex dictionary mapping multi-tier performance indicators.
        justification: Primary text string explaining the dimension result.
        xai_log: Nested logging details isolating debugging data.
        evaluated_atoms: Mapping tracking which structural logic atoms were hit.
        extensions: Arbitrarily mapped XAI extensions dict for UI components.
        allowed_extensions: Explicit list restricting dynamic schema mappings.
    """

    raw_score: float | None = None
    normalized_score: float | None = Field(default=None)
    level_breakdown: dict[str, dict[str, int]] | None = None
    justification: str = ""
    xai_log: XAILogDto | None = None
    evaluated_atoms: dict[str, bool | str] = Field(default_factory=dict)
    extensions: dict[LaxXaiExtensionType, Any] = Field(default_factory=dict)
    allowed_extensions: list[LaxXaiExtensionType] | None = None

    @field_validator("normalized_score")
    @classmethod
    def _validate_normalized_score(cls, v: float | None) -> float | None:
        if v is not None and not (0.0 <= v <= 100.0):
            raise ValueError("normalized_score must be between 0.0 and 100.0")
        return v

    @staticmethod
    def map_llm_extensions_to_domain(raw_data: Any) -> Any:
        """Phase 9 Zero-Legacy: Map flat LLM schema keys to the nested domain extensions dictionary.

        This strictly bridges the gap between the flat LLM JSON output (generated by PromptCompiler)
        and the strict LightweightMatrixOutput domain schema.

        Args:
            raw_data: The flat dictionary parsed from the LLM JSON block.

        Returns:
            The newly mapped domain dictionary nesting arbitrary XAI keys into 'extensions'.
        """
        if not isinstance(raw_data, dict):
            return raw_data

        mapped_data = raw_data.copy()
        extensions = mapped_data.get("extensions", {})
        if not isinstance(extensions, dict):
            extensions = {}

        mapping = {
            "step_1_evidence_scan": "justification",
            "semantic_reasoning": "justification",
            "step_2_mitigating_context": "missing_context",
            "contextual_override": "contextual_override",
            "exact_quotes": "citation",
        }

        # Phase 4 Zero-Variance: Drop structural list fields that do not belong in matrix extensions
        for flat_key, enum_str in mapping.items():
            if flat_key in mapped_data:
                val = mapped_data.pop(flat_key)
                if val is not None:
                    if enum_str == "justification":
                        mapped_data["justification"] = val
                    extensions[enum_str] = val

        # Phase 4 Option B: Dynamically injected Zero-Compromise XAI extensions
        # Any remaining key that wasn't mapped above is treated as a dynamic extension.
        # This guarantees any new output_extension from seed_data works automatically.
        for remaining_key in list(mapped_data.keys()):
            # Prevent moving known base fields if they are somehow still here
            known_fields = [
                "justification",
                "extensions",
                "raw_score",
                "normalized_score",
                "evaluated_atoms",
                "level_breakdown",
                "xai_log",
                "allowed_extensions",
            ]
            if remaining_key in known_fields:
                continue

            val = mapped_data.pop(remaining_key)
            if val is not None:
                extensions[remaining_key] = val

        mapped_data["extensions"] = extensions
        return mapped_data


class MergedFactsDTO(V2CoreBase):
    """Holds global aggregation results safely with ConfigDict(extra='allow').

    Attributes:
        model_config: Pydantic configuration allowing extra attributes.
    """

    model_config = ConfigDict(extra="allow", frozen=True)


class LightweightExtractionAtom(V2CoreBase):
    """Strict schema for Zero-Reasoning extraction protocols.

    This model enforces the 'Zero-Reasoning Mandate' by lacking cognitive fields
    like semantic_reasoning. This reduces token load and prevents hallucination.

    Attributes:
        atom_id: The unique identifier tracking this extraction atom logic.
        extracted_facts: Dictionary of data fragments extracted from source.
        exact_quote: Strict text matched physically within the source text.
        status: The evaluation status. Must be one of PASS, FAIL, DLQ.
        confidence: Internal confidence factor metric between 0.0 and 1.0.
    """

    atom_id: str
    extracted_facts: dict[str, str | None] = Field(default_factory=dict)
    exact_quotes: list[str] = Field(
        default_factory=list,
        max_length=SystemConcurrency.SCHEMA_MAX_QUOTES.value,
        description=(
            f"A list of physically contiguous, character-for-character verbatim substrings extracted "
            f"directly from the source text. Maximum {SystemConcurrency.SCHEMA_MAX_QUOTES_TARGET.value} items. Each quote MUST be UNDER {SystemConcurrency.SCHEMA_MAX_QUOTE_LENGTH.value} characters. "
            f"NEVER translate, fix grammar, paraphrase, or alter the language. The quote MUST remain "
            f"in the ORIGINAL language of the source document."
        ),
    )
    status: Literal["PASS", "FAIL", "CONTESTED", "DLQ"] | None = Field(
        default=None, description="The evaluation status. Must be one of PASS, FAIL, CONTESTED, DLQ."
    )
    confidence: float | None = Field(default=None)

    @field_validator("exact_quotes", mode="before")
    @classmethod
    def _truncate_quotes(cls, v: Any) -> Any:
        if isinstance(v, list):
            max_len = SystemConcurrency.SCHEMA_MAX_QUOTES.value
            if len(v) > max_len:
                return v[:max_len]
        return v

    @field_validator("confidence")
    @classmethod
    def _validate_confidence(cls, v: float | None) -> float | None:
        if v is not None and not (0.0 <= v <= 1.0):
            raise ValueError("confidence must be between 0.0 and 1.0")
        return v

    @property
    def evidence_found(self) -> bool:
        """Phantom Boolean -esto: Sanitoi LLM:n tuottamat haamu-nullit.

        Returns:
            True if meaningful, non-hallucinated evidence text is found, else False.
        """
        blacklist = {"null", "none", "n/a", "false", "", "ei löydy", "not found", "-", "[]", "{}"}
        if self.exact_quotes:
            for quote in self.exact_quotes:
                if quote.strip().lower() not in blacklist:
                    return True
        for val in self.extracted_facts.values():
            if val is not None and val.strip().lower() not in blacklist:
                return True
        return False

    def calculate_rule_satisfied(self, inverse_evidence: bool, allow_contextual_override: bool = False) -> bool | str:
        """Deterministinen tuomiovalta. Kevyt uutto ei tue contextual_overridea.

        Args:
            inverse_evidence: True to flip logic condition (e.g. absence means PASS).
            allow_contextual_override: Ignored parameter for strict interface parity.

        Returns:
            Evaluated boolean rule, or string 'DLQ' if dead letter queue was hit.
        """
        if self.status:
            if self.status == "DLQ":
                return "DLQ"
            # Phase 1: CONTESTED bypasses inversion logic
            if self.status == "CONTESTED":
                return True
            evidence_found = self.status == "PASS"
            if inverse_evidence:
                return not evidence_found
            return evidence_found

        if inverse_evidence:
            return not self.evidence_found
        return self.evidence_found

    # Compatibility properties for scoring.py
    @property
    def contextual_override(self) -> bool:
        return False

    @property
    def structural_location(self) -> str:
        return "N/A"

    @property
    def semantic_reasoning(self) -> str:
        return "N/A (Kevyt poiminta)"


class ReasoningStepDTO(V2CoreBase):
    """Structured micro-CoT reasoning step schema to prevent JSON escaping issues."""

    step_1_identify_premise: str = Field(description="Extract the exact claim from the prompt.")
    step_2_scan_source: str = Field(
        description="Analyze if the source text physically contains evidence for or against the premise."
    )
    step_3_evaluate_anti_patterns: str = Field(description="Check if any strict anti-patterns or exclusions apply.")
    step_4_final_conclusion: str = Field(description="Synthesize steps 1-3 into a final logical conclusion.")


class AtomEvaluationItemDTO(V2CoreBase):
    """Strict schema for individual atom evaluations in the waterfall pipeline.

    Attributes:
        atom_id: Identifying key of the executed atom node.
        extracted_facts: Collected findings data explicitly extracted from context.
        exact_quote: String data ensuring precise verification boundaries.
        internal_logic_en: Rigorous internal mathematical/logical Chain of Thought in English.
        status: Evaluated lifecycle status state marker string.
        semantic_reasoning: Detailed reasoning for the evaluation output.
        contextual_override: Boolean flag enabling non-strict logic jumps.
        structural_location: Location reference where exact context occurred.
        dlq_status: Internal indicator to track failure tracking queues.
    """

    atom_id: str
    used_evidence_ids: list[str] = Field(
        default_factory=list,
        description="List of exact <search_result id> strings you relied upon for this specific extraction.",
    )
    extracted_facts: dict[str, str | None] = Field(default_factory=dict)
    exact_quotes: list[str] = Field(
        default_factory=list,
        max_length=SystemConcurrency.SCHEMA_MAX_QUOTES.value,
        description=(
            f"A list of physically contiguous, character-for-character verbatim substrings extracted "
            f"directly from the source text. Maximum {SystemConcurrency.SCHEMA_MAX_QUOTES_TARGET.value} items. Each quote MUST be UNDER {SystemConcurrency.SCHEMA_MAX_QUOTE_LENGTH.value} characters. "
            f"NEVER translate, fix grammar, paraphrase, or alter the language. The quote MUST remain "
            f"in the ORIGINAL language of the source document."
        ),
    )
    internal_logic_en: ReasoningStepDTO = Field(
        description="Rigorous internal mathematical/logical Chain of Thought deduction mapped step-by-step in English."
    )
    status: Literal["PASS", "FAIL", "CONTESTED", "DLQ"] | None = Field(
        default=None, description="The evaluation status. Must be one of PASS, FAIL, CONTESTED, DLQ."
    )
    counter_quote: str | None = Field(
        default=None,
        description=(
            "If you believe the exact_quotes are taken out of context, provide a SEPARATE "
            "verbatim quote from the source text that contradicts or contextualizes them. "
            "This counter-evidence MUST also be a physically contiguous substring. "
            "If you cannot find contradicting evidence, leave this as null."
        ),
    )
    semantic_reasoning: str = Field(
        description="Detailed reasoning for the evaluation. Must be in the Localized Target Language.",
    )
    contextual_override: bool = Field(
        description=(
            "Set to true ONLY if evidence is implicitly valid despite lacking exact quote. "
            "If true, you MUST populate structural_location."
        ),
    )
    structural_location: str = Field(
        description=(
            "Exact structural location (e.g. 'page 3', 'paragraph 2'). Must be in the Localized "
            "Target Language. If contextual_override is False, you MUST output 'N/A'. "
            "If contextual_override is True, you MUST provide the concrete location."
        ),
    )
    dlq_status: bool | None = None

    @field_validator("exact_quotes", mode="before")
    @classmethod
    def _truncate_quotes(cls, v: Any) -> Any:
        if isinstance(v, list):
            max_len = SystemConcurrency.SCHEMA_MAX_QUOTES.value
            if len(v) > max_len:
                return v[:max_len]
        return v

    @property
    def evidence_found(self) -> bool:
        """Phantom Boolean -esto: Sanitoi LLM:n tuottamat haamu-nullit.

        Returns:
            True if robust quote or extracted data exists, False otherwise.
        """
        blacklist = {
            "null",
            "none",
            "n/a",
            "false",
            "",
            "ei löydy",
            "not found",
            "-",
            "ei mainittu",
            "none detected",
            "[]",
            "{}",
            "ei sovelleta",
            "ei lainausta",
            "no quote",
            "ei ole",
            "[contextual_override_applied]",
        }
        if self.exact_quotes:
            for quote in self.exact_quotes:
                if quote.strip().lower() not in blacklist:
                    return True
        for val in self.extracted_facts.values():
            if val is not None and val.strip().lower() not in blacklist:
                return True
        return False

    def calculate_rule_satisfied(self, inverse_evidence: bool, allow_contextual_override: bool = False) -> bool | str:
        """Deterministinen tuomiovalta: Laskee rule_satisfied arvon kooditasolla.

        Args:
            inverse_evidence: True if successful condition implies missing evidence.
            allow_contextual_override: True if explicit spatial contextual bridging is allowed.

        Returns:
            True if atom logic evaluates to satisfied, False if not, or 'DLQ' if corrupt.
        """
        if allow_contextual_override and self.contextual_override:
            return True

        if self.status:
            if self.status == "DLQ":
                return "DLQ"
            # Phase 1: CONTESTED bypasses inversion logic
            if self.status == "CONTESTED":
                return True
            evidence_found = self.status == "PASS"
            if inverse_evidence:
                return not evidence_found
            return evidence_found

        if inverse_evidence:
            return not self.evidence_found
        return self.evidence_found

    @model_validator(mode="before")
    @classmethod
    def _enforce_null_hypothesis_before(cls, data: Any) -> Any:
        if isinstance(data, dict):
            if data.get("contextual_override"):
                data["exact_quotes"] = []
        return data

    @model_validator(mode="after")
    def _enforce_zero_variance_protocols(self, info: ValidationInfo) -> AtomEvaluationItemDTO:
        """Validates spatial anchoring, Anti-Laziness enforcement, and quote integrity.

        Args:
            info: The validation info context provided by Pydantic V2 engine.

        Returns:
            The validated instance if it meets Zero-Variance mandates.

        Raises:
            ValueError: If lengths, strings or contextual fuzz ratios fail compliance checks.
        """
        if self.contextual_override:
            # Milestone 4: Spatiaalinen ankkurointi & Anti-Laziness enforcement
            reasoning = self.semantic_reasoning or ""
            if len(reasoning) < 50:
                raise ValueError("Contextual override requires semantic_reasoning to be at least 50 characters long.")

            if not self.structural_location or self.structural_location.strip().upper() == "N/A":
                raise ValueError(
                    "Contextual override requires an explicit structural_location reference "
                    "(e.g., 'page 3', 'paragraph 2')."
                )
        else:
            # Milestone 3: Check quote integrity
            if self.exact_quotes:
                context = info.context if info else None
                source_text = context.get("source_text") if context else None
                has_mcp_tools = context.get("has_mcp_tools", False) if context else False
                if source_text and not has_mcp_tools:
                    # Normalize both source and quote using the same exact logic as the orchestrator
                    from backend_v2.services.orchestrator.anchor_validation_service import AnchorValidationService

                    norm_source, _ = AnchorValidationService.normalize_text_with_mapping(source_text)
                    locale = context.get("system_locale") if context else None
                    threshold = get_lexical_fuzz_threshold(locale)
                    max_len = SystemConcurrency.SCHEMA_MAX_QUOTE_LENGTH.value

                    for quote in self.exact_quotes:
                        if len(quote) > max_len:
                            raise ValueError(
                                f"Quote too long ({len(quote)} chars > {max_len}). "
                                "Split into separate shorter quotes from different source locations."
                            )
                        norm_quote, _ = AnchorValidationService.normalize_text_with_mapping(quote)
                        if not norm_quote:
                            continue
                        if norm_quote not in norm_source:
                            score = fuzz.partial_ratio(norm_quote, norm_source)
                            if score < threshold:
                                raise ValueError(
                                    f"exact_quote '{quote[:20]}...' not found in source text with high enough similarity "
                                    f"(got {score:.1f}%, required >= {threshold:.1f}%)."
                                )
        return self
