import pytest

from backend_v2.exceptions import AppException, ErrorCodes
from backend_v2.llm.ingress_pipeline import UniversalIngress


def test_parse_llm_output_success():
    """Test successful parsing of raw JSON."""
    raw_text = """
    {
      "test_key": "test_value"
    }
    """
    result = UniversalIngress.parse_llm_output(raw_text)
    assert result["test_key"] == "test_value"


def test_parse_llm_output_markdown_stripping():
    """Test parsing strips markdown fences correctly."""
    raw_text = """```json
{
  "test_key": "test_value"
}
```"""
    result = UniversalIngress.parse_llm_output(raw_text)
    assert result["test_key"] == "test_value"


def test_parse_llm_output_self_healing_trailing_comma():
    """Test self-healing fixes a trailing comma."""
    raw_text = """
    {
      "invalid_key": "value",
    }
    """
    result = UniversalIngress.parse_llm_output(raw_text)
    assert result["invalid_key"] == "value"


def test_parse_llm_output_self_healing_unescaped_quotes():
    """Test self-healing fixes unescaped double quotes inside string."""
    raw_text = """
    {
      "reasoning": "The user said "hello" to me."
    }
    """
    result = UniversalIngress.parse_llm_output(raw_text)
    assert result["reasoning"] == 'The user said "hello" to me.'


def test_parse_llm_output_unrepairable():
    """Test parsing still raises AppException if the text is completely non-JSON."""
    raw_text = "This is just raw text without any JSON structure."
    with pytest.raises(AppException) as exc:
        UniversalIngress.parse_llm_output(raw_text)

    assert exc.value.details["error_code"] == ErrorCodes.PARSING_FAILED.value
    assert "Malformed JSON in LLM output. Self-healing failed." in exc.value.message


def test_parse_llm_output_list_wrapper():
    """Test parsing of a top-level list wraps it in a dict."""
    raw_text = """
    [
      {"item": 1},
      {"item": 2}
    ]
    """
    result = UniversalIngress.parse_llm_output(raw_text)
    assert "data" in result
    assert len(result["data"]) == 2
    assert result["data"][0]["item"] == 1


def test_clean_dict_against_model_alias_stripping_bug():
    """Reproduces the bug where clean_dict_against_model strips fields generated by the LLM
    if they match the Pydantic alias (e.g. eval_1) instead of the underlying field name.
    """
    from pydantic import BaseModel, ConfigDict, Field

    class AliasModel(BaseModel):
        model_config = ConfigDict(populate_by_name=True)
        my_field: str = Field(..., alias="eval_1")
        other_field: str

    # The LLM generates the JSON using the 'eval_1' alias, as instructed by the JSON Schema
    raw_llm_payload = {"eval_1": "Target Data", "other_field": "Normal Data"}

    # ACL cleans the dict
    cleaned = UniversalIngress.clean_dict_against_model(raw_llm_payload, AliasModel)

    # We expect 'eval_1' to still be present (or remapped to 'my_field') so it can pass validation
    assert "eval_1" in cleaned or "my_field" in cleaned, "The aliased field was incorrectly stripped!"

    # And validation should succeed
    validated = AliasModel.model_validate(cleaned)
    assert validated.my_field == "Target Data"
