// Mocks generated by Mockito 5.4.6 from annotations
// in client_app/test/features/orchestration/presentation/providers/execution_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:client_app/core/error/app_error.dart' as _i4;
import 'package:client_app/features/orchestration/data/repositories/execution_repository.dart'
    as _i2;
import 'package:client_app/features/orchestration/domain/models/execution.dart'
    as _i7;
import 'package:client_app/features/orchestration/domain/models/execution_input.dart'
    as _i5;
import 'package:fpdart/fpdart.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ExecutionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExecutionRepository extends _i1.Mock
    implements _i2.ExecutionRepository {
  @override
  _i3.TaskEither<_i4.AppError, String> createExecution(
    _i5.ExecutionInput? input,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createExecution, [input]),
            returnValue: _i6.dummyValue<_i3.TaskEither<_i4.AppError, String>>(
              this,
              Invocation.method(#createExecution, [input]),
            ),
            returnValueForMissingStub: _i6
                .dummyValue<_i3.TaskEither<_i4.AppError, String>>(
                  this,
                  Invocation.method(#createExecution, [input]),
                ),
          )
          as _i3.TaskEither<_i4.AppError, String>);

  @override
  _i3.TaskEither<_i4.AppError, List<_i7.Execution>> fetchExecutions({
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchExecutions, [], {#limit: limit}),
            returnValue: _i6
                .dummyValue<_i3.TaskEither<_i4.AppError, List<_i7.Execution>>>(
                  this,
                  Invocation.method(#fetchExecutions, [], {#limit: limit}),
                ),
            returnValueForMissingStub: _i6
                .dummyValue<_i3.TaskEither<_i4.AppError, List<_i7.Execution>>>(
                  this,
                  Invocation.method(#fetchExecutions, [], {#limit: limit}),
                ),
          )
          as _i3.TaskEither<_i4.AppError, List<_i7.Execution>>);

  @override
  _i3.TaskEither<_i4.AppError, _i7.Execution> getExecution(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getExecution, [id]),
            returnValue: _i6
                .dummyValue<_i3.TaskEither<_i4.AppError, _i7.Execution>>(
                  this,
                  Invocation.method(#getExecution, [id]),
                ),
            returnValueForMissingStub: _i6
                .dummyValue<_i3.TaskEither<_i4.AppError, _i7.Execution>>(
                  this,
                  Invocation.method(#getExecution, [id]),
                ),
          )
          as _i3.TaskEither<_i4.AppError, _i7.Execution>);

  @override
  _i8.Stream<_i3.Either<_i4.AppError, _i7.Execution>> streamExecution(
    String? id, {
    Duration? interval = const Duration(seconds: 2),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamExecution, [id], {#interval: interval}),
            returnValue:
                _i8.Stream<_i3.Either<_i4.AppError, _i7.Execution>>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i3.Either<_i4.AppError, _i7.Execution>>.empty(),
          )
          as _i8.Stream<_i3.Either<_i4.AppError, _i7.Execution>>);
}
