"""Prompts package.

Centralizes prompt definitions and global mandates for the LLM execution pipeline.
"""

from .field_prompts import (
    DESC_CONTEXTUAL_OVERRIDE,
    DESC_EVALUATION_NOTES,
    DESC_EXACT_QUOTES,
    DESC_REASONING_TRACE,
    STRICT_JSON_STRUCTURE_MANDATE,
    XAI_DESC_CITATION,
    XAI_DESC_COACHING,
    XAI_DESC_CONFIDENCE,
    XAI_DESC_FALSIFICATION,
    XAI_DESC_JUSTIFICATION,
)
from .global_mandates import (
    ANTI_ID_MANDATE,
    ANTI_SCORE_MANDATE,
    EPISTEMIC_GLOSSARY_MANDATE,
    EXTENSION_ANCHORING_MANDATE,
    GLOBAL_MANDATES_XML,
    LANGUAGE_MANDATE,
    NULL_HYPOTHESIS_MANDATE,
    SCHEMA_PURITY_MANDATE,
    SEMANTIC_BLEED_MANDATE,
    TONE_MANDATE,
    VERBATIM_EXTRACTION_MANDATE,
)
from .hook_prompts import (
    INTERACTION_OBJECTIVE,
    INTERACTION_RULES,
    SYNTHESIS_CITATION_RULES,
    SYNTHESIS_LENGTH_CONSTRAINT,
    SYNTHESIS_SDUI_MANDATES,
    SYNTHESIS_SECTION_RULES_PREFIX,
    SYNTHESIS_STATE_ISOLATION_MANDATE,
    SYNTHESIS_XAI_CURATION,
)
from .linguistic_directives import build_linguistic_context

__all__ = [
    "ANTI_ID_MANDATE",
    "ANTI_SCORE_MANDATE",
    "DESC_CONTEXTUAL_OVERRIDE",
    "DESC_EVALUATION_NOTES",
    "DESC_EXACT_QUOTES",
    "DESC_REASONING_TRACE",
    "EPISTEMIC_GLOSSARY_MANDATE",
    "EXTENSION_ANCHORING_MANDATE",
    "GLOBAL_MANDATES_XML",
    "INTERACTION_OBJECTIVE",
    "INTERACTION_RULES",
    "LANGUAGE_MANDATE",
    "NULL_HYPOTHESIS_MANDATE",
    "SCHEMA_PURITY_MANDATE",
    "SEMANTIC_BLEED_MANDATE",
    "STRICT_JSON_STRUCTURE_MANDATE",
    "SYNTHESIS_CITATION_RULES",
    "SYNTHESIS_LENGTH_CONSTRAINT",
    "SYNTHESIS_SDUI_MANDATES",
    "SYNTHESIS_SECTION_RULES_PREFIX",
    "SYNTHESIS_STATE_ISOLATION_MANDATE",
    "SYNTHESIS_XAI_CURATION",
    "TONE_MANDATE",
    "VERBATIM_EXTRACTION_MANDATE",
    "XAI_DESC_CITATION",
    "XAI_DESC_COACHING",
    "XAI_DESC_CONFIDENCE",
    "XAI_DESC_FALSIFICATION",
    "XAI_DESC_JUSTIFICATION",
    "build_linguistic_context",
]
