import logging
from typing import Annotated

from pydantic import Field

from backend_v2.models.core_base import V2CoreBase

logger = logging.getLogger(__name__)


class TokenUsage(V2CoreBase):
    """Strictly typed token usage statistics.

    Attributes:
        prompt_tokens: Number of tokens consumed in the request prompt.
        completion_tokens: Number of tokens generated in the model's response.
        total_tokens: Total tokens used in the interaction.
        cached_tokens: Number of tokens retrieved from the cache.
        reasoning_tokens: Number of tokens generated internally for reasoning steps.
        cache_creation_input_tokens: Number of tokens written to the cache context.
        cost_usd: Estimated monetary cost of the execution in USD.
        estimated_savings_usd: Estimated savings in USD derived from cached responses.
    """

    prompt_tokens: Annotated[int, Field(ge=0, description="Tokens used in the prompt.")]
    completion_tokens: Annotated[int, Field(ge=0, description="Tokens generated by the model.")]
    total_tokens: Annotated[int, Field(ge=0, description="Total tokens used.")]
    cached_tokens: Annotated[
        int, Field(ge=0, description="Tokens retrieved from cache.", json_schema_extra={"x-ui-label": "Cached Tokens"})
    ] = 0
    reasoning_tokens: Annotated[
        int,
        Field(
            ge=0,
            description="Tokens used for reasoning/thought generation.",
            json_schema_extra={"x-ui-label": "Reasoning Tokens"},
        ),
    ] = 0
    cache_creation_input_tokens: Annotated[
        int,
        Field(
            ge=0,
            description="Tokens written to cache (Cache Write/Miss).",
            json_schema_extra={"x-ui-label": "Cache Creation Tokens"},
        ),
    ] = 0
    cost_usd: Annotated[float, Field(ge=0.0, description="Estimated cost in USD.")] = 0.0
    estimated_savings_usd: Annotated[
        float,
        Field(
            ge=0.0,
            description="Estimated savings in USD due to caching.",
            json_schema_extra={"x-ui-label": "Estimated Savings"},
        ),
    ] = 0.0

    def __add__(self, other: TokenUsage) -> TokenUsage:
        """Allows adding two TokenUsage objects together.

        Args:
            other: The other TokenUsage object to add.

        Returns:
            A new TokenUsage instance containing the sum of both instances.
        """
        return TokenUsage(
            prompt_tokens=self.prompt_tokens + other.prompt_tokens,
            completion_tokens=self.completion_tokens + other.completion_tokens,
            total_tokens=self.total_tokens + other.total_tokens,
            cached_tokens=self.cached_tokens + other.cached_tokens,
            cache_creation_input_tokens=self.cache_creation_input_tokens + other.cache_creation_input_tokens,
            reasoning_tokens=self.reasoning_tokens + other.reasoning_tokens,
            cost_usd=self.cost_usd + other.cost_usd,
            estimated_savings_usd=self.estimated_savings_usd + other.estimated_savings_usd,
        )


class UsageAggregate(V2CoreBase):
    """Cumulative aggregated usage statistics per scope and entity.

    Attributes:
        scope: Scope of the aggregate (system, organization, user).
        entity_id: Optional ID of the scoped entity.
        period: Reporting period (e.g. '2026-02', 'all-time').
        usage: Cumulative token and cost statistics.
        total_executions: Total number of recorded execution traces in the period.
    """

    scope: Annotated[str, Field(min_length=1, description="Scope of the aggregate (system, organization, user).")]
    entity_id: Annotated[str | None, Field(description="ID of the entity (if not system).")] = None
    period: Annotated[str, Field(min_length=1, description="Reporting period (e.g., '2026-02', 'all-time').")]

    usage: Annotated[TokenUsage, Field(description="Cumulative token and cost statistics.")] = Field(
        default_factory=lambda: TokenUsage(prompt_tokens=0, completion_tokens=0, total_tokens=0)
    )
    total_executions: Annotated[int, Field(ge=0, description="Total number of recorded executions in this period.")] = 0


class UsageReport(V2CoreBase):
    """Report for aggregated usage statistics across different scopes.

    Attributes:
        scope: Scope of the report (system, organization, user).
        entity_id: Optional ID of the scoped entity.
        period: Reporting period.
        usage: Aggregated token and cost statistics.
        quota_limit_usd: Optional quota limit constraint defined in USD.
        percentage_used: Optional percentage indicating quota consumption.
    """

    scope: Annotated[str, Field(min_length=1, description="Scope of the report (system, organization, user).")]
    entity_id: Annotated[str | None, Field(description="ID of the entity (if not system).")] = None
    period: Annotated[str, Field(min_length=1, description="Reporting period (e.g., '2026-02', 'all-time').")]

    usage: Annotated[TokenUsage, Field(description="Aggregated token and cost statistics.")] = Field(
        default_factory=lambda: TokenUsage(prompt_tokens=0, completion_tokens=0, total_tokens=0)
    )

    quota_limit_usd: Annotated[float | None, Field(ge=0.0, description="Quota limit in USD, if applicable.")] = None
    percentage_used: Annotated[float | None, Field(ge=0.0, description="Percentage of quota used, if applicable.")] = (
        None
    )
