// Mocks generated by Mockito 5.4.6 from annotations
// in client_app/test/features/studio/presentation/providers/studio_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:client_app/features/studio/data/studio_repository.dart' as _i4;
import 'package:client_app/features/studio/domain/models/workflow_def.dart'
    as _i2;
import 'package:flutter/src/foundation/diagnostics.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWorkflowDef_0 extends _i1.SmartFake implements _i2.WorkflowDef {
  _FakeWorkflowDef_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [StudioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStudioRepository extends _i1.Mock implements _i4.StudioRepository {
  MockStudioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.WorkflowDef>> getWorkflows() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkflows, []),
            returnValue: _i5.Future<List<_i2.WorkflowDef>>.value(
              <_i2.WorkflowDef>[],
            ),
          )
          as _i5.Future<List<_i2.WorkflowDef>>);

  @override
  _i5.Future<_i2.WorkflowDef> getWorkflow(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkflow, [id]),
            returnValue: _i5.Future<_i2.WorkflowDef>.value(
              _FakeWorkflowDef_0(this, Invocation.method(#getWorkflow, [id])),
            ),
          )
          as _i5.Future<_i2.WorkflowDef>);

  @override
  _i5.Future<void> saveWorkflow(_i2.WorkflowDef? workflow) =>
      (super.noSuchMethod(
            Invocation.method(#saveWorkflow, [workflow]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteWorkflow(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkflow, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
