import json
from pathlib import Path

SEED_FILE = Path(r"c:\src\quorum\backend_v2\seed\seed_data.json")

def inject_profiles():
    with open(SEED_FILE, encoding="utf-8") as f:
        data = json.load(f)

    output_profiles = [
        {
            "id": "default",
            "name": {
                "en": "Default Report",
                "fi": "Oletusraportti"
            },
            "description": {
                "en": "Standard default report automatically generated by the system.",
                "fi": "Järjestelmän automaattisesti generoima vakiomuotoinen raportti."
            },
            "layouts": [
                {
                    "layout_type": "automatic",
                    "title": {
                        "en": "Components",
                        "fi": "Komponentit"
                    },
                    "components": ["*"],
                    "show_text": True
                }
            ]
        },
        {
            "id": "executive_summary",
            "name": {
                "en": "Executive Summary",
                "fi": "Johdon tiivistelmä"
            },
            "description": {
                "en": "High-level overview containing key metrics and comparative radar charts.",
                "fi": "Ylätason kooste, joka sisältää keskeiset mittarit ja vertailevat tutkakaaviot."
            },
            "layouts": [
                {
                    "layout_type": "radar_3d",
                    "title": {
                        "en": "Strategic Overview",
                        "fi": "Strateginen tilannekuva"
                    },
                    "components": ["*"],
                    "show_text": False
                },
                {
                    "layout_type": "box_1d",
                    "title": {
                        "en": "Key Findings",
                        "fi": "Keskeiset havainnot"
                    },
                    "components": ["*"],
                    "show_text": True
                }
            ]
        },
        {
            "id": "deep_analysis",
            "name": {
                "en": "Deep Analysis",
                "fi": "Syväanalyysi"
            },
            "description": {
                "en": "Comprehensive analysis with all metrics, justifications, and citations.",
                "fi": "Kattava analyysi kaikkine mittareineen, perusteluineen ja lähdeviittauksineen."
            },
            "layouts": [
                {
                    "layout_type": "matrix_2d",
                    "title": {
                        "en": "Detailed Assessment",
                        "fi": "Yksityiskohtainen katsaus"
                    },
                    "components": ["matrix_toulmin", "matrix_kahneman"],
                    "show_text": True
                },
                {
                    "layout_type": "automatic",
                    "title": {
                        "en": "Other Dimensions",
                        "fi": "Muut ulottuvuudet"
                    },
                    "components": ["*"],
                    "show_text": True
                }
            ]
        }
    ]

    data["output_profiles"] = output_profiles

    with open(SEED_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"Injected {len(output_profiles)} output profiles into seed_data.json successfully.")

if __name__ == "__main__":
    inject_profiles()
