import json
from pathlib import Path

# Mock dependencies to cleanly instantiate the compiler if possible,
# or simply use the existing services if available.
import asyncio
from backend_v2.services.orchestrator.prompt_compiler import PromptCompiler

async def verify():
    SEED_DATA_PATH = Path(r"c:\src\quorum\backend_v2\seed\seed_data.json")
    with open(SEED_DATA_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Find Toulmin block
    toulmin_block = None
    for block in data.get("prompt_blocks", []):
        if block.get("id") == "blk_371c7724eeba40218409b5a3697ac1d3":
            toulmin_block = block
            break

    if not toulmin_block:
        print("Toulmin block not found.")
        return

    # We only need to test the build_dynamic_schema output context or bars_text logic.
    # The actual bars_text is built inside `build_dynamic_schema`. 
    # Let's mock a simple call.
    compiler = PromptCompiler()
    
    # We just want to see the generated `bars_text` or `final_desc`.
    # Let's extract the exact logic used in PromptCompiler for a single block to see it printed:
    
    bars_text = ""
    scales = toulmin_block.get("scales")
    print("--- EVALUATION MATRIX GENERATED BY COMPILER ---")
    if scales and isinstance(scales, list) and len(scales) > 0:
        bars_text += "\n\nEVALUATION MATRIX (BARS):\n"
        for s in scales:
            s_val = s.get("score")
            s_lbl = s.get("ai_label")
            s_claim_text = s.get("ai_description")
            
            bars_text += f"- Score {s_val}: {s_lbl} - {s_claim_text}\n"
            
    base_desc = toulmin_block.get("ai_description", "NO_BASE_DESC")
    label = compiler.resolve_i18n(toulmin_block.get("label"), "en") or "LAB"
    final_desc = f"{label}: {base_desc}{bars_text}"
    
    print(final_desc)
    print("-----------------------------------------------")

if __name__ == "__main__":
    asyncio.run(verify())
