import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:client_app/features/studio/controllers/studio_controller.dart';
import 'package:client_app/features/studio/views/model_registry_view.dart';
import 'package:client_app/utils/safe_cast.dart';
import 'package:client_app/l10n/gen/app_localizations.dart';
import 'package:client_app/core/ui/error_view.dart';
import 'package:client_app/router/router.dart';

/// **Studio Dashboard View**
///
/// Main entry point for Admin users to manage Matrices and Workflows.
/// Uses `AsyncNotifierProvider` lists generated by `StudioController`.
class StudioDashboardView extends ConsumerStatefulWidget {
  const StudioDashboardView({super.key});

  @override
  ConsumerState<StudioDashboardView> createState() =>
      _StudioDashboardViewState();
}

class _StudioDashboardViewState extends ConsumerState<StudioDashboardView>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 5, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;

    // Listen to tab changes to trigger refresh if desired
    // However, it's usually enough just to let the AsyncValue handle rebuilds.

    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          tooltip: 'Back to Application',
          onPressed: () => context.go('/dashboard'),
        ),
        title: const Text('Admin Studio V2'),
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh),
            onPressed: () {
              ref.read(promptBlocksControllerProvider.notifier).refresh();
              ref.read(workflowsControllerProvider.notifier).refresh();
            },
          ),
        ],
        bottom: TabBar(
          controller: _tabController,
          tabs: [
            Tab(
              icon: const Icon(Icons.schema),
              text: l10n.studioDashboardWorkflowsTitle,
            ),
            Tab(
              icon: const Icon(Icons.dataset),
              text: l10n.studioDashboardMatricesTitle,
            ),
            Tab(icon: const Icon(Icons.extension), text: 'Steps'),
            Tab(icon: const Icon(Icons.print), text: 'Profiles'),
            Tab(
              icon: const Icon(Icons.settings),
              text: l10n.modelRegistryTitle,
            ),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          // TAB 1: Workflows
          _buildWorkflowsTab(context, ref, l10n),

          // TAB 2: Prompt Blocks
          _buildPromptBlocksTab(context, ref, l10n),

          // TAB 3: Steps
          _buildStepsTab(context, ref, l10n),

          // TAB 4: Profiles (Tulostusprofiilit)
          _buildProfilesTab(context, ref, l10n),

          // TAB 5: Model Registry
          const ModelRegistryView(),
        ],
      ),
    );
  }

  Widget _buildProfilesTab(
    BuildContext context,
    WidgetRef ref,
    AppLocalizations l10n,
  ) {
    final workflowsState = ref.watch(workflowsControllerProvider);

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                'Tulostusprofiilit (Raportit)',
                style: Theme.of(context).textTheme.titleLarge,
              ),
            ],
          ),
          const SizedBox(height: 16),
          workflowsState.when(
            data: (workflows) {
              if (workflows.isEmpty) return const Text('No workflows defined.');
              return ListView.builder(
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                itemCount: workflows.length,
                itemBuilder: (context, index) {
                  final workflow = workflows[index];
                  // Strict De-Generator map logic
                  final profiles = SafeCast.safeMap(
                    workflow['output_profiles'],
                  );
                  final profileCount = profiles.keys.length;

                  return Card(
                    child: ListTile(
                      leading: const Icon(Icons.print, color: Colors.blueGrey),
                      title: Text(
                        (SafeCast.safeMap(workflow['name'])['translations']
                                as Map?)?['fi'] ??
                            workflow['slug']?.toString() ??
                            workflow['id']?.toString() ??
                            'Unnamed Workflow',
                        style: const TextStyle(fontWeight: FontWeight.bold),
                      ),
                      subtitle: Text('$profileCount active profiles'),
                      trailing: const Icon(Icons.edit_document),
                      onTap: () {
                        // Launch the new ProfileEditorView
                        ProfileEditorRoute(
                          workflowSlug: workflow['slug'] ?? workflow['id'],
                          $extra: workflow,
                        ).go(context);
                      },
                    ),
                  );
                },
              );
            },
            loading: () => const Center(child: CircularProgressIndicator()),
            error:
                (e, _) => ErrorView(
                  error: e,
                  compact: true,
                  onRetry:
                      () =>
                          ref
                              .read(workflowsControllerProvider.notifier)
                              .refresh(),
                ),
          ),
        ],
      ),
    );
  }

  Widget _buildWorkflowsTab(
    BuildContext context,
    WidgetRef ref,
    AppLocalizations l10n,
  ) {
    final workflowsState = ref.watch(workflowsControllerProvider);

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          _buildSectionHeader(context, l10n.studioDashboardWorkflowsTitle, () {
            const WorkflowNewRoute().go(context);
          }),
          const SizedBox(height: 16),
          workflowsState.when(
            data: (workflows) {
              if (workflows.isEmpty) return const Text('No workflows defined.');
              return ListView.builder(
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                itemCount: workflows.length,
                itemBuilder: (context, index) {
                  final workflow = workflows[index];
                  final stepCount = (workflow['steps'] as List?)?.length ?? 0;
                  final inputCount =
                      (workflow['expected_inputs'] as List?)?.length ?? 0;

                  return Card(
                    child: ListTile(
                      title: Text(
                        (SafeCast.safeMap(workflow['name'])['translations']
                                as Map?)?['fi'] ??
                            (SafeCast.safeMap(workflow['name'])['translations']
                                as Map?)?['en'] ??
                            workflow['slug']?.toString() ??
                            workflow['id']?.toString() ??
                            'Unnamed',
                        style: const TextStyle(fontWeight: FontWeight.bold),
                      ),
                      subtitle: Text(
                        l10n.workflowSubtitle(stepCount, inputCount),
                      ),
                      trailing: const Icon(Icons.chevron_right),
                      onTap: () {
                        WorkflowEditRoute(
                          slug: workflow['slug'] ?? workflow['id'],
                          $extra: workflow,
                        ).go(context);
                      },
                    ),
                  );
                },
              );
            },
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (e, _) {
              return ErrorView(
                error: e,
                compact: true,
                onRetry:
                    () =>
                        ref
                            .read(workflowsControllerProvider.notifier)
                            .refresh(),
              );
            },
          ),
        ],
      ),
    );
  }

  Widget _buildPromptBlocksTab(
    BuildContext context,
    WidgetRef ref,
    AppLocalizations l10n,
  ) {
    final promptBlocksState = ref.watch(promptBlocksControllerProvider);

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          _buildSectionHeader(context, l10n.studioDashboardMatricesTitle, () {
            const PromptBlockNewRoute().go(context);
          }),
          const SizedBox(height: 16),
          promptBlocksState.when(
            data: (promptBlocks) {
              if (promptBlocks.isEmpty)
                return const Text('No prompt blocks defined.');
              return ListView.builder(
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                itemCount: promptBlocks.length,
                itemBuilder: (context, index) {
                  final matrix = promptBlocks[index];
                  final ruleCount = (matrix['criteria'] as List?)?.length ?? 0;

                  return Card(
                    child: ListTile(
                      title: Text(matrix['id']?.toString() ?? 'Unnamed'),
                      subtitle: Text(l10n.matrixSubtitle(ruleCount)),
                      trailing: const Icon(Icons.chevron_right),
                      onTap: () {
                        PromptBlockEditRoute(
                          slug: matrix['slug'] ?? matrix['id'],
                          $extra: matrix,
                        ).go(context);
                      },
                    ),
                  );
                },
              );
            },
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (e, _) {
              return ErrorView(
                error: e,
                compact: true,
                onRetry:
                    () =>
                        ref
                            .read(promptBlocksControllerProvider.notifier)
                            .refresh(),
              );
            },
          ),
        ],
      ),
    );
  }

  Widget _buildStepsTab(
    BuildContext context,
    WidgetRef ref,
    AppLocalizations l10n,
  ) {
    final blueprintsState = ref.watch(stepsControllerProvider);

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          _buildSectionHeader(context, 'Steps', () {
            const StepNewRoute().go(context);
          }),
          const SizedBox(height: 16),
          blueprintsState.when(
            data: (blueprints) {
              if (blueprints.isEmpty) return const Text('No Steps defined.');
              return ListView.builder(
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                itemCount: blueprints.length,
                itemBuilder: (context, index) {
                  final blueprint = blueprints[index];
                  final blockCount =
                      (blueprint['prompt_blocks'] as List?)?.length ?? 0;
                  final hookCount =
                      (blueprint['pre_hooks'] as List?)?.length ?? 0;

                  return Card(
                    child: ListTile(
                      title: Text(blueprint['id']?.toString() ?? 'Unnamed'),
                      subtitle: Text('Blocks: $blockCount | Hooks: $hookCount'),
                      trailing: const Icon(Icons.chevron_right),
                      onTap: () {
                        StepEditRoute($extra: blueprint).go(context);
                      },
                    ),
                  );
                },
              );
            },
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (e, _) {
              return ErrorView(
                error: e,
                compact: true,
                onRetry:
                    () => ref.read(stepsControllerProvider.notifier).refresh(),
              );
            },
          ),
        ],
      ),
    );
  }

  Widget _buildSectionHeader(
    BuildContext context,
    String title,
    VoidCallback onAdd,
  ) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(title, style: Theme.of(context).textTheme.titleLarge),
        FilledButton.icon(
          onPressed: onAdd,
          icon: const Icon(Icons.add),
          label: const Text('New'),
        ),
      ],
    );
  }
}
