import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:client_app/features/studio/controllers/studio_controller.dart';
import 'package:client_app/features/studio/controllers/prompt_blocks_controller.dart';
import 'package:client_app/features/studio/controllers/model_registry_controller.dart';
import 'package:client_app/features/studio/views/output_profile_list_view.dart';
import 'package:client_app/features/studio/views/mcp_gateways_master_view.dart';
import 'package:client_app/features/studio/views/workflows_master_view.dart';
import 'package:client_app/l10n/gen/app_localizations.dart';
import 'package:client_app/core/ui/error_view.dart';
import 'package:client_app/core/error/app_exception.dart';
import 'package:client_app/router/router.dart';
import 'package:client_app/features/studio/views/components/clone_entity_button.dart';
import 'package:client_app/core/logging/logger_service.dart';

/// **Studio Dashboard View**
///
/// Main entry point for Admin users to manage Matrices and Workflows.
/// Uses `AsyncNotifierProvider` lists generated by `StudioController`.
class StudioDashboardView extends ConsumerStatefulWidget {
  const StudioDashboardView({super.key});

  @override
  ConsumerState<StudioDashboardView> createState() =>
      _StudioDashboardViewState();
}

class _StudioDashboardViewState extends ConsumerState<StudioDashboardView>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;

  String _getLocalizedName(dynamic entity, String currentLocale) {
    if (entity == null || entity is! Map) return 'Unknown';
    final nameVal = entity['name'] ?? entity['label'];
    if (nameVal is String) return nameVal;
    if (nameVal is Map) {
      final translations = nameVal['translations'];
      if (translations is Map) {
        if (translations[currentLocale] != null &&
            translations[currentLocale].toString().isNotEmpty) {
          return translations[currentLocale].toString();
        }
        final defaultLocale = nameVal['default_locale']?.toString() ?? 'en';
        if (translations[defaultLocale] != null &&
            translations[defaultLocale].toString().isNotEmpty) {
          return translations[defaultLocale].toString();
        }
      }
    }
    return entity['id']?.toString() ?? 'Unknown';
  }

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 7, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;

    // Listen to tab changes to trigger refresh if desired
    // However, it's usually enough just to let the AsyncValue handle rebuilds.

    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          tooltip: 'Back to Application',
          onPressed: () => context.go('/dashboard'),
        ),
        title: Text(l10n.studioViewsAdminStudioV2),
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh),
            onPressed: () {
              ref.read(promptBlocksControllerProvider.notifier).refresh();
              ref.read(workflowsControllerProvider.notifier).refresh();
            },
          ),
        ],
        bottom: TabBar(
          controller: _tabController,
          isScrollable: true,
          tabs: [
            Tab(
              icon: const Icon(Icons.schema),
              text: l10n.studioDashboardWorkflowsTitle,
            ),
            Tab(
              icon: const Icon(Icons.chat),
              text: l10n.studioViewsPromptBlocksTab,
            ),
            Tab(
              icon: const Icon(Icons.dataset),
              text: l10n.studioDashboardMatricesTitle,
            ),
            Tab(
              icon: const Icon(Icons.extension),
              text: l10n.studioViewsStepsTab,
            ),
            Tab(
              icon: const Icon(Icons.print),
              text: l10n.studioViewsProfilesTab,
            ),
            Tab(
              icon: const Icon(Icons.settings),
              text: l10n.modelRegistryTitle,
            ),
            Tab(
              icon: const Icon(Icons.hub),
              text: l10n.studioDashboardGatewaysTitle,
            ),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          // TAB 1: Workflows
          const WorkflowsMasterView(),

          // TAB 2: Regular Prompt Blocks
          _buildRegularBlocksTab(context, ref, l10n),

          // TAB 3: Matrices (BARS)
          _buildMatricesTab(context, ref, l10n),

          // TAB 4: Steps
          _buildStepsTab(context, ref, l10n),

          // TAB 5: Profiles (Tulostusprofiilit)
          _buildProfilesTab(context, ref, l10n),

          // TAB 6: Model Registry
          _buildModelRegistryTab(context, ref, l10n),

          // TAB 7: MCP Gateways
          const McpGatewaysMasterView(),
        ],
      ),
    );
  }

  Widget _buildProfilesTab(
    BuildContext context,
    WidgetRef ref,
    AppLocalizations l10n,
  ) {
    return const OutputProfileListView();
  }

  Widget _buildRegularBlocksTab(
    BuildContext context,
    WidgetRef ref,
    AppLocalizations l10n,
  ) {
    final promptBlocksState = ref.watch(promptBlocksControllerProvider);

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          _buildSectionHeader(
            context,
            l10n.studioViewsPromptBlocksStandard,
            () {
              const PromptBlockNewRoute().go(context);
            },
          ),
          const SizedBox(height: 16),
          promptBlocksState.when(
            data: (allBlocks) {
              final regularBlocks = allBlocks
                  .where((b) => b.categoryId != 'matrix')
                  .toList();
              if (regularBlocks.isEmpty)
                return Text(l10n.studioViewsNoStandardPromptBlocks);
              return ListView.builder(
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                itemCount: regularBlocks.length,
                itemBuilder: (context, index) {
                  try {
                    final block = regularBlocks[index];
                    final blockId = block.id.isNotEmpty
                        ? block.id
                        : (throw AppException.validation(
                            'PromptBlock ID is missing.',
                          ));
                    final slugStr = block.slug.isNotEmpty
                        ? block.slug
                        : (throw AppException.validation(
                            'PromptBlock slug is missing.',
                          ));
                    final blockName = block.label.get(
                      Localizations.localeOf(context).languageCode,
                    );

                    return Card(
                      child: ListTile(
                        leading: const Icon(Icons.text_snippet),
                        title: Text(
                          blockName,
                          style: const TextStyle(fontWeight: FontWeight.bold),
                        ),
                        subtitle: Text(
                          '$blockId\n${l10n.studioViewsSlugSubtitle(slugStr)}',
                        ),
                        trailing: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            CloneEntityButton(
                              onClone: () async {
                                final id = blockId;
                                await ref
                                    .read(
                                      promptBlocksControllerProvider.notifier,
                                    )
                                    .clonePromptBlock(id);
                              },
                            ),
                            const Icon(Icons.chevron_right),
                          ],
                        ),
                        onTap: () {
                          PromptBlockEditRoute(
                            id: blockId,
                            slug: slugStr,
                          ).go(context);
                        },
                      ),
                    );
                  } catch (e) {
                    ref
                        .read(loggerServiceProvider)
                        .error(
                          'Studio',
                          'Error rendering block list tile: $e',
                          e,
                        );
                    return ErrorView(error: e, compact: true);
                  }
                },
              );
            },
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (e, _) => ErrorView(
              error: e,
              compact: true,
              onRetry: () =>
                  ref.read(promptBlocksControllerProvider.notifier).refresh(),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildMatricesTab(
    BuildContext context,
    WidgetRef ref,
    AppLocalizations l10n,
  ) {
    final promptBlocksState = ref.watch(promptBlocksControllerProvider);

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          _buildSectionHeader(context, l10n.studioDashboardMatricesTitle, () {
            // Future UI feature: Pre-fill category_id = 'matrix'
            const PromptBlockNewRoute().go(context);
          }),
          const SizedBox(height: 16),
          promptBlocksState.when(
            data: (allBlocks) {
              final matrices = allBlocks
                  .where((b) => b.categoryId == 'matrix')
                  .toList();
              if (matrices.isEmpty)
                return Text(l10n.studioViewsNoMatricesDefined);
              return ListView.builder(
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                itemCount: matrices.length,
                itemBuilder: (context, index) {
                  try {
                    final matrix = matrices[index];
                    final matrixId = matrix.id.isNotEmpty
                        ? matrix.id
                        : (throw AppException.validation(
                            'Matrix data is corrupted: missing ID.',
                          ));
                    final slugStr = matrix.slug.isNotEmpty
                        ? matrix.slug
                        : (throw AppException.validation(
                            'Matrix slug is missing.',
                          ));

                    // NO HARDCODING MANDATE: Read 'scales', default to empty if null.
                    final scalesList = matrix.scales;
                    final ruleCount = scalesList?.length ?? 0;
                    final matrixName = matrix.label.get(
                      Localizations.localeOf(context).languageCode,
                    );

                    return Card(
                      child: ListTile(
                        leading: const Icon(Icons.grid_on),
                        title: Text(
                          matrixName,
                          style: const TextStyle(fontWeight: FontWeight.bold),
                        ),
                        subtitle: Text(
                          '$matrixId\n${l10n.matrixSubtitle(ruleCount)}',
                        ),
                        trailing: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            CloneEntityButton(
                              onClone: () async {
                                final id = matrixId;
                                await ref
                                    .read(
                                      promptBlocksControllerProvider.notifier,
                                    )
                                    .clonePromptBlock(id);
                              },
                            ),
                            const Icon(Icons.chevron_right),
                          ],
                        ),
                        onTap: () {
                          PromptBlockEditRoute(
                            id: matrixId,
                            slug: slugStr,
                          ).go(context);
                        },
                      ),
                    );
                  } catch (e) {
                    ref
                        .read(loggerServiceProvider)
                        .error(
                          'Studio',
                          'Error rendering matrix list tile: $e',
                          e,
                        );
                    return ErrorView(error: e, compact: true);
                  }
                },
              );
            },
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (e, _) => ErrorView(
              error: e,
              compact: true,
              onRetry: () =>
                  ref.read(promptBlocksControllerProvider.notifier).refresh(),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildStepsTab(
    BuildContext context,
    WidgetRef ref,
    AppLocalizations l10n,
  ) {
    // ... Existing implementation of Steps Tab ...
    final blueprintsState = ref.watch(stepsControllerProvider);

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          _buildSectionHeader(context, l10n.studioViewsStepsTab, () {
            const StepNewRoute().go(context);
          }),
          const SizedBox(height: 16),
          blueprintsState.when(
            data: (blueprints) {
              if (blueprints.isEmpty)
                return Text(l10n.studioViewsNoStepsDefined);
              return ListView.builder(
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                itemCount: blueprints.length,
                itemBuilder: (context, index) {
                  try {
                    final blueprint = blueprints[index];
                    final blueprintId = blueprint['id']?.toString();
                    if (blueprintId == null) {
                      throw AppException.validation(
                        'Blueprint step is corrupted: missing ID.',
                      );
                    }
                    final blocks = blueprint['prompt_blocks'] as List?;
                    if (blocks == null) {
                      throw AppException.validation(
                        'Blueprint prompt_blocks is missing for ID: $blueprintId',
                      );
                    }
                    final hooks = blueprint['pre_hooks'] as List?;
                    if (hooks == null) {
                      throw AppException.validation(
                        'Blueprint pre_hooks is missing for ID: $blueprintId',
                      );
                    }
                    final blockCount = blocks.length;
                    final hookCount = hooks.length;
                    final stepName = _getLocalizedName(
                      blueprint,
                      Localizations.localeOf(context).languageCode,
                    );

                    return Card(
                      child: ListTile(
                        title: Text(
                          stepName,
                          style: const TextStyle(fontWeight: FontWeight.bold),
                        ),
                        subtitle: Text(
                          '$blueprintId\n${l10n.studioViewsSlugSubtitle(blueprint['slug']?.toString() ?? '')}\n${l10n.studioViewsStepsSubtitle(blockCount, hookCount)}',
                        ),
                        trailing: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            CloneEntityButton(
                              onClone: () async {
                                final id = blueprintId;
                                await ref
                                    .read(stepsControllerProvider.notifier)
                                    .cloneStep(id);
                              },
                            ),
                            const Icon(Icons.chevron_right),
                          ],
                        ),
                        onTap: () {
                          StepEditRoute($extra: blueprint).go(context);
                        },
                      ),
                    );
                  } catch (e) {
                    ref
                        .read(loggerServiceProvider)
                        .error(
                          'Studio',
                          'Error rendering step list tile: $e',
                          e,
                        );
                    return ErrorView(error: e, compact: true);
                  }
                },
              );
            },
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (e, _) {
              return ErrorView(
                error: e,
                compact: true,
                onRetry: () =>
                    ref.read(stepsControllerProvider.notifier).refresh(),
              );
            },
          ),
        ],
      ),
    );
  }

  Widget _buildModelRegistryTab(
    BuildContext context,
    WidgetRef ref,
    AppLocalizations l10n,
  ) {
    final registryState = ref.watch(modelRegistryControllerProvider);

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          _buildSectionHeader(context, l10n.modelRegistryTitle, () {
            const ModelRegistryNewRoute().go(context);
          }),
          const SizedBox(height: 16),
          registryState.when(
            data: (configs) {
              if (configs.isEmpty) return Text(l10n.studioViewsNoSystemConfigs);
              return ListView.builder(
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                itemCount: configs.length,
                itemBuilder: (context, index) {
                  try {
                    final config = configs[index];
                    final configId = config['id']?.toString();
                    if (configId == null) {
                      throw AppException.validation(
                        'Model Registry config is missing ID.',
                      );
                    }
                    final modelsMap = config['models'] as Map?;
                    if (modelsMap == null) {
                      throw AppException.validation(
                        'Model Registry models object is missing for ID: $configId',
                      );
                    }
                    final modelCount = modelsMap.length;

                    return Card(
                      child: ListTile(
                        title: Text(configId),
                        subtitle: Text(
                          l10n.studioViewsConfiguredModels(modelCount),
                        ),
                        trailing: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            CloneEntityButton(
                              onClone: () async {
                                final id = configId;
                                await ref
                                    .read(
                                      modelRegistryControllerProvider.notifier,
                                    )
                                    .cloneConfig(id);
                              },
                            ),
                            const Icon(Icons.chevron_right),
                          ],
                        ),
                        onTap: () {
                          ModelRegistryEditRoute(
                            id: configId,
                            $extra: config,
                          ).go(context);
                        },
                      ),
                    );
                  } catch (e) {
                    ref
                        .read(loggerServiceProvider)
                        .error(
                          'Studio',
                          'Error rendering config list tile: $e',
                          e,
                        );
                    return ErrorView(error: e, compact: true);
                  }
                },
              );
            },
            loading: () => const Center(child: CircularProgressIndicator()),
            error: (e, _) {
              return ErrorView(
                error: e,
                compact: true,
                onRetry: () => ref
                    .read(modelRegistryControllerProvider.notifier)
                    .refresh(),
              );
            },
          ),
        ],
      ),
    );
  }

  Widget _buildSectionHeader(
    BuildContext context,
    String title,
    VoidCallback onAdd,
  ) {
    final l10n = AppLocalizations.of(context)!;
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(title, style: Theme.of(context).textTheme.titleLarge),
        FilledButton.icon(
          onPressed: onAdd,
          icon: const Icon(Icons.add),
          label: Text(l10n.studioViewsNewBtn),
        ),
      ],
    );
  }
}
