include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - unawaited_futures
    - avoid_dynamic_calls
    - throw_in_finally
    - always_use_package_imports
    - comment_references
    - secure_pubspec_urls
