name: client_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core State Management & Routing
  flutter_riverpod: ^3.0.0
  riverpod_annotation: any
  go_router: ^17.0.1
  fpdart: ^1.1.0

  # Connectivity & Data
  dio: any
  json_annotation: any
  freezed_annotation: any
  flutter_dotenv: any

  # Firebase
  firebase_core: any
  firebase_auth: ^6.1.3
  firebase_ui_auth: any
  firebase_ui_localizations: any

  # UI & UX
  flutter_localizations:
    sdk: flutter
  intl: any
  flex_color_scheme: any
  flutter_animate: any
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  flutter_markdown: ^0.7.7+1
  file_picker: ^10.3.8
  collection: ^1.19.1
  fl_chart: ^1.1.1
  pdf: ^3.11.3
  printing: ^5.14.2
  file_saver: ^0.3.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Dev Tools & Code Generation
  build_runner: ^2.10.4
  riverpod_generator: any
  custom_lint: any
  riverpod_lint: any
  json_serializable: any
  freezed: any
  flutter_lints: any
  mocktail: ^1.0.4
  mockito: ^5.6.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
