name: client_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core State Management & Routing
  flutter_riverpod:
  riverpod:
  riverpod_annotation:
  go_router:
  fpdart:

  # Connectivity & Data
  dio:
  json_annotation:
  freezed_annotation:
  flutter_dotenv:

  # Firebase
  firebase_core:
  firebase_auth:
  firebase_ui_auth:
  firebase_ui_localizations:

  # UI & UX
  flutter_localizations:
    sdk: flutter
  intl:
  flex_color_scheme:
  flutter_animate:
  google_fonts:
  shared_preferences:
  flutter_markdown_plus:
  file_picker:
  collection:
  fl_chart:
  pdf:
  printing:
  file_saver:
  url_launcher:
  flutter_hooks:
  hooks_riverpod:
  logger:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Dev Tools & Code Generation
  build_runner:
  riverpod_generator:
  custom_lint:
  riverpod_lint:
  json_serializable:
  freezed:
  flutter_lints:
  mocktail:
  mockito:
  go_router_builder:

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
