"""Large Language Model (LLM) Integration Schemas.

This module defines the standardized response structures for interacting with
various LLM providers (Google Gemini, OpenAI, etc.), including support for
advanced reasoning tokens and tool calls.
"""

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class LLMResponse(BaseModel):
    """Unified response wrapper for all LLM providers (Gemini 3, GPT-5.1, etc.).

    Supports advanced features like 'Meaning Tokens' (Thought Signature / Reasoning Blob).

    Attributes:
        content (str): The primary text content generated by the model.
        reasoning_token (Optional[str]): Encrypted Blob representing the model's internal reasoning state.
        tool_calls (Optional[list[dict]]): List of tool use requests invoked by the model.
        token_usage (dict): Token usage statistics (prompt, completion, total).
        provider_metadata (dict): Provider-specific raw metadata (e.g. finish_reason).
    """

    model_config = ConfigDict(extra="ignore")

    content: Annotated[str, Field(description="The primary text content generated by the model.")]
    parsed_content: Annotated[
        Any | None,
        Field(default=None, description="Pre-parsed structured data (Dict or Pydantic Model) from the provider."),
    ]
    reasoning_token: Annotated[
        str | None,
        Field(
            default=None,
            description=(
                "Encrypted Blob representing the model's internal reasoning state "
                "(e.g. Gemini 'thought_signature' or OpenAI 'reasoning_blob'). "
                "Must be passed back to continue the thought process."
            ),
        ),
    ]
    tool_calls: Annotated[
        list[dict[str, Any]] | None,
        Field(default=None, description="List of tool use requests invoked by the model."),
    ]
    token_usage: Annotated[
        dict[str, float | int],
        Field(default_factory=dict, description="Token usage statistics (prompt, completion, total, cost)."),
    ]
    messages: Annotated[
        list[dict[str, str]] | None,
        Field(default=None, description="The full list of messages (prompts) sent to the model for audit purposes."),
    ]
    override_reason: Annotated[str | None, Field(default=None, description="Reason for override if applicable.")] = None

    model_config = ConfigDict(extra="ignore", strict=True)

    @field_validator("content")
    @classmethod
    def validate_non_empty(cls, v: str) -> str:
        # Content *can* be empty if only tool_calls are returned?
        # Provider dependent. But typically we want content.
        # Let's enforce non-empty string for now, but allow whitespace? No.
        # Actually, sometimes models return empty content with tool calls.
        # We should probably allow empty if tool_calls is present but that requires model validation.
        # For simple field validation, let's just strip.
        return v if v is None else v # It is not optional in schema.



class LLMProviderConfig(BaseModel):
    """Configuration for an LLM Provider."""

    model_config = ConfigDict(extra="ignore", strict=True)

    id: Annotated[
        str,
        Field(..., description="Configuration ID (unique key).", json_schema_extra={"x-ui-hidden": True}),
    ]
    provider: Annotated[
        str,
        Field(
            ..., description="Provider type (e.g. 'openai', 'vertex_ai').", json_schema_extra={"x-ui-label": "Provider"}
        ),
    ]
    model_name: Annotated[
        str,
        Field(
            ...,
            description="Model identifier (e.g. 'gpt-4', 'gemini-pro').",
            json_schema_extra={"x-ui-label": "Model Name"},
        ),
    ]
    api_key: Annotated[
        str | None,
        Field(default=None, description="API Key (masked on read).", json_schema_extra={"x-ui-label": "API Key"}),
    ]
    base_url: Annotated[
        str | None,
        Field(default=None, description="Base URL for API calls.", json_schema_extra={"x-ui-label": "Base URL"}),
    ]
    temperature: Annotated[
        float,
        Field(
            default=0.7,
            ge=0.0,
            le=2.0,
            description="Sampling temperature.",
            json_schema_extra={"x-ui-label": "Temperature"},
        ),
    ]
    additional_params: Annotated[
        dict[str, Any], Field(default_factory=dict, description="Additional provider-specific parameters.")
    ]

    @field_validator("id", "provider", "model_name")
    @classmethod
    def validate_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Field cannot be empty or whitespace only.")
        return v.strip()


class AdHocTestRequest(BaseModel):
    """Request payload for ephemeral LLM testing."""

    model_config = ConfigDict(extra="ignore", strict=True)

    provider: Annotated[str, Field(..., description="Provider identifier.")]
    api_key: Annotated[str | None, Field(default=None, description="Optional API key for testing.")]
    system_instruction: Annotated[str, Field(..., description="System prompt.")]
    user_prompt: Annotated[str, Field(..., description="User prompt.")]
    model_params: Annotated[dict[str, Any], Field(default_factory=dict, description="Model parameters override.")]

    @field_validator("provider", "system_instruction", "user_prompt")
    @classmethod
    def validate_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Field cannot be empty or whitespace only.")
        return v.strip()


class AdHocTestResponse(BaseModel):
    """Response for ephemeral LLM testing."""

    content: Annotated[str, Field(..., description="Generated content.")]
    latency_ms: Annotated[float, Field(..., description="Execution latency in milliseconds.")]
    status: Annotated[str, Field(..., description="Status string (e.g. 'success', 'error').")]

    model_config = ConfigDict(extra="ignore", strict=True)

    @field_validator("content", "status")
    @classmethod
    def validate_non_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Field cannot be empty or whitespace only.")
        return v.strip()

    @field_validator("latency_ms")
    @classmethod
    def validate_non_negative(cls, v: float) -> float:
        if v < 0:
            raise ValueError("Latency cannot be negative.")
        return v
