"""Large Language Model (LLM) Integration Schemas.

This module defines the standardized response structures for interacting with
various LLM providers (Google Gemini, OpenAI, etc.), including support for
advanced reasoning tokens and tool calls.
"""

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class LLMResponse(BaseModel):
    """Unified response wrapper for all LLM providers (Gemini 3, GPT-5.1, etc.).

    Supports advanced features like 'Meaning Tokens' (Thought Signature / Reasoning Blob).

    Attributes:
        content (str): The primary text content generated by the model.
        reasoning_token (Optional[str]): Encrypted Blob representing the model's internal reasoning state.
        tool_calls (Optional[list[dict]]): List of tool use requests invoked by the model.
        token_usage (dict): Token usage statistics (prompt, completion, total).
        provider_metadata (dict): Provider-specific raw metadata (e.g. finish_reason).
    """

    model_config = ConfigDict(extra="ignore")

    content: Annotated[str, Field(description="The primary text content generated by the model.")]
    reasoning_token: Annotated[
        str | None,
        Field(
            default=None,
            description=(
                "Encrypted Blob representing the model's internal reasoning state "
                "(e.g. Gemini 'thought_signature' or OpenAI 'reasoning_blob'). "
                "Must be passed back to continue the thought process."
            ),
        ),
    ]
    tool_calls: Annotated[
        list[dict[str, Any]] | None,
        Field(default=None, description="List of tool use requests invoked by the model."),
    ]
    token_usage: Annotated[
        dict[str, float | int],
        Field(default_factory=dict, description="Token usage statistics (prompt, completion, total, cost)."),
    ]
    provider_metadata: Annotated[
        dict[str, Any],
        Field(default_factory=dict, description="Provider-specific raw metadata (e.g. finish_reason, safety_ratings)."),
    ]
