// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLTjI14E-8hulSeViyuAi8wfoEC7ZiZ6g',
    appId: '1:943560988580:web:c1bf9fa0f6d043b52bd331',
    messagingSenderId: '943560988580',
    projectId: 'cognitive-quorum',
    authDomain: 'cognitive-quorum.firebaseapp.com',
    storageBucket: 'cognitive-quorum.firebasestorage.app',
    measurementId: 'G-YZ7DW2WZ4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXrTJjN_6pL2EEitrpz9mmUf4x1wNGS6M',
    appId: '1:943560988580:android:38e86c519d5beb7e2bd331',
    messagingSenderId: '943560988580',
    projectId: 'cognitive-quorum',
    storageBucket: 'cognitive-quorum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfdSKEFY_N6aShobDJIwOCiys3mCZU39w',
    appId: '1:943560988580:ios:3f046d943129016b2bd331',
    messagingSenderId: '943560988580',
    projectId: 'cognitive-quorum',
    storageBucket: 'cognitive-quorum.firebasestorage.app',
    iosBundleId: 'com.launis.quorum.clientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfdSKEFY_N6aShobDJIwOCiys3mCZU39w',
    appId: '1:943560988580:ios:3f046d943129016b2bd331',
    messagingSenderId: '943560988580',
    projectId: 'cognitive-quorum',
    storageBucket: 'cognitive-quorum.firebasestorage.app',
    iosBundleId: 'com.launis.quorum.clientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLTjI14E-8hulSeViyuAi8wfoEC7ZiZ6g',
    appId: '1:943560988580:web:04a76056658c5d1d2bd331',
    messagingSenderId: '943560988580',
    projectId: 'cognitive-quorum',
    authDomain: 'cognitive-quorum.firebaseapp.com',
    storageBucket: 'cognitive-quorum.firebasestorage.app',
    measurementId: 'G-YPPH6GDFJS',
  );
}
