import 'package:flutter/material.dart';
import 'package:client_app/l10n/gen/app_localizations.dart';
import 'package:client_app/features/studio/models/workflow.dart';
import 'package:client_app/shared/models/i18n_text.dart';

/// **WorkflowStepCard**
///
/// Componentized UI widget representing a single execution step node
/// inside the workflow builder. Enforces the Opaque Stripe ID mandate
/// by keeping the ID completely un-editable and auto-generated by the parent.
class WorkflowStepCard extends StatelessWidget {
  final int index;
  final StepRule stepDef;
  final List<NodeStrategy> blueprints;
  final List<StepRule> allSteps;
  final List<Map<String, dynamic>> mcpGateways;
  final List<ExpectedInput> globalWorkflowInputs;
  final AppLocalizations l10n;
  final Function(StepRule) onChanged;
  final VoidCallback onDelete;

  const WorkflowStepCard({
    super.key,
    required this.index,
    required this.stepDef,
    required this.blueprints,
    required this.allSteps,
    required this.mcpGateways,
    required this.globalWorkflowInputs,
    required this.l10n,
    required this.onChanged,
    required this.onDelete,
  });

  @override
  Widget build(BuildContext context) {
    final stepIdStr = stepDef.id;

    final previousSteps = allSteps
        .map((s) => s.id)
        .where((id) => id.isNotEmpty && id != stepIdStr)
        .toList();

    final dependsOn = List<String>.from(stepDef.dependsOn);
    final mappings = Map<String, String>.from(stepDef.inputMappings);

    String getBlueprintLabel(String stepId) {
      if (stepId.isEmpty) return '';
      final bp = blueprints.firstWhere(
        (b) => b.id == stepId,
        orElse: () => const NodeStrategy.logic(
          id: '',
          slug: '',
          hook: '',
          name: I18nText(defaultLocale: 'en'),
        ), // Fallback dummy
      );
      if (bp.id.isNotEmpty) {
        final fiStr = bp.name.translations['fi'] ?? '';
        final enStr = bp.name.translations['en'] ?? '';
        return fiStr.isNotEmpty ? fiStr : enStr;
      }
      return stepId;
    }

    void update(StepRule updated) {
      onChanged(updated);
    }

    return Card(
      margin: const EdgeInsets.only(bottom: 16),
      elevation: 2,
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  l10n.studioWorkflowStepCount(index + 1),
                  style: const TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 16,
                  ),
                ),
                IconButton(
                  icon: Icon(
                    Icons.delete,
                    color: Theme.of(context).colorScheme.error,
                  ),
                  onPressed: onDelete,
                ),
              ],
            ),
            const Divider(),

            Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        l10n.studioWorkflowNodeIdOpaque,
                        style: TextStyle(
                          fontSize: 12,
                          color: Theme.of(context).colorScheme.onSurfaceVariant,
                        ),
                      ),
                      const SizedBox(height: 4),
                      SelectableText(
                        stepIdStr,
                        style: const TextStyle(
                          fontFamily: 'monospace',
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: DropdownButtonFormField<String>(
                    decoration: InputDecoration(
                      labelText: l10n.studioWorkflowTaskBlueprint,
                    ),
                    initialValue:
                        blueprints.any((bp) => bp.id == stepDef.taskBlueprint)
                        ? stepDef.taskBlueprint
                        : null,
                    items: blueprints.map((bp) {
                      final label = getBlueprintLabel(bp.id);
                      return DropdownMenuItem(value: bp.id, child: Text(label));
                    }).toList(),
                    onChanged: (val) {
                      if (val != null) {
                        update(stepDef.copyWith(taskBlueprint: val));
                      }
                    },
                  ),
                ),
              ],
            ),

            const SizedBox(height: 16),
            Text(
              l10n.studioWorkflowDependsOn,
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 8),
            if (previousSteps.isEmpty)
              Text(
                l10n.studioWorkflowNoDependencies,
                style: TextStyle(
                  color: Theme.of(context).colorScheme.onSurfaceVariant,
                ),
              )
            else
              Wrap(
                spacing: 8,
                children: previousSteps.map((prevId) {
                  final isSelected = dependsOn.contains(prevId);

                  // Extract human-readable label for dependency chip
                  String displayLabel = prevId;
                  final matchingNode = allSteps
                      .where((s) => s.id == prevId)
                      .firstOrNull;
                  if (matchingNode != null &&
                      matchingNode.taskBlueprint.isNotEmpty) {
                    final readableName = getBlueprintLabel(
                      matchingNode.taskBlueprint,
                    );
                    displayLabel =
                        readableName.isNotEmpty &&
                            readableName != matchingNode.taskBlueprint
                        ? readableName
                        : prevId.length > 15
                        ? '${prevId.substring(0, 15)}...'
                        : prevId;
                  }

                  return FilterChip(
                    label: Text(displayLabel),
                    selected: isSelected,
                    onSelected: (bool selected) {
                      final newDependsOn = List<String>.from(dependsOn);
                      if (selected) {
                        if (!newDependsOn.contains(prevId)) {
                          newDependsOn.add(prevId);
                        }
                      } else {
                        newDependsOn.remove(prevId);
                      }
                      update(stepDef.copyWith(dependsOn: newDependsOn));
                    },
                  );
                }).toList(),
              ),

            const SizedBox(height: 16),
            Text(
              l10n.studioWorkflowInputMappings,
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
            ...(() {
              final List<Widget> checkboxes = [];

              // 1. Global Inputs
              for (final ei in globalWorkflowInputs) {
                final targetKey = ei.inputKey;
                final sourceValue = r'$inputs.' + ei.inputKey;
                final isSemanticMapped =
                    mappings.containsValue(sourceValue) &&
                    mappings[targetKey] != sourceValue;
                final isSelected =
                    mappings[targetKey] == sourceValue || isSemanticMapped;
                final isReadOnly = isSemanticMapped;
                final labelText = ei.label.get(l10n.localeName);

                checkboxes.add(
                  CheckboxListTile(
                    title: Text('Syöte: $labelText'),
                    subtitle: Text(sourceValue),
                    value: isSelected,
                    onChanged: isReadOnly
                        ? null
                        : (bool? checked) {
                            final newMappings = Map<String, String>.from(
                              mappings,
                            );
                            if (checked == true) {
                              newMappings[targetKey] = sourceValue;
                            } else {
                              newMappings.remove(targetKey);
                            }
                            update(
                              stepDef.copyWith(inputMappings: newMappings),
                            );
                          },
                    controlAffinity: ListTileControlAffinity.leading,
                    dense: true,
                  ),
                );
              }

              // 2. Depends On Steps
              for (final prevId in dependsOn) {
                final targetKey = prevId;
                final sourceValue = r'$steps.' + prevId;
                final isSemanticMapped =
                    mappings.containsValue(sourceValue) &&
                    mappings[targetKey] != sourceValue;
                final isGlobalStepsMapped = mappings.containsValue(r'$steps');
                final isSelected =
                    mappings[targetKey] == sourceValue ||
                    isSemanticMapped ||
                    isGlobalStepsMapped;
                final isReadOnly = isSemanticMapped || isGlobalStepsMapped;

                final matchingNode = allSteps
                    .where((s) => s.id == prevId)
                    .firstOrNull;
                String labelStr = prevId;
                if (matchingNode != null &&
                    matchingNode.taskBlueprint.isNotEmpty) {
                  labelStr = getBlueprintLabel(matchingNode.taskBlueprint);
                }
                if (labelStr.isEmpty) {
                  labelStr = prevId.length > 15
                      ? '${prevId.substring(0, 15)}...'
                      : prevId;
                }

                checkboxes.add(
                  CheckboxListTile(
                    title: Text('Askel: $labelStr'),
                    subtitle: Text(sourceValue),
                    value: isSelected,
                    onChanged: isReadOnly
                        ? null
                        : (bool? checked) {
                            final newMappings = Map<String, String>.from(
                              mappings,
                            );
                            if (checked == true) {
                              newMappings[targetKey] = sourceValue;
                            } else {
                              newMappings.remove(targetKey);
                            }
                            update(
                              stepDef.copyWith(inputMappings: newMappings),
                            );
                          },
                    controlAffinity: ListTileControlAffinity.leading,
                    dense: true,
                  ),
                );
              }

              if (checkboxes.isEmpty) {
                return [
                  Padding(
                    padding: const EdgeInsets.symmetric(vertical: 8.0),
                    child: Text(
                      'Ei valittavia syötteitä tai riippuvuuksia.',
                      style: TextStyle(
                        color: Theme.of(context).colorScheme.onSurfaceVariant,
                      ),
                    ),
                  ),
                ];
              }

              return [
                Container(
                  decoration: BoxDecoration(
                    border: Border.all(
                      color: Theme.of(context).colorScheme.outlineVariant,
                    ),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Column(children: checkboxes),
                ),
              ];
            })(),
          ],
        ),
      ),
    );
  }
}
