import 'package:flutter/material.dart';
import 'package:client_app/l10n/gen/app_localizations.dart';
import '../../../../../utils/safe_cast.dart';

/// **WorkflowStepCard**
///
/// Componentized UI widget representing a single execution step node
/// inside the workflow builder. Enforces the Opaque Stripe ID mandate
/// by keeping the ID completely un-editable and auto-generated by the parent.
class WorkflowStepCard extends StatelessWidget {
  final int index;
  final Map<String, dynamic> stepDef;
  final List<Map<String, dynamic>> blueprints;
  final List<Map<String, dynamic>> allSteps;
  final List<Map<String, dynamic>> mcpGateways;
  final AppLocalizations l10n;
  final VoidCallback onChanged;
  final VoidCallback onDelete;

  const WorkflowStepCard({
    super.key,
    required this.index,
    required this.stepDef,
    required this.blueprints,
    required this.allSteps,
    required this.mcpGateways,
    required this.l10n,
    required this.onChanged,
    required this.onDelete,
  });

  @override
  Widget build(BuildContext context) {
    final stepIdController = TextEditingController(
      text: SafeCast.safeString(stepDef['id'] ?? stepDef['step_id']),
    );

    final previousSteps =
        allSteps
            .map((s) => SafeCast.safeString(s['id'] ?? s['step_id']))
            .where((id) => id.isNotEmpty && id != stepIdController.text)
            .toList();

    final dependsOn =
        SafeCast.safeList(
          stepDef['depends_on'],
        ).map((e) => e.toString()).toList();

    final mappings = SafeCast.safeMap(
      stepDef['input_mappings'],
    ).map((k, v) => MapEntry(k.toString(), v.toString()));

    final allowedMcpTools =
        SafeCast.safeList(
          stepDef['allowed_mcp_tools'],
        ).map((e) => e.toString()).toList();

    return Card(
      margin: const EdgeInsets.only(bottom: 16),
      elevation: 2,
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  'Step ${index + 1}',
                  style: const TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 16,
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.delete, color: Colors.red),
                  onPressed: onDelete,
                ),
              ],
            ),
            const Divider(),

            Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        'Node ID (Opaque Stripe Pattern)',
                        style: TextStyle(fontSize: 12, color: Colors.grey),
                      ),
                      const SizedBox(height: 4),
                      SelectableText(
                        stepIdController.text,
                        style: const TextStyle(
                          fontFamily: 'monospace',
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: DropdownButtonFormField<String>(
                    decoration: const InputDecoration(
                      labelText: 'Task Blueprint (Cognitive Engine)',
                    ),
                    initialValue:
                        blueprints.any(
                              (bp) => bp['slug'] == stepDef['task_blueprint'],
                            )
                            ? stepDef['task_blueprint'] as String?
                            : null,
                    items:
                        blueprints.map((bp) {
                          final slug = SafeCast.safeString(bp['slug']);
                          final nameMap = SafeCast.safeMap(bp['name']);
                          final enName = SafeCast.safeString(nameMap['en']);
                          final label = enName.isNotEmpty ? enName : slug;
                          return DropdownMenuItem(
                            value: slug,
                            child: Text(label),
                          );
                        }).toList(),
                    onChanged: (val) {
                      stepDef['task_blueprint'] = val;
                      onChanged();
                    },
                  ),
                ),
              ],
            ),

            const SizedBox(height: 16),
            const Text(
              'XAI Reporting / Toolkit Injection (MCP Gateways):',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 8),
            Wrap(
              spacing: 8,
              children:
                  mcpGateways.map((toolMap) {
                    final slug = SafeCast.safeString(toolMap['slug']);
                    final isSelected = allowedMcpTools.contains(slug);
                    return FilterChip(
                      label: Text(slug),
                      selected: isSelected,
                      onSelected: (bool selected) {
                        if (selected) {
                          if (!allowedMcpTools.contains(slug)) {
                            allowedMcpTools.add(slug);
                          }
                        } else {
                          allowedMcpTools.remove(slug);
                        }
                        stepDef['allowed_mcp_tools'] = allowedMcpTools;
                        onChanged();
                      },
                    );
                  }).toList(),
            ),

            const SizedBox(height: 16),
            const Text(
              'Depends On (Executes AFTER these steps finish):',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 8),
            if (previousSteps.isEmpty)
              const Text(
                'No previous steps available to depend on.',
                style: TextStyle(color: Colors.grey),
              )
            else
              Wrap(
                spacing: 8,
                children:
                    previousSteps.map((prevId) {
                      final isSelected = dependsOn.contains(prevId);
                      return FilterChip(
                        label: Text(prevId),
                        selected: isSelected,
                        onSelected: (bool selected) {
                          if (selected) {
                            if (!dependsOn.contains(prevId)) {
                              dependsOn.add(prevId);
                            }
                          } else {
                            dependsOn.remove(prevId);
                          }
                          stepDef['depends_on'] = dependsOn;
                          onChanged();
                        },
                      );
                    }).toList(),
              ),

            const SizedBox(height: 16),
            const Text(
              'Input Mappings (State Data Injection):',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            ...mappings.entries.map((m) {
              return Padding(
                padding: const EdgeInsets.only(top: 8.0, bottom: 4.0),
                child: Row(
                  children: [
                    Expanded(
                      flex: 2,
                      child: TextFormField(
                        initialValue: m.key,
                        decoration: const InputDecoration(
                          labelText: 'Target Arg Name',
                          isDense: true,
                        ),
                        onChanged: (newKey) {
                          final val = mappings[m.key];
                          mappings.remove(m.key);
                          mappings[newKey] = val ?? '';
                          stepDef['input_mappings'] = mappings;
                          onChanged();
                        },
                      ),
                    ),
                    const Padding(
                      padding: EdgeInsets.symmetric(horizontal: 8.0),
                      child: Icon(Icons.arrow_forward),
                    ),
                    Expanded(
                      flex: 3,
                      child: TextFormField(
                        initialValue: m.value,
                        decoration: const InputDecoration(
                          labelText: 'Source Token (e.g. \$inputs, step_1)',
                          isDense: true,
                        ),
                        onChanged: (newVal) {
                          mappings[m.key] = newVal;
                          stepDef['input_mappings'] = mappings;
                          onChanged();
                        },
                      ),
                    ),
                    IconButton(
                      icon: const Icon(Icons.remove_circle, color: Colors.grey),
                      onPressed: () {
                        mappings.remove(m.key);
                        stepDef['input_mappings'] = mappings;
                        onChanged();
                      },
                    ),
                  ],
                ),
              );
            }),
            const SizedBox(height: 8),
            Align(
              alignment: Alignment.centerLeft,
              child: TextButton.icon(
                icon: const Icon(Icons.add_link),
                label: const Text('Add Mapping'),
                onPressed: () {
                  mappings['new_arg_${mappings.length}'] = '';
                  stepDef['input_mappings'] = mappings;
                  onChanged();
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
