import 'package:flutter/material.dart';
import 'package:client_app/l10n/gen/app_localizations.dart';
import '../../../../../utils/safe_cast.dart';

/// **WorkflowStepCard**
///
/// Componentized UI widget representing a single execution step node
/// inside the workflow builder. Enforces the Opaque Stripe ID mandate
/// by keeping the ID completely un-editable and auto-generated by the parent.
class WorkflowStepCard extends StatelessWidget {
  final int index;
  final Map<String, dynamic> stepDef;
  final List<Map<String, dynamic>> blueprints;
  final List<Map<String, dynamic>> allSteps;
  final List<Map<String, dynamic>> mcpGateways;
  final AppLocalizations l10n;
  final VoidCallback onChanged;
  final VoidCallback onDelete;

  const WorkflowStepCard({
    super.key,
    required this.index,
    required this.stepDef,
    required this.blueprints,
    required this.allSteps,
    required this.mcpGateways,
    required this.l10n,
    required this.onChanged,
    required this.onDelete,
  });

  @override
  Widget build(BuildContext context) {
    final stepIdController = TextEditingController(
      text: SafeCast.safeString(stepDef['id'] ?? stepDef['step_id']),
    );

    final previousSteps = allSteps
        .map((s) => SafeCast.safeString(s['id'] ?? s['step_id']))
        .where((id) => id.isNotEmpty && id != stepIdController.text)
        .toList();

    final dependsOn = SafeCast.safeList(
      stepDef['depends_on'],
    ).map((e) => e.toString()).toList();

    final mappings = SafeCast.safeMap(
      stepDef['input_mappings'],
    ).map((k, v) => MapEntry(k.toString(), v.toString()));

    final allowedMcpTools = SafeCast.safeList(
      stepDef['allowed_mcp_tools'],
    ).map((e) => e.toString()).toList();

    String extractName(dynamic nameObj) {
      if (nameObj is String && nameObj.isNotEmpty) return nameObj;
      final map = SafeCast.safeMap(nameObj);
      if (map.containsKey('translations')) {
        final translations = SafeCast.safeMap(map['translations']);
        final fiStr = SafeCast.safeString(translations['fi']);
        final enStr = SafeCast.safeString(translations['en']);
        return fiStr.isNotEmpty ? fiStr : enStr;
      }
      final legacyFi = SafeCast.safeString(map['fi']);
      final legacyEn = SafeCast.safeString(map['en']);
      return legacyFi.isNotEmpty ? legacyFi : legacyEn;
    }

    String getBlueprintLabel(String stepId) {
      if (stepId.isEmpty) return '';
      final bp = blueprints.firstWhere(
        (b) => SafeCast.safeString(b['id']) == stepId,
        orElse: () => <String, dynamic>{},
      );
      if (bp.isNotEmpty) {
        final nameStr = extractName(bp['name']);
        return nameStr.isNotEmpty ? nameStr : stepId;
      }
      return stepId;
    }

    return Card(
      margin: const EdgeInsets.only(bottom: 16),
      elevation: 2,
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  l10n.studioWorkflowStepCount(index + 1),
                  style: const TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 16,
                  ),
                ),
                IconButton(
                  icon: Icon(
                    Icons.delete,
                    color: Theme.of(context).colorScheme.error,
                  ),
                  onPressed: onDelete,
                ),
              ],
            ),
            const Divider(),

            Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        l10n.studioWorkflowNodeIdOpaque,
                        style: TextStyle(
                          fontSize: 12,
                          color: Theme.of(context).colorScheme.onSurfaceVariant,
                        ),
                      ),
                      const SizedBox(height: 4),
                      SelectableText(
                        stepIdController.text,
                        style: const TextStyle(
                          fontFamily: 'monospace',
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: DropdownButtonFormField<String>(
                    decoration: InputDecoration(
                      labelText: l10n.studioWorkflowTaskBlueprint,
                    ),
                    initialValue:
                        blueprints.any(
                          (bp) => bp['id'] == stepDef['task_blueprint'],
                        )
                        ? SafeCast.safeString(stepDef['task_blueprint'])
                        : null,
                    items: blueprints.map((bp) {
                      final stepId = SafeCast.safeString(bp['id']);
                      final label = getBlueprintLabel(stepId);
                      return DropdownMenuItem(
                        value: stepId,
                        child: Text(label),
                      );
                    }).toList(),
                    onChanged: (val) {
                      stepDef['task_blueprint'] = val;
                      onChanged();
                    },
                  ),
                ),
              ],
            ),

            const SizedBox(height: 16),
            Text(
              l10n.studioWorkflowXaiReporting,
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 8),
            Wrap(
              spacing: 8,
              children: mcpGateways.map((toolMap) {
                final slug = SafeCast.safeString(toolMap['slug']);
                final isSelected = allowedMcpTools.contains(slug);
                return FilterChip(
                  label: Text(slug),
                  selected: isSelected,
                  onSelected: (bool selected) {
                    if (selected) {
                      if (!allowedMcpTools.contains(slug)) {
                        allowedMcpTools.add(slug);
                      }
                    } else {
                      allowedMcpTools.remove(slug);
                    }
                    stepDef['allowed_mcp_tools'] = allowedMcpTools;
                    onChanged();
                  },
                );
              }).toList(),
            ),

            const SizedBox(height: 16),
            Text(
              l10n.studioWorkflowDependsOn,
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 8),
            if (previousSteps.isEmpty)
              Text(
                l10n.studioWorkflowNoDependencies,
                style: TextStyle(
                  color: Theme.of(context).colorScheme.onSurfaceVariant,
                ),
              )
            else
              Wrap(
                spacing: 8,
                children: previousSteps.map((prevId) {
                  final isSelected = dependsOn.contains(prevId);

                  // Extract human-readable label for dependency chip
                  String displayLabel = prevId;
                  final matchingNode = allSteps.firstWhere(
                    (s) =>
                        SafeCast.safeString(s['id'] ?? s['step_id']) == prevId,
                    orElse: () => <String, dynamic>{},
                  );
                  if (matchingNode.isNotEmpty) {
                    final bpId = SafeCast.safeString(
                      matchingNode['task_blueprint'],
                    );
                    final readableName = getBlueprintLabel(bpId);
                    displayLabel =
                        readableName.isNotEmpty && readableName != bpId
                        ? readableName
                        : prevId.length > 15
                        ? '${prevId.substring(0, 15)}...'
                        : prevId;
                  }

                  return FilterChip(
                    label: Text(displayLabel),
                    selected: isSelected,
                    onSelected: (bool selected) {
                      if (selected) {
                        if (!dependsOn.contains(prevId)) {
                          dependsOn.add(prevId);
                        }
                      } else {
                        dependsOn.remove(prevId);
                      }
                      stepDef['depends_on'] = dependsOn;
                      onChanged();
                    },
                  );
                }).toList(),
              ),

            const SizedBox(height: 16),
            Text(
              l10n.studioWorkflowInputMappings,
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
            ...mappings.entries.map((m) {
              return Padding(
                padding: const EdgeInsets.only(top: 8.0, bottom: 4.0),
                child: Row(
                  children: [
                    Expanded(
                      flex: 2,
                      child: TextFormField(
                        initialValue: m.key,
                        decoration: InputDecoration(
                          labelText: l10n.studioWorkflowTargetArgName,
                          isDense: true,
                        ),
                        onChanged: (newKey) {
                          final val = mappings[m.key];
                          mappings.remove(m.key);
                          mappings[newKey] = val ?? '';
                          stepDef['input_mappings'] = mappings;
                          onChanged();
                        },
                      ),
                    ),
                    const Padding(
                      padding: EdgeInsets.symmetric(horizontal: 8.0),
                      child: Icon(Icons.arrow_forward),
                    ),
                    Expanded(
                      flex: 3,
                      child: TextFormField(
                        initialValue: m.value,
                        decoration: InputDecoration(
                          labelText: l10n.studioWorkflowSourceToken,
                          isDense: true,
                        ),
                        onChanged: (newVal) {
                          mappings[m.key] = newVal;
                          stepDef['input_mappings'] = mappings;
                          onChanged();
                        },
                      ),
                    ),
                    IconButton(
                      icon: Icon(
                        Icons.remove_circle,
                        color: Theme.of(context).colorScheme.onSurfaceVariant,
                      ),
                      onPressed: () {
                        mappings.remove(m.key);
                        stepDef['input_mappings'] = mappings;
                        onChanged();
                      },
                    ),
                  ],
                ),
              );
            }),
            const SizedBox(height: 8),
            Align(
              alignment: Alignment.centerLeft,
              child: TextButton.icon(
                icon: const Icon(Icons.add_link),
                label: Text(l10n.studioWorkflowAddMappingBtn),
                onPressed: () {
                  mappings['new_arg_${mappings.length}'] = '';
                  stepDef['input_mappings'] = mappings;
                  onChanged();
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
