"""Execution layer prompts for heavy sensors, MCP tools, and DAG execution hooks."""

from backend_v2.models.prompts.execution.field_prompts import (
    DESC_CONTEXTUAL_OVERRIDE,
    DESC_EVALUATION_NOTES,
    DESC_EXACT_QUOTES,
    DESC_REASONING_TRACE,
    DESC_SEMANTIC_REASONING,
    STRICT_JSON_STRUCTURE_MANDATE,
    XAI_DESC_CITATION,
    XAI_DESC_COACHING,
    XAI_DESC_CONFIDENCE,
    XAI_DESC_FALSIFICATION,
    XAI_DESC_JUSTIFICATION,
)
from backend_v2.models.prompts.execution.global_mandates import (
    ANTI_ID_MANDATE,
    ANTI_SCORE_MANDATE,
    CONTEXT_SEGREGATION_MANDATE,
    EPISTEMIC_GLOSSARY_MANDATE,
    EXTENSION_ANCHORING_MANDATE,
    GLOBAL_MANDATES_XML,
    NULL_HYPOTHESIS_MANDATE,
    SCHEMA_PURITY_MANDATE,
    SEMANTIC_BLEED_MANDATE,
    VERBATIM_EXTRACTION_MANDATE,
)
from backend_v2.models.prompts.execution.hook_prompts import (
    INTERACTION_OBJECTIVE,
    INTERACTION_RULES,
)
from backend_v2.models.prompts.execution.matrix_evaluation import (
    CONTEXTUAL_OVERRIDE_DIRECTIVE,
    MATRIX_SENSOR_SYSTEM_PROMPT,
)
from backend_v2.models.prompts.execution.mcp_prompts import (
    CITATION_SELF_CORRECTION_SYSTEM_INSTRUCTION,
    MCP_EVIDENCE_INJECTION_DIRECTIVE,
    SOURCE_EXTRACTION_SYSTEM_INSTRUCTION,
    SOURCE_VERIFICATION_SYSTEM_INSTRUCTION,
    build_mcp_citation_extraction_directive,
)

__all__ = [
    "ANTI_ID_MANDATE",
    "ANTI_SCORE_MANDATE",
    "CITATION_SELF_CORRECTION_SYSTEM_INSTRUCTION",
    "CONTEXTUAL_OVERRIDE_DIRECTIVE",
    "CONTEXT_SEGREGATION_MANDATE",
    "DESC_CONTEXTUAL_OVERRIDE",
    "DESC_EVALUATION_NOTES",
    "DESC_EXACT_QUOTES",
    "DESC_REASONING_TRACE",
    "DESC_SEMANTIC_REASONING",
    "EPISTEMIC_GLOSSARY_MANDATE",
    "EXTENSION_ANCHORING_MANDATE",
    "GLOBAL_MANDATES_XML",
    "INTERACTION_OBJECTIVE",
    "INTERACTION_RULES",
    "MATRIX_SENSOR_SYSTEM_PROMPT",
    "MCP_EVIDENCE_INJECTION_DIRECTIVE",
    "NULL_HYPOTHESIS_MANDATE",
    "SCHEMA_PURITY_MANDATE",
    "SEMANTIC_BLEED_MANDATE",
    "SOURCE_EXTRACTION_SYSTEM_INSTRUCTION",
    "SOURCE_VERIFICATION_SYSTEM_INSTRUCTION",
    "STRICT_JSON_STRUCTURE_MANDATE",
    "VERBATIM_EXTRACTION_MANDATE",
    "XAI_DESC_CITATION",
    "XAI_DESC_COACHING",
    "XAI_DESC_CONFIDENCE",
    "XAI_DESC_FALSIFICATION",
    "XAI_DESC_JUSTIFICATION",
    "build_mcp_citation_extraction_directive",
]
