"""Synthesis layer prompt directives for reporting, SDUI formatting, and coaching tone."""

from backend_v2.models.prompts.synthesis.sdui_directives import (
    SDUI_BLOCK_STRUCTURE_MANDATE,
    SDUI_SYNTHESIS_MANDATE_BLOCK,
    SECTION_SYNTHESIS_DIRECTIVE_BLOCK,
    STATE_ISOLATION_BLOCK,
    SYNTHESIS_SDUI_MANDATES,
)
from backend_v2.models.prompts.synthesis.style_directives import (
    ANTI_JARGON_MANDATE_BLOCK,
    DEFAULT_COACHING_TONE_MANDATE,
    SPARSE_DATA_SYNTHESIS_MANDATE,
    SYNTHESIS_CITATION_RULES,
    SYNTHESIS_CITATION_RULES_HARVARD,
    SYNTHESIS_LENGTH_CONSTRAINT,
    SYNTHESIS_NO_CITATION_RULES,
)
from backend_v2.models.prompts.synthesis.synthesis_directives import (
    DEFAULT_ROW_EXPLANATION_SYSTEM_PROMPT,
    DEFAULT_SYNTHESIS_SYSTEM_PROMPT,
    DEFAULT_VARIANCE_SYSTEM_PROMPT,
    EXECUTIVE_SUMMARY_SECTION_ID,
    SYNTHESIS_SECTION_RULES_PREFIX,
    SYNTHESIS_XAI_CURATION,
)

__all__ = [
    "ANTI_JARGON_MANDATE_BLOCK",
    "DEFAULT_COACHING_TONE_MANDATE",
    "DEFAULT_ROW_EXPLANATION_SYSTEM_PROMPT",
    "DEFAULT_SYNTHESIS_SYSTEM_PROMPT",
    "DEFAULT_VARIANCE_SYSTEM_PROMPT",
    "EXECUTIVE_SUMMARY_SECTION_ID",
    "SDUI_BLOCK_STRUCTURE_MANDATE",
    "SDUI_SYNTHESIS_MANDATE_BLOCK",
    "SECTION_SYNTHESIS_DIRECTIVE_BLOCK",
    "SPARSE_DATA_SYNTHESIS_MANDATE",
    "STATE_ISOLATION_BLOCK",
    "SYNTHESIS_CITATION_RULES",
    "SYNTHESIS_CITATION_RULES_HARVARD",
    "SYNTHESIS_LENGTH_CONSTRAINT",
    "SYNTHESIS_NO_CITATION_RULES",
    "SYNTHESIS_SDUI_MANDATES",
    "SYNTHESIS_SECTION_RULES_PREFIX",
    "SYNTHESIS_XAI_CURATION",
]
