"""Synthesis layer prompt directives for reporting, SDUI formatting, and coaching tone."""

from backend_v2.models.prompts.synthesis.sdui_directives import (
    SDUI_BLOCK_STRUCTURE_MANDATE,
    SECTION_SYNTHESIS_DIRECTIVE_BLOCK,
    STATE_ISOLATION_BLOCK,
    SYNTHESIS_SDUI_MANDATES,
)
from backend_v2.models.prompts.synthesis.style_directives import (
    ANTI_JARGON_MANDATE_BLOCK,
    SPARSE_DATA_SYNTHESIS_MANDATE,
    SYNTHESIS_CITATION_RULES_HARVARD,
    SYNTHESIS_NO_CITATION_RULES,
)
from backend_v2.models.prompts.synthesis.synthesis_directives import (
    EXECUTIVE_SUMMARY_SECTION_ID,
    ROW_EXPLANATION_SYSTEM_PROMPT,
    SYNTHESIS_SECTION_RULES_PREFIX,
    SYNTHESIS_SYSTEM_PROMPT,
    SYNTHESIS_XAI_CURATION,
    VARIANCE_SYSTEM_PROMPT,
)

__all__ = [
    "ANTI_JARGON_MANDATE_BLOCK",
    "EXECUTIVE_SUMMARY_SECTION_ID",
    "ROW_EXPLANATION_SYSTEM_PROMPT",
    "SDUI_BLOCK_STRUCTURE_MANDATE",
    "SECTION_SYNTHESIS_DIRECTIVE_BLOCK",
    "SPARSE_DATA_SYNTHESIS_MANDATE",
    "STATE_ISOLATION_BLOCK",
    "SYNTHESIS_CITATION_RULES_HARVARD",
    "SYNTHESIS_NO_CITATION_RULES",
    "SYNTHESIS_SDUI_MANDATES",
    "SYNTHESIS_SECTION_RULES_PREFIX",
    "SYNTHESIS_SYSTEM_PROMPT",
    "SYNTHESIS_XAI_CURATION",
    "VARIANCE_SYSTEM_PROMPT",
]
