"""Common prompts and foundational epistemic mandates."""

from backend_v2.models.prompts.common.field_prompts import (
    DESC_CONTEXTUAL_OVERRIDE,
    DESC_EVALUATION_NOTES,
    DESC_EXACT_QUOTES,
    DESC_REASONING_TRACE,
    DESC_SEMANTIC_REASONING,
    STRICT_JSON_STRUCTURE_MANDATE,
    XAI_DESC_CITATION,
    XAI_DESC_COACHING,
    XAI_DESC_CONFIDENCE,
    XAI_DESC_FALSIFICATION,
    XAI_DESC_JUSTIFICATION,
)
from backend_v2.models.prompts.common.global_mandates import (
    ANTI_ID_MANDATE,
    ANTI_SCORE_MANDATE,
    CONTEXT_SEGREGATION_MANDATE,
    EPISTEMIC_GLOSSARY_MANDATE,
    EXTENSION_ANCHORING_MANDATE,
    GLOBAL_MANDATES_XML,
    NULL_HYPOTHESIS_MANDATE,
    SCHEMA_PURITY_MANDATE,
    SEMANTIC_BLEED_MANDATE,
    VERBATIM_EXTRACTION_MANDATE,
)
from backend_v2.models.prompts.common.linguistic_directives import (
    DESC_TRANSLATION_MANDATE,
    STATIC_LINGUISTIC_PROTOCOL,
    build_linguistic_parameters,
)

__all__ = [
    "ANTI_ID_MANDATE",
    "ANTI_SCORE_MANDATE",
    "CONTEXT_SEGREGATION_MANDATE",
    "DESC_CONTEXTUAL_OVERRIDE",
    "DESC_EVALUATION_NOTES",
    "DESC_EXACT_QUOTES",
    "DESC_REASONING_TRACE",
    "DESC_SEMANTIC_REASONING",
    "DESC_TRANSLATION_MANDATE",
    "EPISTEMIC_GLOSSARY_MANDATE",
    "EXTENSION_ANCHORING_MANDATE",
    "GLOBAL_MANDATES_XML",
    "NULL_HYPOTHESIS_MANDATE",
    "SCHEMA_PURITY_MANDATE",
    "SEMANTIC_BLEED_MANDATE",
    "STATIC_LINGUISTIC_PROTOCOL",
    "STRICT_JSON_STRUCTURE_MANDATE",
    "VERBATIM_EXTRACTION_MANDATE",
    "XAI_DESC_CITATION",
    "XAI_DESC_COACHING",
    "XAI_DESC_CONFIDENCE",
    "XAI_DESC_FALSIFICATION",
    "XAI_DESC_JUSTIFICATION",
    "build_linguistic_parameters",
]
