"""Automated Dart Codebase Guardrails Engine (DGR001-DGR004).

Single Source of Truth for static Dart architectural rules enforcement across Quorum Flutter client.
Scans handwritten client code for loose Map types, UI error concealment, unlocalized strings, and lint suppressions.
Guarantees 100% false-positive immunity for generated files (*.freezed.dart, *.g.dart, .dart_tool/, build/).
"""

from __future__ import annotations

import argparse
import io
import re
import sys
from collections.abc import Sequence
from enum import StrEnum
from pathlib import Path
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

__all__ = [
    "DartViolation",
    "GuardrailSeverity",
    "format_dart_violations_table",
    "is_generated_dart_file",
    "main",
    "scan_dart_file",
    "scan_dart_files",
    "scan_dart_source",
]

# Force UTF-8 encoding for stdout on Windows
if isinstance(sys.stdout, io.TextIOWrapper):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except AttributeError, io.UnsupportedOperation:
        pass


class GuardrailSeverity(StrEnum):
    """Severity classification for Dart guardrail violations."""

    WARNING = "WARNING"
    FATAL = "FATAL"


class DartViolation(BaseModel):
    """Pydantic V2 DTO representing a Dart architectural violation."""

    model_config = ConfigDict(strict=True, extra="forbid", frozen=True)

    filepath: Annotated[str, Field(description="Target file path relative to workspace")]
    lineno: Annotated[int, Field(ge=0, description="1-indexed line number where violation occurred")]
    col_offset: Annotated[int, Field(ge=0, description="Column offset of violation")]
    rule_code: Annotated[str, Field(pattern=r"^DGR\d{3}$", description="Rule code e.g. DGR001")]
    message: Annotated[str, Field(description="Descriptive violation message")]
    remediation: Annotated[str, Field(description="Deterministic remediation guidance")]
    severity: Annotated[GuardrailSeverity, Field(description="Severity tier")]
    is_suppressed: Annotated[bool, Field(description="Whether violation is suppressed")]


# ==============================================================================
# Rule Patterns
# ==============================================================================

# DGR001: Loose Map return types in API clients or feature models
DGR001_PATTERN = re.compile(
    r"\b(Future\s*<\s*List\s*<\s*Map(?:\s*<[^>]+>)?\s*>\s*>|"
    r"Future\s*<\s*Map(?:\s*<[^>]+>)?\s*>|"
    r"List\s*<\s*Map(?:\s*<[^>]+>)?\s*>|"
    r"Map\s*<[A-Za-z0-9_?,\s]+>)\s+([A-Za-z0-9_]+)\s*\("
)

# DGR002: SizedBox.shrink() concealment
DGR002_PATTERN = re.compile(r"\b(?:const\s+)?SizedBox\.shrink\s*\(\s*\)")

# DGR003: Raw hardcoded string literals in Text("...") widgets
DGR003_PATTERN = re.compile(r"\b(?:const\s+)?Text\s*\(\s*(['\"])(.*?)\1\s*[,)]")

# DGR004: Dart lint suppressions (// ignore: or // ignore_for_file:)
DGR004_PATTERN = re.compile(r"//\s*(?:ignore_for_file|ignore):")

# Ignored trivial string literals for DGR003 (pure symbols or separators)
PUNCTUATION_OR_EMPTY_PATTERN = re.compile(r"^[\s\-:–—|/\\.,;*+~#_!?@$%^&()\[\]{}'\"0-9]*$")


def is_generated_dart_file(filepath: Path | str, source_text: str | None = None) -> bool:
    """Checks if a Dart file is generated by build_runner or external tooling."""
    p = Path(filepath)
    name = p.name.lower()
    if name.endswith(".freezed.dart") or name.endswith(".g.dart"):
        return True

    normalized_path = str(p).replace("\\", "/")
    parts = set(normalized_path.strip("/").split("/"))
    if ".dart_tool" in parts or "build" in parts:
        return True

    if source_text is not None:
        for line in source_text.splitlines()[:15]:
            upper_line = line.upper()
            if "GENERATED CODE - DO NOT MODIFY BY HAND" in upper_line or "GENERATED BY BUILD_RUNNER" in upper_line:
                return True

    return False


def scan_dart_source(filepath: str, source_bytes: bytes, strict: bool = False) -> list[DartViolation]:
    """Scans Dart source code bytes for architectural violations."""
    try:
        source_text = source_bytes.decode("utf-8")
    except UnicodeDecodeError as exc:
        return [
            DartViolation(
                filepath=filepath,
                lineno=1,
                col_offset=0,
                rule_code="DGR000",
                message=f"Fatal encoding error reading Dart file: {exc}",
                remediation="Ensure file is valid UTF-8 encoded text.",
                severity=GuardrailSeverity.FATAL,
                is_suppressed=False,
            )
        ]

    # 100% Immunity for generated files
    if is_generated_dart_file(filepath, source_text):
        return []

    violations: list[DartViolation] = []
    normalized_path = filepath.replace("\\", "/").strip("/")
    path_parts = set(normalized_path.split("/"))

    is_api_or_model_scope = "api" in path_parts or "models" in path_parts or "core/api" in normalized_path
    is_ui_scope = "features" in path_parts or "shared" in path_parts
    is_feature_widget_scope = "features" in path_parts and "test" not in path_parts
    default_severity = GuardrailSeverity.FATAL if strict else GuardrailSeverity.WARNING

    lines = source_text.splitlines()
    for lineno, line in enumerate(lines, start=1):
        stripped = line.strip()
        if not stripped:
            continue

        # DGR004: Banned Dart lint suppressions
        dgr004_match = DGR004_PATTERN.search(line)
        if dgr004_match:
            violations.append(
                DartViolation(
                    filepath=filepath,
                    lineno=lineno,
                    col_offset=dgr004_match.start(),
                    rule_code="DGR004",
                    message="Banned Dart lint suppression comment detected in handwritten code.",
                    remediation="Resolve the underlying static analysis warning instead of using `// ignore:` or `// ignore_for_file:`.",
                    severity=default_severity,
                    is_suppressed=False,
                )
            )

        # Skip scanning logic rules on pure comments
        if stripped.startswith("//") or stripped.startswith("/*") or stripped.startswith("*"):
            continue

        # DGR001: Banned loose Map return types in API clients or models
        if is_api_or_model_scope:
            dgr001_match = DGR001_PATTERN.search(line)
            if dgr001_match:
                ret_type = dgr001_match.group(1).strip()
                method_name = dgr001_match.group(2).strip()
                violations.append(
                    DartViolation(
                        filepath=filepath,
                        lineno=lineno,
                        col_offset=dgr001_match.start(),
                        rule_code="DGR001",
                        message=f"Banned loose Map return type `{ret_type}` in method `{method_name}`.",
                        remediation="Return strongly typed Freezed DTOs or domain models instead of raw Map<String, dynamic> in API clients.",
                        severity=default_severity,
                        is_suppressed=False,
                    )
                )

        # DGR002: Banned SizedBox.shrink() concealment
        if is_ui_scope:
            dgr002_match = DGR002_PATTERN.search(line)
            if dgr002_match:
                violations.append(
                    DartViolation(
                        filepath=filepath,
                        lineno=lineno,
                        col_offset=dgr002_match.start(),
                        rule_code="DGR002",
                        message="Banned `SizedBox.shrink()` UI error or layout concealment detected.",
                        remediation="Use `AppErrorBoundary`, typed error state widgets, or explicit empty placeholders instead of `SizedBox.shrink()`.",
                        severity=default_severity,
                        is_suppressed=False,
                    )
                )

        # DGR003: Banned hardcoded UI string literals in Text widgets
        if is_feature_widget_scope:
            dgr003_match = DGR003_PATTERN.search(line)
            if dgr003_match:
                raw_text = dgr003_match.group(2)
                # Ignore trivial punctuation, separators, or empty strings
                if not PUNCTUATION_OR_EMPTY_PATTERN.match(raw_text):
                    violations.append(
                        DartViolation(
                            filepath=filepath,
                            lineno=lineno,
                            col_offset=dgr003_match.start(),
                            rule_code="DGR003",
                            message=f'Banned hardcoded string literal `"{raw_text}"` in `Text()` widget.',
                            remediation="Use `AppLocalizations.of(context)` or `.arb` localization keys instead of raw hardcoded strings in `Text(...)` widgets.",
                            severity=default_severity,
                            is_suppressed=False,
                        )
                    )

    return violations


def scan_dart_file(filepath: Path, strict: bool = False) -> list[DartViolation]:
    """Scans a single Dart file on disk."""
    if not filepath.exists():
        return [
            DartViolation(
                filepath=str(filepath),
                lineno=1,
                col_offset=0,
                rule_code="DGR000",
                message=f"Fatal read error: File not found `{filepath}`",
                remediation="Verify that the target path exists.",
                severity=GuardrailSeverity.FATAL,
                is_suppressed=False,
            )
        ]

    try:
        source_bytes = filepath.read_bytes()
    except OSError as exc:
        return [
            DartViolation(
                filepath=str(filepath),
                lineno=1,
                col_offset=0,
                rule_code="DGR000",
                message=f"Fatal OS read error: {exc}",
                remediation="Check file permissions and disk availability.",
                severity=GuardrailSeverity.FATAL,
                is_suppressed=False,
            )
        ]

    return scan_dart_source(str(filepath), source_bytes, strict=strict)


def scan_dart_files(filepaths: Sequence[Path], strict: bool = False) -> list[DartViolation]:
    """Scans multiple Dart files or directories, recursing into subdirectories."""
    all_violations: list[DartViolation] = []
    for fp in filepaths:
        if fp.is_dir():
            for child in fp.rglob("*.dart"):
                if child.is_file():
                    all_violations.extend(scan_dart_file(child, strict=strict))
        elif fp.is_file() and fp.suffix == ".dart":
            all_violations.extend(scan_dart_file(fp, strict=strict))
    return all_violations


def format_dart_violations_table(violations: Sequence[DartViolation]) -> str:
    """Formats Dart guardrail violations into a structured ASCII table."""
    if not violations:
        return "No Dart guardrail violations found."

    headers = ("Severity", "Rule", "File:Line:Col", "Message")
    rows: list[tuple[str, str, str, str]] = []
    for v in violations:
        loc = f"{v.filepath}:{v.lineno}:{v.col_offset}"
        rows.append((v.severity.value, v.rule_code, loc, v.message))

    col_widths = [max(len(headers[i]), max((len(r[i]) for r in rows), default=0)) for i in range(4)]

    header_line = " | ".join(headers[i].ljust(col_widths[i]) for i in range(4))
    separator_line = "-+-".join("-" * col_widths[i] for i in range(4))
    body_lines = [" | ".join(row[i].ljust(col_widths[i]) for i in range(4)) for row in rows]

    return "\n".join([header_line, separator_line] + body_lines)


def main(argv: list[str] | None = None) -> int:
    """CLI entry point for Dart guardrail engine."""
    parser = argparse.ArgumentParser(description="Quorum Dart Codebase Guardrails Engine")
    parser.add_argument(
        "targets",
        nargs="*",
        default=["client_app_v2/lib"],
        help="Target Dart files or directories to scan (default: client_app_v2/lib)",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Treat all violations as FATAL and return exit code 1",
    )
    args = parser.parse_args(argv)

    target_paths = [Path(t) for t in args.targets]
    violations = scan_dart_files(target_paths, strict=args.strict)

    fatal_violations = [v for v in violations if v.severity == GuardrailSeverity.FATAL]
    warning_violations = [v for v in violations if v.severity == GuardrailSeverity.WARNING]

    if violations:
        print(format_dart_violations_table(violations))
        print(
            f"\nTotal Dart Violations: {len(violations)} "
            f"({len(fatal_violations)} FATAL, {len(warning_violations)} WARNING)"
        )
    else:
        print("All Dart guardrail checks passed cleanly! (0 violations)")

    if fatal_violations or (args.strict and violations):
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
