import json

path = r"c:\src\quorum\backend_v2\seed\seed_data.json"
with open(path, encoding="utf-8") as f:
    data = json.load(f)

# Find profile
profile = next(p for p in data["output_profiles"] if p["id"] == "prf_5d6e7f8091a2b3c4")

# 1. Update custom_preface
profile["custom_preface"] = {
    "default_locale": "fi",
    "translations": {
        "en": "**Report on your AI skills**\n\nThis report analyzes your way of utilizing AI and helps you develop into a strategic guide...",
        "fi": "**Raportti tekoälytaidoistasi**\n\nTämä raportti analysoi tapaasi hyödyntää tekoälyä ja auttaa sinua kehittymään sen strategiseksi ohjaajaksi. Arvioinnissa keskitytään kolmeen osa-alueeseen:\n\n- **Oivalluskyky**: Pureudutko syvälle aiheeseen vai jäätkö pintatasolle?\n- **Logiikka ja päättely**: Miten perustelet väitteesi ja haastat tekoälyn vastauksia?\n- **Luotettavuus**: Miten hallitset prosessia ja sen läpinäkyvyyttä?\n\nAnalyysi perustuu tieteellisiin malleihin (mm. Kahneman, Toulmin ja Popper). Lopussa olevan pisteytyksen avulla voit tunnistaa vahvuutesi ja rakentaa itsellesi tavoitteellisen kehityspolun.",
    },
}

# 2. Build layouts list correctly
layouts = [
    {
        "preset_view": "text_only",
        "title": None,
        "description": None,
        "is_synthesis_enabled": True,
        "steps": [],
        "target_blocks": None,
        "text_delivery_mode": "full",
        "synthesis": {
            "synthesis_block_id": "blk_1a2b3c4d5e6f7a8b",
            "model_strategy": "synthesis",
            "historical_context_mode": "DISABLED",
            "enable_pii_masking": False,
            "allowed_exports": ["pdf", "raw_json", "sdui"],
            "omit_empty_sections": True,
            "allowed_mcp_tools": [],
        },
        "synthesis_blocks": None,
        "strictness_level": None,
        "scoring_strategy": None,
        "matrix_column_labels": {},
        "matrix_visible_columns": [],
    },
    {
        "preset_view": "2d_compare",
        "title": None,
        "description": None,
        "is_synthesis_enabled": True,
        "steps": [],
        "target_blocks": ["blk_440a5fef9331451b", "blk_53f32679aa514fcb", "blk_109dab5b6b3f403a"],
        "text_delivery_mode": "full",
        "synthesis": {
            "synthesis_block_id": "blk_8b7a6f5e4d3c2b1a",
            "model_strategy": "synthesis",
            "historical_context_mode": "DISABLED",
            "enable_pii_masking": False,
            "allowed_exports": ["pdf", "raw_json", "sdui"],
            "omit_empty_sections": True,
            "allowed_mcp_tools": [],
        },
        "synthesis_blocks": None,
        "strictness_level": None,
        "scoring_strategy": None,
        "matrix_column_labels": {},
        "matrix_visible_columns": [],
    },
    {
        "preset_view": "2d_compare",
        "title": None,
        "description": None,
        "is_synthesis_enabled": True,
        "steps": [],
        "target_blocks": ["blk_c5804a9143c34cb1", "blk_b476f89fb732448c"],
        "text_delivery_mode": "full",
        "synthesis": {
            "synthesis_block_id": "blk_8b7a6f5e4d3c2b1a",
            "model_strategy": "synthesis",
            "historical_context_mode": "DISABLED",
            "enable_pii_masking": False,
            "allowed_exports": ["pdf", "raw_json", "sdui"],
            "omit_empty_sections": True,
            "allowed_mcp_tools": [],
        },
        "synthesis_blocks": None,
        "strictness_level": None,
        "scoring_strategy": None,
        "matrix_column_labels": {},
        "matrix_visible_columns": [],
    },
    {
        "preset_view": "2d_compare",
        "title": None,
        "description": None,
        "is_synthesis_enabled": True,
        "steps": [],
        "target_blocks": ["blk_6b8c766185294f7e", "blk_f6e286f050c94d60"],
        "text_delivery_mode": "full",
        "synthesis": {
            "synthesis_block_id": "blk_8b7a6f5e4d3c2b1a",
            "model_strategy": "synthesis",
            "historical_context_mode": "DISABLED",
            "enable_pii_masking": False,
            "allowed_exports": ["pdf", "raw_json", "sdui"],
            "omit_empty_sections": True,
            "allowed_mcp_tools": [],
        },
        "synthesis_blocks": None,
        "strictness_level": None,
        "scoring_strategy": None,
        "matrix_column_labels": {},
        "matrix_visible_columns": [],
    },
    {
        "preset_view": "text_only",
        "title": {"translations": {"fi": "Best Practices -yhteensopivuus", "en": "Best Practices Compliance"}},
        "description": None,
        "is_synthesis_enabled": True,
        "steps": [],
        "target_blocks": ["blk_fb15f8dcf23f4865"],  # matrix_archivist
        "text_delivery_mode": "full",
        "synthesis": None,
        "synthesis_blocks": None,
        "strictness_level": None,
        "scoring_strategy": None,
        "matrix_column_labels": {},
        "matrix_visible_columns": [],
    },
    {
        "preset_view": "text_only",
        "title": {"translations": {"fi": "Lopullinen Tuomioasteikko", "en": "Final Verdict Scale"}},
        "description": None,
        "is_synthesis_enabled": True,
        "steps": [],
        "target_blocks": ["blk_ff72c2d79edb4ebf"],  # matrix_judge
        "text_delivery_mode": "full",
        "synthesis": None,
        "synthesis_blocks": None,
        "strictness_level": None,
        "scoring_strategy": None,
        "matrix_column_labels": {},
        "matrix_visible_columns": [],
    },
    {
        "preset_view": "text_only",
        "title": {"translations": {"fi": "Turvallisuuden ja Etiikan Auditointi", "en": "Security and Ethics Audit"}},
        "description": None,
        "is_synthesis_enabled": True,
        "steps": [],
        "target_blocks": ["blk_80732a33fe1947ee"],  # matrix_taskguard
        "text_delivery_mode": "full",
        "synthesis": None,
        "synthesis_blocks": None,
        "strictness_level": None,
        "scoring_strategy": None,
        "matrix_column_labels": {},
        "matrix_visible_columns": [],
    },
    {
        "preset_view": "text_only",
        "title": {
            "translations": {"fi": "Kausaalinen ja Abduktiivinen Integriteetti", "en": "Causal and Abductive Integrity"}
        },
        "description": None,
        "is_synthesis_enabled": True,
        "steps": [],
        "target_blocks": ["blk_c3bc5f3eb8e74110"],  # matrix_causal_abductive
        "text_delivery_mode": "full",
        "synthesis": None,
        "synthesis_blocks": None,
        "strictness_level": None,
        "scoring_strategy": None,
        "matrix_column_labels": {},
        "matrix_visible_columns": [],
    },
    {
        "preset_view": "text_only",
        "title": {"translations": {"fi": "Episteeminen Nöyryys", "en": "Epistemic Humility"}},
        "description": None,
        "is_synthesis_enabled": True,
        "steps": [],
        "target_blocks": ["blk_22e3598e06414409"],  # matrix_epistemic_humility
        "text_delivery_mode": "full",
        "synthesis": None,
        "synthesis_blocks": None,
        "strictness_level": None,
        "scoring_strategy": None,
        "matrix_column_labels": {},
        "matrix_visible_columns": [],
    },
    {
        "preset_view": "matrix_summary",
        "title": None,
        "description": None,
        "is_synthesis_enabled": True,
        "steps": [],
        "target_blocks": ["*"],
        "text_delivery_mode": "full",
        "synthesis": None,
        "synthesis_blocks": None,
        "strictness_level": None,
        "scoring_strategy": None,
        "matrix_column_labels": {},
        "matrix_visible_columns": ["label", "distribution", "row_explanation", "score"],
    },
    {
        "preset_view": "text_only",
        "title": None,
        "description": None,
        "is_synthesis_enabled": True,
        "steps": [],
        "target_blocks": ["printable_sources_block"],
        "text_delivery_mode": "full",
        "synthesis": None,
        "synthesis_blocks": None,
        "strictness_level": None,
        "scoring_strategy": None,
        "matrix_column_labels": {},
        "matrix_visible_columns": [],
    },
    {
        "preset_view": "1d_metrics",
        "title": None,
        "description": None,
        "is_synthesis_enabled": True,
        "steps": [],
        "target_blocks": ["global_score_block"],
        "text_delivery_mode": "full",
        "synthesis": None,
        "synthesis_blocks": None,
        "strictness_level": None,
        "scoring_strategy": None,
        "matrix_column_labels": {},
        "matrix_visible_columns": [],
    },
    {
        "preset_view": "text_only",
        "title": None,
        "description": None,
        "is_synthesis_enabled": True,
        "steps": [],
        "target_blocks": ["penalties_block", "audit_trail_block"],
        "text_delivery_mode": "full",
        "synthesis": None,
        "synthesis_blocks": None,
        "strictness_level": None,
        "scoring_strategy": None,
        "matrix_column_labels": {},
        "matrix_visible_columns": [],
    },
]

profile["layouts"] = layouts

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
