import json


def merge_draft():
    # Load the original seed data
    with open('c:/src/quorum/backend_v2/seed/backups/seed_data_pre_phase4_20260611.json', encoding='utf-8') as f:
        db = json.load(f)

    # Load the draft generated by Phase 3
    with open('c:/src/quorum/backend_v2/seed/seed_data_v2_draft.json', encoding='utf-8') as f:
        draft = json.load(f)

    # Map tda_id to its draft JSON representation
    draft_tdas = {}
    for pb in draft.get('prompt_blocks', []):
        for s in pb.get('scales', []):
            for c in s.get('claims', []):
                for tda in c.get('tda_assertions', []):
                    draft_tdas[tda['tda_id']] = tda

    # Apply to db
    for pb in db.get('prompt_blocks', []):
        for s in pb.get('scales', []):
            for c in s.get('claims', []):
                for tda in c.get('tda_assertions', []):
                    # Always remove ai_rule_description
                    old_desc = tda.pop('ai_rule_description', 'Missing Rule Description')

                    if tda['tda_id'] in draft_tdas and 'concept_description' in draft_tdas[tda['tda_id']]:
                        dtda = draft_tdas[tda['tda_id']]
                        tda['concept_description'] = dtda['concept_description']
                        if 'acceptance_criteria' in dtda:
                            tda['acceptance_criteria'] = dtda['acceptance_criteria']
                        if 'anti_patterns' in dtda:
                            tda['anti_patterns'] = dtda['anti_patterns']
                        if 'contrastive_example' in dtda:
                            tda['contrastive_example'] = dtda['contrastive_example']
                        if 'syntactic_anchors' in dtda:
                            tda['syntactic_anchors'] = dtda['syntactic_anchors']
                        if 'enforce_pre_flight' in dtda:
                            tda['enforce_pre_flight'] = dtda['enforce_pre_flight']
                    else:
                        # Fallback missing bilingual fields to avoid Pydantic validation errors
                        tda['concept_description'] = {
                            "default_locale": "en",
                            "translations": {"en": old_desc, "fi": old_desc}
                        }

    # Write back
    with open('c:/src/quorum/backend_v2/seed/seed_data.json', 'w', encoding='utf-8') as f:
        json.dump(db, f, indent=4)

if __name__ == "__main__":
    merge_draft()
