import json
import argparse
import sys
import codecs
import os
from pathlib import Path

def setup_console():
    sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())

def get_latest_execution_dir(base_dir):
    """Finds the most recently modified execution directory containing execution_trace.json."""
    if not base_dir.exists():
        return None
    
    latest_dir = None
    latest_mtime = -1
    
    for exec_dir in base_dir.iterdir():
        if exec_dir.is_dir():
            trace_file = exec_dir / "execution_trace.json"
            if trace_file.exists():
                mtime = trace_file.stat().st_mtime
                if mtime > latest_mtime:
                    latest_mtime = mtime
                    latest_dir = exec_dir
                    
    return latest_dir

def parse_args():
    parser = argparse.ArgumentParser(description="Quorum Execution Trace Lineage Viewer")
    parser.add_argument("execution_id", nargs="?", help="Execution ID (e.g., exe_... ). If omitted, uses the most recent execution.")
    parser.add_argument("--matrix", help="Optional: Filter by a specific matrix ID (block_id)")
    
    # Optional overrides
    parser.add_argument("--trace", help="Optional: Direct path to execution_trace.json (overrides execution_id)")
    parser.add_argument("--seed", help="Optional: Direct path to db_v2.json or seed_data.json")
    return parser.parse_args()

def load_seed_data(seed_path):
    with open(seed_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    tda_map = {}
    
    prompt_blocks = data.get("prompt_blocks", [])
    if isinstance(prompt_blocks, dict):
        prompt_blocks = list(prompt_blocks.values())
        
    for block in prompt_blocks:
        block_id = block.get("id")
        for scale in block.get("scales") or []:
            for claim in scale.get("claims") or []:
                for tda in claim.get("tda_assertions") or []:
                    tda_id = tda.get("tda_id")
                    rule = tda.get("extraction_rule") or tda.get("concept_description") or "N/A"
                    tda_map[tda_id] = {
                        "block_id": block_id,
                        "rule": rule
                    }
    return tda_map

def load_trace_data(trace_path):
    with open(trace_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def extract_dynamic_facts(trace_data):
    """Scan trace for dynamic facts generated by Extractors."""
    dynamic_facts = {}
    for event in trace_data:
        if event.get("event_type") == "output":
            content = event.get("content", {})
            # Extractors sometimes output dicts mapped by tda_id
            for k, v in content.items():
                if isinstance(v, dict) and "resolved_claim" in v:
                    dynamic_facts[k] = v
            # Extractors sometimes output a list of results
            results = content.get("results", [])
            if isinstance(results, list):
                for r in results:
                    tda_id = r.get("tda_id") or r.get("atom_id")
                    if tda_id and r.get("resolved_claim"):
                        dynamic_facts[tda_id] = r
    return dynamic_facts

def analyze_evaluations(trace_data, tda_map, dynamic_facts, target_matrix=None):
    print("=" * 80)
    print("QUORUM TRACE LINEAGE ANALYSIS")
    print("=" * 80)
    
    found_evaluations = False

    for event in trace_data:
        if event.get("event_type") == "output":
            content = event.get("content", {})
            
            # Check for results list (usually in Logician or Evaluator nodes)
            results = content.get("results", [])
            if isinstance(results, list) and len(results) > 0 and isinstance(results[0], dict) and ("tda_id" in results[0] or "atom_id" in results[0]):
                
                step_name = event.get("step_name", "UNKNOWN_STEP")
                
                # Determine block mapping for these results
                filtered_results = []
                for res in results:
                    tda_id = res.get("tda_id") or res.get("atom_id")
                    block_id = tda_map.get(tda_id, {}).get("block_id", "UNKNOWN_BLOCK (Dynamic or Orphan)")
                    
                    if target_matrix and block_id != target_matrix and block_id != "UNKNOWN_BLOCK (Dynamic or Orphan)":
                        continue
                    filtered_results.append((tda_id, block_id, res))
                
                if not filtered_results:
                    continue
                    
                found_evaluations = True
                print(f"\n[{step_name}] Evaluated {len(filtered_results)} atoms")
                print("-" * 80)
                
                for tda_id, block_id, res in filtered_results:
                    print(f"Atom ID : {tda_id}")
                    print(f"Matrix  : {block_id}")
                    
                    # 1. Source Quote
                    quote = res.get("source_quote") or "N/A"
                    if isinstance(quote, str) and len(quote) > 100:
                        quote = quote[:100] + "..."
                    print(f"Source  : {quote}")
                    
                    # 2. Match Static Rule
                    static_info = tda_map.get(tda_id)
                    if static_info:
                        print(f"Rule    : [STATIC] {static_info['rule']}")
                    
                    # 3. Match Dynamic Fact
                    dyn_info = dynamic_facts.get(tda_id)
                    if dyn_info:
                        claim = dyn_info.get("resolved_claim") or "N/A"
                        print(f"Rule    : [DYNAMIC] {claim}")
                        
                    # 4. Result/Extensions
                    status = res.get("status")
                    if status is None:
                        status = "RAW DTO"
                        
                    reasoning = res.get("evaluation_reasoning") or "N/A"
                    falsification = res.get("extensions", {}).get("falsification") or "N/A"
                    
                    print(f"Result  : {status}")
                    if reasoning != "N/A":
                        print(f"Reason  : {reasoning}")
                    if falsification != "N/A":
                        print(f"Falsif. : {falsification}")
                        
                    print("-" * 40)

    if not found_evaluations:
        print("\nNo evaluations matched the criteria. (Hint: check matrix ID or ensure trace contains 'results' arrays).")

def main():
    setup_console()
    args = parse_args()
    
    # Resolve project root
    project_root = Path(__file__).parent.parent.resolve()
    
    # Resolve Seed/DB Data
    seed_path = args.seed
    if not seed_path:
        seed_path = project_root / "data" / "db_v2.json"
    else:
        seed_path = Path(seed_path)
        
    if not seed_path.exists():
        print(f"Error: Database file not found at {seed_path}")
        sys.exit(1)
        
    # Resolve Trace Data
    trace_path = args.trace
    if not trace_path:
        executions_dir = project_root / "data" / "files" / "executions"
        
        if args.execution_id:
            exec_dir = executions_dir / args.execution_id
            trace_path = exec_dir / "execution_trace.json"
        else:
            print(f"No execution_id provided. Searching for the most recent execution in {executions_dir}...")
            latest_dir = get_latest_execution_dir(executions_dir)
            if not latest_dir:
                print(f"Error: No executions found in {executions_dir}")
                sys.exit(1)
            trace_path = latest_dir / "execution_trace.json"
            print(f"Found latest execution: {latest_dir.name}\n")
    else:
        trace_path = Path(trace_path)
        
    if not trace_path.exists():
        print(f"Error: Trace file not found at {trace_path}")
        sys.exit(1)
        
    tda_map = load_seed_data(seed_path)
    trace_data = load_trace_data(trace_path)
    
    dynamic_facts = extract_dynamic_facts(trace_data)
    
    analyze_evaluations(trace_data, tda_map, dynamic_facts, args.matrix)

if __name__ == "__main__":
    main()
