"""Service for parsing unstructured pasted chat logs into strict JSON structures.

Uses an LLM (strategy: 'ChatParser') to decouple human conversation from UI garbage,
aligning with the V2 Fail-Fast architecture.
"""

import json
import logging
from typing import Any

from fastapi import status
from pydantic import ValidationError

from backend_v2.exceptions import AppException, ConfigurationError, ErrorCodes
from backend_v2.llm.client import LLMClient
from backend_v2.models.v2_core import ChatHistoryDTO

logger = logging.getLogger(__name__)

_SYSTEM_INSTRUCTION = (
    "You are a data-mining expert. Your task is to receive messy raw text copy-pasted\n"
    "from a user's browser, originating from an AI chat (e.g. ChatGPT, Gemini, or Claude).\n\n"
    "RULES:\n"
    "1. Separate human ('user') and AI ('ai') messages from the text. The 'role' MUST be "
    "either 'user' or 'ai'.\n"
    "2. CRITICAL - PDF PRINTOUT RECONSTRUCTION: The user input might be a browser printout "
    "(Print to PDF) of a ChatGPT conversation that PyMuPDF has shredded into a single long "
    "string of text, destroying all visual boundaries.\n"
    '   - Look for repeating identifiers like a person\'s name ("You", full name, initials) '
    'vs "ChatGPT", "AI".\n'
    "   - Even without these, YOU MUST INFER the turn changes from context: human messages are "
    'typically questions or prompts (e.g., "Do this next...", "What do you mean by..."), '
    "followed by structured informational text generated by the machine.\n"
    "   - Merge the fragmented text seamlessly back together under each proper role "
    "('user' or 'ai'), restoring the original question-answer rhythm. Prefer overly long "
    "blocks over overly fragmented ones.\n"
    '3. Completely ignore all UI garbage text (e.g., "Regenerate", "Copy code", '
    'timestamps, "Was this response better or worse?", side menus, profile names).\n'
    "4. Assumption: messages alternate. If the text starts with a human question, the "
    "first 'role' is 'user'.\n"
    "5. Return the data EXACTLY in the requested Pydantic JSON format.\n"
    "6. WARNING (FAIL-SAFE): If the raw text does not look like a conversation in any way "
    "(e.g., it is just a messy learning diary or essay without dialogue), NEVER return an "
    "empty list. In this emergency, place all the text as one single long message under "
    "the 'user' role."
)


class ChatParserService:
    @staticmethod
    async def parse_pasted_chat(raw_paste: str, repository: Any) -> ChatHistoryDTO:
        """Parse raw pasted chat logs into strict JSON using LLM.

        Args:
            raw_paste (str): Raw unstructured text pasted from a chat UI.
            repository (Any): AbstractWorkflowRepository instance.

        Returns:
            ChatHistoryDTO: Strictly typed chat history object.

        Raises:
            AppException: If input is empty, LLM fails, or validation fails.
        """
        logger.debug("[ChatParser] parse_pasted_chat CALLED")

        if not raw_paste or not raw_paste.strip():
            # Fail Fast: Cannot parse empty text
            error_code = ErrorCodes.EMPTY_INPUT
            msg = "ChatParser received empty input."
            logger.error("[ChatParser] %s: %s", error_code.name, msg)
            raise AppException(
                message=msg, status_code=status.HTTP_400_BAD_REQUEST, details={"error_code": error_code.value}
            )

        # Initialize LLM Client via Strategy Pattern
        try:
            # Note: The system model_registry must have a 'fast' (or alias) strategy defined.
            llm_client = await LLMClient.from_strategy("fast", repository=repository)
        except ConfigurationError as e:
            error_code = ErrorCodes.CONFIGURATION_ERROR
            msg = f"Failed to initialize LLMClient for ChatParser: {e.message}"
            logger.error("[ChatParser] %s: %s", error_code.name, msg)
            raise AppException(
                message=msg, status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, details={"error_code": error_code.value}
            ) from e

        # Construct the Prompt
        # Mandates: Strip all AI UI fluff (Regenerate, Copy code, etc)
        # Role Segregation: Isolated System Instruction prevents prompt injection
        messages = [
            {"role": "system", "content": _SYSTEM_INSTRUCTION},
            {"role": "user", "content": f"Here is the raw text to process:\n<raw_text>\n{raw_paste}\n</raw_text>\n"},
        ]

        try:
            # V2 Strict Output Generation
            parsed_data, _ = await llm_client.run_structured_task(messages=messages, response_model=ChatHistoryDTO)
            logger.info("[ChatParser] Parsing successful. Extracted %s messages.", len(parsed_data.conversation))
            return parsed_data

        except ValidationError as e:
            error_code = ErrorCodes.VALIDATION_FAILED
            msg = f"LLM output validation failed to match ChatHistoryDTO schema: {e}"
            logger.error("[ChatParser] %s: %s", error_code.name, msg, exc_info=True)
            raise AppException(
                message=msg,
                status_code=status.HTTP_400_BAD_REQUEST,
                details={"error_code": error_code.value, "original_error": str(e)},
            ) from e
        except json.JSONDecodeError as e:
            error_code = ErrorCodes.VALIDATION_FAILED
            msg = f"LLM returned invalid JSON: {e}"
            logger.error("[ChatParser] %s: %s", error_code.name, msg, exc_info=True)
            raise AppException(
                message=msg,
                status_code=status.HTTP_400_BAD_REQUEST,
                details={"error_code": error_code.value, "original_error": str(e)},
            ) from e
        except Exception as e:
            if isinstance(e, AppException):
                raise e

            error_code = ErrorCodes.INTERNAL_SERVER_ERROR
            msg = f"LLM generation failed: {e}"
            logger.error("[ChatParser] %s: %s", error_code.name, msg, exc_info=True)
            raise AppException(
                message=msg, status_code=status.HTTP_502_BAD_GATEWAY, details={"error_code": error_code.value}
            ) from e
