from pydantic import BaseModel, ConfigDict, Field

class TokenUsage(BaseModel):
    """Strictly typed token usage statistics."""
    prompt_tokens: int = Field(default=0, description="Tokens used in the prompt.")
    completion_tokens: int = Field(default=0, description="Tokens generated by the model.")
    total_tokens: int = Field(default=0, description="Total tokens used.")
    cost_usd: float = Field(default=0.0, description="Estimated cost in USD.")

    model_config = ConfigDict(frozen=True, strict=True)
    
    def __add__(self, other: "TokenUsage") -> "TokenUsage":
        """Allows adding two TokenUsage objects together."""
        return TokenUsage(
            prompt_tokens=self.prompt_tokens + other.prompt_tokens,
            completion_tokens=self.completion_tokens + other.completion_tokens,
            total_tokens=self.total_tokens + other.total_tokens,
            cost_usd=self.cost_usd + other.cost_usd,
        )

class UsageReport(BaseModel):
    """Report for aggregated usage statistics across different scopes."""
    scope: str = Field(..., description="Scope of the report (system, organization, user).")
    entity_id: str | None = Field(default=None, description="ID of the entity (if not system).")
    period: str = Field(..., description="Reporting period (e.g., '2026-02', 'all-time').")
    
    usage: TokenUsage = Field(default_factory=TokenUsage, description="Aggregated token and cost statistics.")
    
    quota_limit_usd: float | None = Field(default=None, description="Quota limit in USD, if applicable.")
    percentage_used: float | None = Field(default=None, description="Percentage of quota used, if applicable.")
    
    model_config = ConfigDict(frozen=True, strict=True)
