//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:copy_with_extension/copy_with_extension.dart';
import 'package:json_annotation/json_annotation.dart';

part 'token_usage.g.dart';


@CopyWith()
@JsonSerializable(
  checked: true,
  createToJson: true,
  disallowUnrecognizedKeys: false,
  explicitToJson: true,
)
class TokenUsage {
  /// Returns a new [TokenUsage] instance.
  TokenUsage({

     this.promptTokens = 0,

     this.completionTokens = 0,

     this.totalTokens = 0,

     this.costUsd = 0.0,
  });

      /// Tokens used in the prompt.
  @JsonKey(
    defaultValue: 0,
    name: r'prompt_tokens',
    required: false,
    
  )


  final int? promptTokens;



      /// Tokens generated by the model.
  @JsonKey(
    defaultValue: 0,
    name: r'completion_tokens',
    required: false,
    
  )


  final int? completionTokens;



      /// Total tokens used.
  @JsonKey(
    defaultValue: 0,
    name: r'total_tokens',
    required: false,
    
  )


  final int? totalTokens;



      /// Estimated cost in USD.
  @JsonKey(
    defaultValue: 0.0,
    name: r'cost_usd',
    required: false,
    
  )


  final num? costUsd;





    @override
    bool operator ==(Object other) => identical(this, other) || other is TokenUsage &&
      other.promptTokens == promptTokens &&
      other.completionTokens == completionTokens &&
      other.totalTokens == totalTokens &&
      other.costUsd == costUsd;

    @override
    int get hashCode =>
        promptTokens.hashCode +
        completionTokens.hashCode +
        totalTokens.hashCode +
        costUsd.hashCode;

  factory TokenUsage.fromJson(Map<String, dynamic> json) => _$TokenUsageFromJson(json);

  Map<String, dynamic> toJson() => _$TokenUsageToJson(this);

  @override
  String toString() {
    return toJson().toString();
  }

}

