import copy

import pytest

from backend_v2.models.dtos.synthesis import SynthesisOutputDTO


def test_synthesis_output_dto_schema_deepcopy_bug():
    """Tier 4 Bug Hunting Regression Test:
    Ensures that the JSON Schema generated by SynthesisOutputDTO can be deepcopied.
    If a variable like SYNTHESIS_XAI_HIGHLIGHTS_MANDATE is not imported, it becomes a 
    ForwardRef/cell object inside the Annotated description, crashing LiteLLM during
    Vertex AI execution when the schema is deepcopied.
    """
    try:
        json_schema = SynthesisOutputDTO.model_json_schema()
        # This will raise TypeError: cannot pickle 'cell' object if the bug is present
        copy.deepcopy(json_schema)
    except TypeError as e:
        if "cell" in str(e):
            pytest.fail(f"SynthesisOutputDTO JSON schema deepcopy failed due to ForwardRef cell issue: {e}")
        raise e
