"""Search hooks for executing external searches (e.g. Google)."""

import logging

from backend.exceptions import AppException, ErrorCodes
from backend.hooks.search_client import VertexAISearchTool
from backend.models.domain.analyst import AnalystOutput, SearchResult, SearchResultItem
from backend.models.domain.inputs import WorkflowInputs
from backend.models.state import WorkflowState
from backend.utils.pydantic_utils import inflate

logger = logging.getLogger(__name__)


from typing import Any
async def execute_google_search(state: WorkflowState, repository: Any = None) -> WorkflowState:
    """HOOK: execute_google_search.

    Executes Google Search via Vertex AI Grounding based on hypotheses generated by the Analyst agent.

    Logic (Fail Fast):
    1. Extracts 'analyst' data. If missing, logs warning and returns (safe default for optional step).
    2. Inflates 'AnalystOutput'. If invalid, RAISES AppException (Strict Schema).
    3. Extracts queries. If none, returns.
    4. Initializes Tool. If config missing, RAISES ConfigurationError (Crashing is better than silent fail).
    5. Executes Search. If fails, RAISES AppException.
    6. Updates State with strictly typed 'SearchResult'.

    Args:
        state (WorkflowState): Current state containing analysis hypotheses.

    Returns:
        WorkflowState: Updated state with search results.

    Raises:
        AppException: If configuration is missing, data is invalid, or execution fails.
    """
    logger.debug("[SearchHook] execute_google_search CALLED (Vertex AI Grounding)")

    # Strict Enforce: State must be WorkflowState object
    if isinstance(state, dict):
        raise AppException(
            message="Search Hook received dict state. Strict Pydantic Enforcement Violation.",
            status_code=500,
            details={"error_code": ErrorCodes.INVALID_OUTPUT_SCHEMA},
        )

    # 1. Extract Analyst Output (Strict Type Check)
    step_analyst_data = state.context_variables.get("step_analyst")  # Keep for warning check
    analyst_output = state.get_context("step_analyst", AnalystOutput)

    if not step_analyst_data:
        # If the step was skipped or not executed, we can't search.
        # This is a valid "no-op" scenario, not a crash.
        logger.warning("[SearchHook] 'step_analyst' (Analyst) not found in context. Skipping search.")
        return state

    # 2. STRICT INFLATION (Fail Fast)
    # inflate() handles validation errors by logging and returning None.
    # analyst_output already set via get_context

    if not analyst_output:
        # If raw data exists but fails validation -> CRITICAL INTEGRITY ERROR
        error_code = ErrorCodes.AGENT_SCHEMA_VALIDATION_FAILED
        msg = f"Invalid AnalystOutput data in context. Failed to inflate {type(step_analyst_data)}."
        logger.error(f"[SearchHook] {error_code}: {msg}")
        raise AppException(message=msg, status_code=500, details={"error_code": error_code, "step": "step_search"})

    # 3. Extract Queries
    queries: list[str] = []
    if analyst_output.hypotheses:
        for hyp in analyst_output.hypotheses:
            if hyp.search_query and len(hyp.search_query.strip()) > 3:
                queries.append(hyp.search_query)

    if not queries:
        logger.debug("[SearchHook] No valid queries generated. Skipping search.")
        return state

    # 4. Initialize Tool via SSOT Factory
    from backend.llm.client import LLMClient
    from backend.exceptions import ConfigurationError
    import asyncio
    
    # Hooks executing within an async workflow loop should safely execute this.
    # Note: If executed synchronously, this would require `asyncio.run()`, 
    # but the framework is expected to handle async properly in `execute_google_search` 
    # because the hook signature itself is `async def`.
    try:
        search_client = await LLMClient.from_strategy("SearchHook", repository=repository)
        model_id_full = search_client._config.model_name if search_client._config else None
        
        # Vertex tools expect the raw model id without provider prefix 'vertex_ai/'
        if model_id_full and model_id_full.startswith("vertex_ai/"):
            model_id = model_id_full.split("/")[-1]
        else:
            model_id = model_id_full
            
        if not search_client._config or not search_client._config.supports_grounding:
            # We strictly enforce that the allocated strategy must support grounding.
            raise ConfigurationError("The assigned 'SearchHook' strategy does not have supports_grounding=True.")

        tool = VertexAISearchTool(model_id=model_id)
    except ConfigurationError as e:
        error_code = ErrorCodes.SEARCH_CONFIG_ERROR
        msg = f"Search configuration failed: {e.message}"
        logger.error(f"[SearchHook] {error_code.name}: {msg}")
        raise ConfigurationError(msg, details={"error_code": error_code})

    # 5. Extract Language (Strict Inputs)
    input_data = state.context_variables.get("inputs")
    inputs = inflate(input_data, WorkflowInputs)
    lang_code = inputs.language if inputs else "en"

    # 6. Execute Search (Vertex AI Grounding)
    try:
        logger.debug(f"[SearchHook] Executing {len(queries)} searches (Lang: {lang_code})...")

        # tool.search raises ServiceUnavailableError or AppException on failure.
        client_results = tool.search(queries, limit=3, language=lang_code)

        # STRICT Enforce: Tool must return Objects, not dicts.
        if client_results and isinstance(client_results[0], dict):
            error_code = ErrorCodes.INVALID_OUTPUT_SCHEMA
            msg = "Search Tool returned dicts instead of Pydantic Models. Strict Pydantic Enforcement Violation."
            logger.error(f"[SearchHook] {error_code.name}: {msg}")
            raise AppException(message=msg, status_code=500, details={"error_code": error_code})

        # Convert Client Model -> Domain Model (Strict Mapping)
        domain_items: list[SearchResultItem] = []
        for c_res in client_results:
            domain_items.append(SearchResultItem(title=c_res.title, link=c_res.link, snippet=c_res.snippet))

        search_result = SearchResult(results=domain_items)

        # 7. Update State (Immutable)
        # Data Hygiene: We NO LONGER inject search snippets directly into AnalystOutput.rag_evidence. 
        # This prevents massive Context Bloat (+60k tokens) for downstream agents.
        # The data is kept cleanly isolated in 'search_result' for targeted use only.
        new_context = state.context_variables.copy()
        new_context["search_result"] = search_result

        logger.info(f"[SearchHook] Search complete. Found {len(domain_items)} results. Isolated to 'search_result'.")
        return state.model_copy(update={"context_variables": new_context})

    except AppException as e:
        # Re-raise known AppExceptions (ConfigurationError, ServiceUnavailableError, etc.)
        # This preserves the original error code and details.
        raise e
    except Exception as e:
        # Catch unexpected unknown errors and wrap them
        error_code = ErrorCodes.SEARCH_EXECUTION_FAILED
        msg = f"Unexpected error in Search Hook: {e}"
        logger.error(f"[SearchHook] {error_code.name}: {msg}", exc_info=True)
        raise AppException(message=msg, status_code=500, details={"error_code": error_code}) from e
