"""Search hooks for executing external searches (e.g. Google)."""

import json
import logging
import os

from googleapiclient.discovery import build

from backend.models.state import WorkflowState

logger = logging.getLogger(__name__)


def execute_google_search(state: WorkflowState) -> WorkflowState:
    """HOOK: execute_google_search.

    Executes Google Custom Search API based on hypotheses generated by the Analyst agent.

    Logic:
    1. Extracts 'hakusana_ehdotus' (search query) from 'step_analyst.hypoteesit'.
    2. Executes up to 3 queries using the Google Custom Search API.
    3. Stores results in 'aux_data.google_search_results' for downstream agents.

    Prerequisites:
        - Env vars: GOOGLE_SEARCH_API_KEY, GOOGLE_SEARCH_CX.

    Args:
        state (WorkflowState): Current state containing analysis hypotheses.

    Returns:
        WorkflowState: Updated state with search results.

    """

    logging.debug("[SearchHook] Running execute_google_search...")

    from backend.hooks.search_client import GoogleSearchTool

    tool = GoogleSearchTool()
    if not tool._service:
         state.aux_data["google_search_results"] = "Search disabled (Missing API Keys)"
         return state

    queries = []

    # Extract queries from Hypotheses (Step 2 Analyst)
    if state.step_analyst and state.step_analyst.hypoteesit:
        logging.debug(f"   [HOOK] Found {len(state.step_analyst.hypoteesit)} hypotheses.")
        for hyp in state.step_analyst.hypoteesit:
            # ONLY use explicit search suggestions (external facts)
            # Logic: Must have suggestion > 3 chars
            if hyp.hakusana_ehdotus and len(hyp.hakusana_ehdotus.strip()) > 3:
                queries.append(hyp.hakusana_ehdotus)
    else:
        logging.debug("   [HOOK] No hypotheses found. Using fallback.")
       
    if not queries:
        return state

    try:
        # Use Tool
        results = tool.search(queries, limit=3)
        state.aux_data["google_search_results"] = json.dumps(results, indent=2)

    except Exception as e:
        logger.error(f"   [SearchHook] Search failed: {e}")
        state.aux_data["google_search_results"] = f"Search failed: {str(e)}"

    return state
