name: ci 
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Generate OpenAPI Spec
        env:
          VERTEX_LOCATION: "europe-north1"
        run: uv run backend/scripts/generate_openapi.py

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Deploy Documentation
        run: uv run mkdocs gh-deploy --force
