// Mocks generated by Mockito 5.4.6 from annotations
// in client_app/test/features/studio/presentation/providers/studio_workflow_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:client_app/features/studio/data/schema_repository.dart' as _i3;
import 'package:client_app/features/studio/data/studio_repository.dart' as _i5;
import 'package:client_app/features/studio/domain/models/json_schema.dart'
    as _i2;
import 'package:client_app/features/studio/domain/models/workflow_summary.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeJsonSchema_0 extends _i1.SmartFake implements _i2.JsonSchema {
  _FakeJsonSchema_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SchemaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSchemaRepository extends _i1.Mock implements _i3.SchemaRepository {
  @override
  _i4.Future<_i2.JsonSchema> fetchSchema(String? componentType) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSchema, [componentType]),
            returnValue: _i4.Future<_i2.JsonSchema>.value(
              _FakeJsonSchema_0(
                this,
                Invocation.method(#fetchSchema, [componentType]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.JsonSchema>.value(
              _FakeJsonSchema_0(
                this,
                Invocation.method(#fetchSchema, [componentType]),
              ),
            ),
          )
          as _i4.Future<_i2.JsonSchema>);
}

/// A class which mocks [StudioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStudioRepository extends _i1.Mock implements _i5.StudioRepository {
  @override
  _i4.Future<List<_i6.WorkflowSummary>> fetchWorkflows() =>
      (super.noSuchMethod(
            Invocation.method(#fetchWorkflows, []),
            returnValue: _i4.Future<List<_i6.WorkflowSummary>>.value(
              <_i6.WorkflowSummary>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i6.WorkflowSummary>>.value(
                  <_i6.WorkflowSummary>[],
                ),
          )
          as _i4.Future<List<_i6.WorkflowSummary>>);

  @override
  _i4.Future<void> updateWorkflow(String? id, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkflow, [id, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> fetchWorkflow(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchWorkflow, [id]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}
